### ISSUE TITLE
[Quest] Bang a Gong !

### ISSUE THREAD

**Issue by opalq** [Warglaive/DragonFireOriginal-3.3.5#1]
http://www.wowhead.com/quest=8743/bang-a-gong

Това е последният куест от chain-a за отварянето на вратите на Ahn'Qiraj, който дава Scarab Lord титлата и Black Qiraji Battle Tank маунта. След големия update, хората, които бяха стигнали до последния работещ куест от chain-a, можеха да изпълнят куеста treasure of the Timeless One, който дава epic weapon- и като награда. (Аз го минах, като най- вероятно така се прецаках при евентуално оправяне на последната част от поредицата)

Въпросният куест обаче, се води след куестите Might of Kalimdor и Bang a Gong! (т.е все едно гонга е бит, минал е 10 часовия event (през който други играчи, минали Bang a Gong могат да получат mount и titla)

Накратко- куестът, който дава така желаните награди го няма. Въпросът ми възможно ли е, и дали ще се направи работещ ? Или умишлено е пропуснат, и няма да има повече развръзка по тази поредица ?

**Comment by Ritokoko** [comment]
Здрасти,поради същата причина пиша и аз .Защото направих следните два куеста "  http://prikachi.com/images.php?images/964/7639964w.jpg " и " http://prikachi.com/images.php?images/968/7639968Q.jpg " и при мен се получи същата работа да не ми даде куеста Bang a Gong!.И аз както останалите се интересувам дали ще има развитие по този въпрос и дали ще можем да си вземем наградите от куестите .

**Comment by FALL1N1** [comment]
Изпълнихте ли http://www.wowhead.com/quest=8742 ?

**Comment by AnTOLI** [comment]
Аз всички са го минали без последния куест.

**Comment by FALL1N1** [comment]
Ясно, оправих го, трябва да работи!

**Comment by AnTOLI** [comment]
ок

**Comment by AnTOLI** [comment]
Не го дава последния куест.

**Comment by FALL1N1** [comment]
Оправен, добавен е старт/финал на куеста в GOBJECT:180717(Scarab Gong)
