### ISSUE TITLE
HOR Event bug

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#10]
Евента на HOR работи но на 3-та врата която Sylvana трябва да счупи вратата става невидима играчите могат да минават ама Sylvana стои и стрела по невидими точки.Проблема да не може да мине е бугнати Голове които стоя до Lich kinga и не идват а трябва сам да утидеш да ги извикаш.Друго после като трябва да дава лоота кораба е невидими и не виждаме кораба и немойе да ступим на него да земем лоота и да се портнем и не виждаме как кораба чупи прохода на Lich king. Благодаря за вниманието

**Comment by FALL1N1** [comment]
Оправен!
