### ISSUE TITLE
Quest - That's Abominable! - Class B #13276 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#100]
Започва от http://www.wowhead.com/npc=29795/koltira-deathweaver който ни дава този куест http://www.wowhead.com/quest=13288/thats-abominable.
При назе ги няма магите на пета 
http://www.wowhead.com/npc=31692/reanimated-abomination
1) - Attack • Basic Pet Ability. http://www.wowhead.com/spell=6603
3) - Stay • Basic Pet Ability.
4) - Flatuate • Special Ability. http://www.wowhead.com/spell=59564
5) - Burst at the Seams • Special Ability. http://www.wowhead.com/spell=59576
9) - Defensive • Basic Pet Ability.
За изпъляването на куета трябва да използваме 5) Burst at the Seams и да взривим 
15х Icy Ghoul http://www.wowhead.com/npc=31142
15х Vicious Geist http://www.wowhead.com/npc=31147
15 х Risen Alliance Soldier http://www.wowhead.com/npc=31205

Проблема при нас е , че когато призовем Reanimated Abomination - а не излиза Secondary Action Bar ,чрез който да го управляваме , което прави изпълнението на куеста невъзможно.
Ето и видео на куеста http://www.youtube.com/watch?v=YIGAmf5si-o

**Comment by AnTOLI** [comment]
По добре ауто го направете скоро няма че има фикс за това.

**Comment by FALL1N1** [comment]
Авто.
