### ISSUE TITLE
Quest - Matchmaker - Class B #13147

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#101]
http://www.wowhead.com/quest=13147
Куеста се взема от Vereth the Cunning ( http://www.wowhead.com/npc=30944 ) в Icecrown.
Изисква използването на ghoul - Lithe Stalker ( http://www.wowhead.com/npc=30894 ).След използването на умението на ghoul-а - Throw Rock ( http://www.wowhead.com/spell=58283 ), вместо да "започнат работа", NPC-тата (http://www.wowhead.com/npc=31320/) се нахварлят на самия ghoul.

**Comment by Chillie** [comment]
Работи вече ...
