### ISSUE TITLE
Achievement  [Lance a Lot]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#102]
http://www.wowhead.com/achievement=2836 Не работи.

**Comment by AnTOLI** [comment]
Че има ли script по achievement :)

**Comment by AnTOLI** [comment]
Като играч е на Mounts не му слага буфа за Achievement,
На http://www.wowhead.com/npc=33749/undercity-champion пише invalid target.
Не може да се бием с Aliance champion за Achievement.
http://www.wowhead.com/npc=33480/ironforge-champion#screenshots

**Comment by FALL1N1** [comment]
Fixed

**Comment by Chillie** [comment]
Все още не си отчита за  [Lance a Lot] 
http://wotlk.openwow.com/achievement=2836

**Comment by AnTOLI** [comment]
Само хорде отчита алита не може да се бием.
