### ISSUE TITLE
Quest - Drag and Drop 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#104]
http://www.wowhead.com/quest=13352

Куест предмета трябва да се пусне върху Dark Subjugator - http://www.wowhead.com/npc=32236 след това този моб се превърща в human female и този прилеп идва, и взима моба и го пуска от въздуха.

Това е текста, когато от Dark Subjugator стане на human female трябва да излезe:
Dark Subjugator: Okay, who's the joker that threw an orb at me?
Dark Subjugator: NOOOOOO!
Dark Subjugator: I feel funny all of a sudden. Er?!
Dark Subjugator: You've got it all wrong. I'm a subjugator!

**Comment by AnTOLI** [comment]
За куеста Фикс https://github.com/TrinityCore/TrinityCore/commit/4b9002a4deec32fc58c917ffde4c632011d1b2fe

**Comment by AnTOLI** [comment]
Става ли фикса.!

**Comment by FALL1N1** [comment]
Става, добавен.
