### ISSUE TITLE
Quest - The Reckoning

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#106]
http://www.wowhead.com/quest=13047/the-reckoning Не работи липсва http://www.wowhead.com/npc=30295 Thorim на моста и след това да го  стартираме малък евент до Temple of Wisdom в които  започва диалог с Loken.

**Comment by AnTOLI** [comment]
Не може да се мине.

**Comment by AnTOLI** [comment]
До колкото виждам е ауто направен махнете го. Fix за куеста https://github.com/TrinityCore/TrinityCore/commit/03f32bee7bf264984189e233af9f7998b625

**Comment by AnTOLI** [comment]
Махнете ауто куеста  и тесваите фикса

**Comment by FALL1N1** [comment]
Готов.

**Comment by AnTOLI** [comment]
Работи :+1:
