### ISSUE TITLE
Quest - Trial of the Naaru: Mercy

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#108]
http://www.wowhead.com/quest=10884 Не работи липсва http://www.wowhead.com/npc=17301 Нпцто в The Shattered Halls http://www.wowhead.com/zone=3714 от които пада куест итема http://www.wowhead.com/item=31716.

**Comment by Dragonspower** [comment]
https://github.com/DragonFire/3.3.5/issues/33
