### ISSUE TITLE
Spell Reflection Warrior 

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#11]
магията още не работи както трябва рефлектва само 1 магия а трабва да рефлектни сички маги които са пуснати в тази секунда може да се тества дали е оправен когато рефлектне сички удари на мисилите на mage или илузите на mageблагодаря

**Comment by JunkyBG** [comment]
@stefanokis още ли е така?

**Comment by FALL1N1** [comment]
Оправено!
