### ISSUE TITLE
[My Girl Loves to Skadi All the Time] - Achievement

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#110]
Defeat Skadi the Ruthless in Utgarde Pinnacle on Heroic Difficulty after having killed Grauf from 100% to dead in a single pass.

Постижението се изпълнява с босът Skadi the Ruthless ( http://old.wowhead.com/npc=26693 ) в Utgarde Pinnacle. Целта му е да свалите Skadi the Ruthless ( http://old.wowhead.com/npc=26693 ) от въздуха за едно излитане (когато излети преди да се спусне към вас). Това е в рамките на около 5-6 секунди. За целта никой не стреля с харпун докато 3 ма от вас не съберат по 2 стрели. Застават един до друг... и когато видите че се спуска към вас и излита отново - тези 3 мата изстрелват един след друг стрелите си (нужни са 5 истрела) за да свалите Grauf ( http://old.wowhead.com/npc=26893 ) който бива язден от Skadi the Ruthless ( http://old.wowhead.com/npc=26693 ). Ако това стане в рамките на едно и също излитане (от 1 вата до 5 тата стрела) след като убиете боса... трябва да получите постижението.
Бъгът е, че босът в сървъра иска различен брой стрели (незнам някога явмо мисва ли или...) но дори и да падне във 1 излитане (от първата до последната стрела) пак не го отчита. За съмия бос трябва да са нужни точно 3 стрели. Не повече - не по малко.

**Comment by opalq** [comment]
Всъщност, от пач 3.3.2 насам, са необходими 3 стрели за свалянето му.

**Comment by AnTOLI** [comment]
Направте го хакфикс поне да го вземе постижението. ;с

**Comment by AnTOLI** [comment]
Развитие от боса има ли.?

**Comment by AnTOLI** [comment]
Маи така че остане.

**Comment by AnTOLI** [comment]
Стрели са бъгави и умираме всчки и после боса не може да се лооти...

**Comment by AnTOLI** [comment]
Работи :+1:

**Comment by AnTOLI** [comment]
За Боса дано да става фикса http://hg.assembla.com/LoL_Trinity/file/74bd47d14bab/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp

**Comment by AnTOLI** [comment]
За Боса дано да става фикса. https://github.com/mik1893/TrinityCore/commit/538bf8d1091e27c21d5b8c02c9861a9387bd83e4

**Comment by FALL1N1** [comment]
Не става, за по-стар TrinityCore e. Взех някой неща от тук там, оправих синтаксиса и е сложен, пиши ако има нещо и отвори отново.

**Comment by AnTOLI** [comment]
Така отидохме при боса пускаме  харпуни и боса не слиза при назе около 20-30  истрела и не идва при наз боса (необходими 3 стрели за свалянето му).
