### ISSUE TITLE
[Achievement] A-bomb-inable

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#111]
http://www.wowhead.com/achievement=3848 Не работи постижението не ги ототчита като ги сложим.

**Comment by AnTOLI** [comment]
Fix за постижението http://paste.org.ru/?j4avq8

**Comment by AnTOLI** [comment]
Става ли фикса.?

**Comment by FALL1N1** [comment]
Добавен.

**Comment by AnTOLI** [comment]
Не работи не ги ототчита.

**Comment by AnTOLI** [comment]
Работи. :+1:
