### ISSUE TITLE
[Achievement] Isle of Conquest All-Star

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#112]
http://www.wowhead.com/achievement=3845 Не работи не го отчита за постижението като.
1. Убит играч в бг то.
2.Превзета база.
3.Защитена база.

**Comment by AnTOLI** [comment]
И до днес не работи. :(

**Comment by AnTOLI** [comment]
До днес не работи

**Comment by FALL1N1** [comment]
rewrite na bg, skoro
