### ISSUE TITLE
Achievement: [Disarmed (10 player)]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#116]
http://www.wowhead.com/achievement=2953/disarmed-10-player
Въпросното постижение НЕ работи, преди е работило мисля, но го тествах и не работи в момента.
Мисля, че на 25 също не работи.

**Comment by Warglaive** [comment]
Все още не работи.

**Comment by FALL1N1** [comment]
#661
