### ISSUE TITLE
Boss: Hodir ( Ulduar )

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#117]
При победа над бос-а се взимат 4 постижения, дори да не са изпълнени както трябва.
http://www.wowhead.com/achievement=3182/i-could-say-that-this-cache-was-rare-10-player
http://www.wowhead.com/achievement=2967/getting-cold-in-here-10-player
http://www.wowhead.com/achievement=2961/cheese-the-freeze-10-player
http://www.wowhead.com/achievement=2963/i-have-the-coolest-friends-10-player

**Comment by AnTOLI** [comment]
Така че си остане маи няма кои да го оправи. :)

**Comment by FALL1N1** [comment]
Така ще си остане, да.
test

**Comment by Warglaive** [comment]
Все още НЕ отчита за  [The Keepers of Ulduar 10/25 ]
http://wotlk.openwow.com/achievement=2890
http://wotlk.openwow.com/achievement=2891
