### ISSUE TITLE
Icecrown quest : "By fire be purged "

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#119]
http://www.wowhead.com/quest=13211/by-fire-be-purged
Като се използва итема върху труповете http://www.wowhead.com/item=43524 не отчита за куеста .

**Comment by Chillie** [comment]
Работи вече ..

**Comment by AnTOLI** [comment]
Куест итема не работи като се използва итема върху труповет. 
Fix https://github.com/TrinityCore/TrinityCore/commit/dacc4b8a319ec835e89a6ae1cfe61158e7e4f991
