### ISSUE TITLE
Quest:  [The Demoniac Scryer]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#122]
http://www.wowhead.com/quest=10838/the-demoniac-scryer
След поставяне на Demoniac Scryer (Provided) трябва да се изчака малко и да се случи нещо, но нищо не се случва.

**Comment by AnTOLI** [comment]
Fix https://github.com/TrinityCore/TrinityCore/commit/aceec683253c62293d1b94e365ffe2a2e8721e3c

**Comment by FALL1N1** [comment]
Fixed
