### ISSUE TITLE
Quest:  [The Cipher of Damnation]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#129]
http://www.wowhead.com/quest=10588/the-cipher-of-damnation
При този Quest, липсва NPC-то което трябва да бъде убито:
http://www.wowhead.com/npc=21181

**Comment by Dragonspower** [comment]
Въпросния creature се призовава с quest предмета http://www.wowhead.com/item=30657.
