### ISSUE TITLE
Icecrown quests: [Banshee's Revenge]  [The Story Thus Far...] [An Undead's Best Friend] [New Recruit]

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#131]
http://www.wowhead.com/quest=13142/banshees-revenge - не тръгва евента и не се появява елита,който трябва да се убие,за да се изпълни куеста.

http://www.wowhead.com/quest=12807/the-story-thus-far - не тръгва диалога.

http://www.wowhead.com/quest=13169 - дори не поглеждат месото,което им се дава :D

http://www.wowhead.com/quest=13143/new-recruit - амиии онова дребното мобче,което трябва да се плени не следва господаря си (не знам по какъв друг начин да го обясня :D:D ) ето клипче https://www.youtube.com/watch?v=gJEVSXf6ICg

**Comment by Dragonspower** [comment]
http://www.wowhead.com/quest=12807/the-story-thus-far  е направен autocomplete.
