### ISSUE TITLE
Storm Peaks quests ...

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#132]
[Going Bearback] [You Can't Miss Him] [In Memoriam] [Raising Hodir's Spear] [Spy Hunter] за да се минат тези трябва да те мята в друга фаза,а не го прави..

 [Changing the Wind's Course] http://www.wowhead.com/quest=13058/changing-the-winds-course - не работи куест итема както трябва,не може и да се извика и елита. http://www.wowhead.com/item=42918

 [Jormuttar is Soo Fat...] http://www.wowhead.com/quest=13011/jormuttar-is-soo-fat - не дава да се одере мечката като се убие,за да се вземе месото,че да се извика Jormuttar, с този итем http://www.wowhead.com/item=42732 .

 [Sniffing Out the Perpetrator] http://www.wowhead.com/quest=12855/sniffing-out-the-perpetrator Tracker Thulin slain е ок ,но Track down thief не може да се мине,тъй като куест итема не работи,а като вземеш куеста и го откажеш куест итема изчезва и при следващото вземане не ти го дава.

 [Destroy the Forges!]  http://www.wowhead.com/quest=12988/destroy-the-forges няма никакво движение след като се използва куест итема и следователно не отчита https://www.youtube.com/watch?v=swMq763EMTM ето и клипче .

You Can't Miss Him 
http://wotlk.openwow.com/quest=12966
До момента неможе да се вземе.

Та,това са за сега :D  аз се изморих само докато ги изпробвам и напиша,па успех с оправянето :( .

**Comment by Dragonspower** [comment]
http://www.wowhead.com/quest=13011 Jormuttar е spawnat на мястото му.

**Comment by AnTOLI** [comment]
Fix за Куеста [Sniffing Out the Perpetrator]  https://github.com/TrinityCore/TrinityCore/commit/50853755d993f941973137d6db30bf53f1ac4b3d

**Comment by AnTOLI** [comment]
До този момент не може да се язди тигара.

**Comment by Warglaive** [comment]
You Can't Miss Him 
http://wotlk.openwow.com/quest=12966
До момента неможе да се вземе.

**Comment by Warglaive** [comment]
До момента няма промяна.
