### ISSUE TITLE
Redemption[Spell] [Paladin]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#134]
http://www.wowhead.com/spell=7328/redemption
Въпросният спел, трябва да се влияе от Haste статса, но това не е така.
Дори при 1200 Haste, spell-а се каства за 10 секунди, а трябва да е доста по-малко както при всички други класове.

**Comment by FALL1N1** [comment]
test

**Comment by FALL1N1** [comment]
fixed

**Comment by Warglaive** [comment]
http://wotlk.openwow.com/spell=7328
http://wotlk.openwow.com/spell=7329
http://wotlk.openwow.com/spell=10322
http://wotlk.openwow.com/spell=10324
http://wotlk.openwow.com/spell=20772
http://wotlk.openwow.com/spell=20773
http://wotlk.openwow.com/spell=48949
http://wotlk.openwow.com/spell=48950
