### ISSUE TITLE
Title : Bloodsail Admiral

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#137]
Такаа, като трепиш мобове за да дигнеш репутация към Bloodsail Admiral ти дава репутация и към Booty ,a вместо да дава трябва да сваля към тях и по този начин  не може да се мине куеста Avast Ye, Admiral! http://www.wowhead.com/quest=4621/avast-ye-admiral и следователно не може да се вземе и http://wod.wowhead.com/achievement=871 . :)

**Comment by FALL1N1** [comment]
#447
