### ISSUE TITLE
Ach Master of Arms

### ISSUE THREAD

**Issue by HorrorisT** [Warglaive/DragonFireOriginal-3.3.5#138]
Здравейте! Искам да попитам поради какво се е наложило промяна на този Achievement ? Преди можеше да се тренира на Dummy-та а сега не може ? 
Единствения начин за качване на скил си остава като се бият мобове и босове ли ?

**Comment by Chillie** [comment]
Не мога да повярвам,че репортваш нещо,което работи както трябва вече и ДА единствения начин е този ,преди с  Dummy-та си беше пропуск,бъг.

**Comment by FALL1N1** [comment]
Да, единствения начин е с босове и мобове, така трябва да е.
