### ISSUE TITLE
Netherstorm quests...

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#144]
Troublesome Distractions http://www.wowhead.com/quest=10273/troublesome-distractions - трябва да ти даде да говориш с Wind Trader Marid http://www.wowhead.com/npc=20071 и да го биеш докато остане на малко,но като говориш не става unfriendly ..

Measuring Warp Energies http://www.wowhead.com/quest=10313/measuring-warp-energies - като се използва итема не отчита ...

Teleport This! http://www.wowhead.com/quest=10857/teleport-this - като използваш итема за да контролираш моба,че да вземе телепортите, ти маха контрола веднага..

Delivering the Message http://www.wowhead.com/quest=10406/delivering-the-message
Escape from the Staging Grounds http://www.wowhead.com/quest=10425/escape-from-the-staging-grounds
Sabotage the Warp-Gate! http://www.wowhead.com/quest=10310/sabotage-the-warp-gate - при тези 3 куеста проблема е един и същ,не тръгва NPC-то,което трябва да се ескортне .

**Comment by AnTOLI** [comment]
Fix за  Куеста (Delivering the Message) https://github.com/tkrokli/TrinityCore/commit/a1041e7f7fdc05a5fd465da5f97a4b117b3b05f7
