### ISSUE TITLE
[Quest] [Stasis Chambers of the Mana-Tombs] id 10977

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#147]
Няма я сферата http://www.wowhead.com/quest=10977#screenshots:id=181971 в инса на http://www.wowhead.com/quest=10977#.Mana-Tombs. Tя трябва за да се мине куеста.

**Comment by AnTOLI** [comment]
Куеста е ауто но не  мога да ги мина.

**Comment by AnTOLI** [comment]
Пак си е така.

**Comment by AnTOLI** [comment]
Няма си я сферата в инса ощте.

**Comment by Warglaive** [comment]
ИД на обекта не виждам?

**Comment by Warglaive** [comment]
Дай някакви кординати, къде точно трябва да е тази сфера?

**Comment by AnTOLI** [comment]
http://www.wowhead.com/quest=10977/stasis-chambers-of-the-mana-tombs#map:3792.1

**Comment by AnTOLI** [comment]
Сферата е тама но като се отвори не отчита за куеста.
