### ISSUE TITLE
Quest-Fhwoor smash!

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#149]
http://www.wowhead.com/quest=9729
Трябва да се ескортне съответното НПЦ http://www.wowhead.com/npc=17877 до зададената локация.
Проблемът е в това,че ескорт евента не тръгва и няма как да се мине.

**Comment by AnTOLI** [comment]
Ауто и куеста не може да се вземе.

**Comment by FALL1N1** [comment]
Снимка ако може.

**Comment by AnTOLI** [comment]
Самия Куест е син на Нпц то и не може да се вземе или мине.
