### ISSUE TITLE
Quest - [Across Transborea] id 11930

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#150]
http://www.wowhead.com/quest=11930/across-transborea Ескорта на Нпц http://www.wowhead.com/npc=26158 не работи .

**Comment by AnTOLI** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9f99f6bf47650ae55f957fba3fae4481b788dcdb

**Comment by AnTOLI** [comment]
Да се махне ауто на Куеста.

**Comment by FALL1N1** [comment]
Готов.

**Comment by AnTOLI** [comment]
Работи :+1:
