### ISSUE TITLE
Achievement: Lumberjacked id 2979

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#153]
Не работи на 10 http://www.wowhead.com/achievement=2979 и 25 http://www.wowhead.com/achievement=3118.
Fix https://github.com/TrinityCore/TrinityCore/commit/14e4a557ed5063bcb20a3be58547ab1a3f9bb12d

**Comment by Vanx3lzing** [comment]
Може да се вземе след като се убие Фрейа и после елдерите .

**Comment by AnTOLI** [comment]
Как като убием Фрейа и после елдерите няма ли да доидат елдерите като бием Фрейа.?

**Comment by Vanx3lzing** [comment]
Моя грешка извинявам се .Те самите умират след като Фрейа бъде убита.
