### ISSUE TITLE
Quest:  [A Distraction for Akama]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#154]
http://www.wowhead.com/quest=10985/a-distraction-for-akama
NPC-to(http://www.wowhead.com/npc=18528) от което се взима quest-а, не може да го активира.
Предлагам да се направи AutoComplete, докато не се фиксне Blizzlike.

**Comment by AnTOLI** [comment]
Какво стана с този куест.

**Comment by AnTOLI** [comment]
Има написан вече fix https://github.com/TrinityCore/TrinityCore/commit/879678e50f71666646b2489ee2f86336e21a28a0

**Comment by FALL1N1** [comment]
След рестарта ще е активен, пиши ако има нещо.

**Comment by AnTOLI** [comment]
Работи много добре. :)
