### ISSUE TITLE
NPC:Horde Warbringer/Achievement: Call to Arms!

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#157]
http://www.wowhead.com/npc=15350
Въпросното NPC, трябва да дава quests за http://www.wowhead.com/achievement=909/call-to-arms ( 3.3.5 версията ).
Но не ги дава и постижението неможе да се вземе.

**Comment by AnTOLI** [comment]
https://github.com/DragonFire/3.3.5/issues/96

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/96

**Comment by AnTOLI** [comment]
Какво става с тия Куести на Нпцто.
