### ISSUE TITLE
 The Oculus instance...

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#167]
След първия бос трите NPC-та,които трябва да дадат дракони,за да се продължи инстанцията,не дават нищо..скръндзи :D

**Comment by AnTOLI** [comment]
Развитие по инса има ли. :)

**Comment by AnTOLI** [comment]
Развитие по проблема има ли.

**Comment by AnTOLI** [comment]
Потвърждавам.Проблема е, че NPC-тата не дават дракони и така няма шанс инстанцията да бъде продължена.

**Comment by FALL1N1** [comment]
Ще е оправена до няколко дни.

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/274
