### ISSUE TITLE
Quest:Coward Delivery... Under 30 Minutes or it's Free

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#169]
http://www.wowhead.com/quest=11711/coward-delivery-under-30-minutes-or-its-free
Неможе да се говори с NPC(http://www.wowhead.com/npc=25379)
За да се вземе http://www.wowhead.com/npc=25361/alliance-deserter и да се изпълни quest-а.

**Comment by Dragonspower** [comment]
Направен autocomplete

**Comment by AnTOLI** [comment]
Има написан Фикс https://github.com/TrinityCore/TrinityCore/commit/d6cc7c14d523b6fcaa1109ee3f530ece2584cfd2

**Comment by AnTOLI** [comment]
Не мога да го взема от Нпц то куеста.

**Comment by AnTOLI** [comment]
Махнете аутото на куеста и сложете фикса.

**Comment by AnTOLI** [comment]
Развитие по Куеста .!
