### ISSUE TITLE
Quest : [Trial of the Naaru: Mercy]

### ISSUE THREAD

**Issue by Amarelol** [Warglaive/DragonFireOriginal-3.3.5#17]
Куеста не работи.Като отвориш първата врата преди първия бос трябва да се стартура 55 минутен таймер и за това време трябва да убиеш и последния бос и да дропне куест итем....обаче не бачка,ако може да го фикстнете

**Comment by Warglaive** [comment]
http://www.wowhead.com/quest=10884/trial-of-the-naaru-mercy

**Comment by FALL1N1** [comment]
Авто.
