### ISSUE TITLE
skill: Spell Lock

### ISSUE THREAD

**Issue by denislav92** [Warglaive/DragonFireOriginal-3.3.5#177]
mnogo vajen skill na locka raboti napolovina kazva se Spell Lock na edin ot petovete   mu  (Felhunter) slaga silence za 3 sekundi  + "preventing any  spell from that school of magic from being cast for 6 sec." 
a skila slaga samo silence za 3 sekundi bez 2riq efekt ..

**Comment by Roxolana** [comment]
За жалост класът е изключително ощетен. Succubus-ът не работи както трябва, Demonic Circle не работи както трябва, Summon Doomguard направо ни го махнаха и тн. Просто трябва да си Warrior или Paladin, за да ти работи всичко :D

**Comment by JunkyBG** [comment]
Може ли някой да потвърди дали още го има тоя проблем? @Roxolana @denislav92

**Comment by AnTOLI** [comment]
Doomguard го няма в Spellbook.

**Comment by JunkyBG** [comment]
@AnTOLI а в трейнъра има ли го?

**Comment by AnTOLI** [comment]
Няма го

**Comment by AnTOLI** [comment]
Тои се взима с Куести.

**Comment by JunkyBG** [comment]
@AnTOLI да разбирам че е добре?

**Comment by AnTOLI** [comment]
Еми незнам не го мога да го видя и да кажа как е. или е скрит от гм или незнам.

**Comment by AnTOLI** [comment]
И  Inferno не работи добре само stun и до тама.

**Comment by Warglaive** [comment]
Работи.
