### ISSUE TITLE
A-Bomb-inable - Achievement

### ISSUE THREAD

**Issue by Cantouchthis** [Warglaive/DragonFireOriginal-3.3.5#180]
http://www.wowhead.com/achievement=3848 - не отчита бомбите които са били сложени.

**Comment by AnTOLI** [comment]
fix http://paste.org.ru/?j4avq8

**Comment by AnTOLI** [comment]
Сложен ли е фикса.

**Comment by FALL1N1** [comment]
Не, не е за нашето ядро.

**Comment by AnTOLI** [comment]
Дано да го оправш.

**Comment by AnTOLI** [comment]
Работи поне при Хорде.

**Comment by FALL1N1** [comment]
rewrite na bg-to, skoro
