### ISSUE TITLE
Achievement:  [The Keepers of Ulduar (10 player)]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#196]
http://www.wowhead.com/achievement=2890/the-keepers-of-ulduar-10-player
Проблема е, че НЕ отчита Hodir(http://www.wowhead.com/npc=32845/hodir), останалото е наред.

**Comment by AnTOLI** [comment]
https://github.com/TrinityCore/TrinityCore/commit/21820b425b0b573229f683a2d45b23d8a42c888d за http://www.wowhead.com/achievement=2927/hot-pocket-10-player

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи си.
