### ISSUE TITLE
quest: you can't miss him

### ISSUE THREAD

**Issue by denislav92** [Warglaive/DragonFireOriginal-3.3.5#197]
http://www.wowhead.com/quest=12966/you-cant-miss-him
npc-to go nqma na mqstoto s vyproscheto ( ? )

**Comment by Warglaive** [comment]
Проблема е при фазата на NPC(http://www.wowhead.com/npc=30099).

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/132
