### ISSUE TITLE
Quest: The Grand Melee

### ISSUE THREAD

**Issue by denislav92** [Warglaive/DragonFireOriginal-3.3.5#199]
http://www.wowhead.com/quest=13772/the-grand-melee

eto klip kak se minava https://www.youtube.com/watch?v=7rLF_8mgRaY

vzimam pikata, kachvam se na konche, otivam na ringa do oponentite natiskam "i am ready to fight" i nishto ne stava

**Comment by AnTOLI** [comment]
Fix https://github.com/TrinityCore/TrinityCore/commit/d84f7c5ebd173f7d99bc21b564e356110a3e07be

**Comment by FALL1N1** [comment]
Вкаран.

**Comment by AnTOLI** [comment]
Не става нищто като цъкна на (i am ready to fight)
Рестарт на сървера или.

**Comment by FALL1N1** [comment]
След рестарта, да.

**Comment by FALL1N1** [comment]
Всичките фиксове които в момента правя ще са след рестарта.

**Comment by AnTOLI** [comment]
Тия Нпц та от които трябва да  пада Mark of the Valiant  итема нямат опция (i am ready to fight) за почване да битка с тях я няма в тази арена http://www.wowhead.com/quest=13772/the-grand-melee#screenshots:id=258578

**Comment by FALL1N1** [comment]
Репорт в нова тема, това е друг бъг.
