### ISSUE TITLE
Quest: Riding the Red Rocket

### ISSUE THREAD

**Issue by denislav92** [Warglaive/DragonFireOriginal-3.3.5#206]
http://www.wowhead.com/quest=12432/riding-the-red-rocket

https://www.youtube.com/watch?v=lx4RDBHBt8U
vzimam elementa Element 115 sled koeto trqbva da se kacha na raketata no nqma opciq za kachvane a tq samo si sedi spawnata tam

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/145
https://github.com/DragonFire/3.3.5/issues/114
Моля проверяваите дали нещото което репортвате го няма вече репортнато, благодаря.
