### ISSUE TITLE
Аnk Kahet:The old kingdom Instace debuff bug stack

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#21]
Слага курс на играчи като бият босовете да им намалява хпто и курса се стаква

**Comment by AnTOLI** [comment]
Така е. ;s

**Comment by FALL1N1** [comment]
Линк на магията.

**Comment by AnTOLI** [comment]
http://www.wowhead.com/spell=56710/aura-of-lost-hope

**Comment by FALL1N1** [comment]
Оправено.
