### ISSUE TITLE
Quest:  [Among the Champions]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#211]
http://www.wowhead.com/quest=13790/among-the-champions
Неможе да се активира евента при шампионите, нито да се бият, като цяло не работят.
Давам клип на който е показано как точно трябва да се изпълни въпросният quest:
http://youtu.be/s7_vZJOmcOE

**Comment by AnTOLI** [comment]
Натиска се опцията  (I am ready to fight!) и до там. Тои е нужен и заминаване  на http://www.wowhead.com/achievement=2836/lance-a-lot.

**Comment by AnTOLI** [comment]
https://github.com/TrinityCore/TrinityCore/commit/505e8357d517d7757229691b1b14c64249f69509

**Comment by AnTOLI** [comment]
Става ли фикса :)

**Comment by FALL1N1** [comment]
Преправих го и вече става.

**Comment by AnTOLI** [comment]
Като се победи опонента не дава за Куеста  Mark of the Champion http://www.wowhead.com/item=45500/mark-of-the-champion като яздиш само без моулт дава.

**Comment by Warglaive** [comment]
Mark of the champion си дава, тествал съм го.

**Comment by AnTOLI** [comment]
Като си с  моулт не дава марка само буфа му слага на моулт а трябва да го слагa  на играча които го язди.

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/337

**Comment by AnTOLI** [comment]
И хорде не може да се бием натиска се опцията (I am ready to fight!) и до там.
