### ISSUE TITLE
Plucky Johnson

### ISSUE THREAD

**Issue by denislav92** [Warglaive/DragonFireOriginal-3.3.5#212]
http://www.wowhead.com/npc=41135/plucky-johnson

tova e kokoshka i kato napishem /chicken se prevryshta v chovek i trqbva da prodava companion  no ne prodava nishto

http://www.wowhead.com/item=11023 tova e companiona Ancona Chicken

**Comment by Warglaive** [comment]
Ancona Chicken се продава от http://wotlk.openwow.com/npc=6548
Доколкото "Plucky" Johnson - Added in patch 4.0.3 ( Има го, НО не е вендор).
