### ISSUE TITLE
Quest:  [Betrayal]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#213]
http://www.wowhead.com/quest=12713/betrayal
Евента от Drakuru - НЕ РАБОТИ.
Самият quest - работи, главата се взима и quest-а е готов, но по желание на играч го репортвам.

Ето вероятно решение:
https://github.com/TrinityCore/TrinityCore/commit/dd985a8c2635d31b66b12624dfbafe59673d4fdd

**Comment by Warglaive** [comment]
Prio Mid - за постижение е нужен въпросният яуест.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Работи.
