### ISSUE TITLE
NPC:Henry Stern

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#214]
http://www.wowhead.com/npc=8696/henry-stern#comments
Въпросното NPC, трябва да дава:
http://www.wowhead.com/spell=13028#recipes
http://www.wowhead.com/item=3831/recipe-major-trolls-blood-elixir
НО не дава нищо, въпреки че може да се говори с него.

**Comment by Warglaive** [comment]
Проблема стои.

**Comment by Ritokoko** [comment]
Все още го има този проблем.
