### ISSUE TITLE
Quest  [Saving Yenniku] 26305

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#215]
Link: http://www.wowhead.com/quest=592

Kогато се използва Soul Gem(http://www.wowhead.com/item=3912) върху Yenniku (http://www.wowhead.com/npc=2530), Soul Gem трябва да направи Yenniku friendly след това да се говори с него и да ти даде Filled Soul Gem(http://www.wowhead.com/item=3913). Проблемът е че като се използва Soul Gem върху Yenniku го убива..

**Comment by AnTOLI** [comment]
Има Fix вече https://github.com/TrinityCore/TrinityCore/commit/f172d7bf49d813d634eec969f5cac71320326668

**Comment by FALL1N1** [comment]
При рестарт ще е активно, пиши ако има нещо.

**Comment by AnTOLI** [comment]
За се мине иска итема. ако си го направил на ауто  [Filled Soul Gem].

**Comment by FALL1N1** [comment]
Не съм, изчакай до рестарт.
