### ISSUE TITLE
Missing Npc Night Elf Mohawk 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#218]
Липсва това нпц http://www.wowhead.com/npc=31111. ако може го сложите

**Comment by Warglaive** [comment]
Това е NPC от Patch 3.2.2 (2009-09-22), не е за 3.3.5.

**Comment by FALL1N1** [comment]
Добавено в 3.3.2 и достъпно до 6.х.х

**Comment by AnTOLI** [comment]
На място си е мерси :+1:
