### ISSUE TITLE
Missing Npc Vol'jin

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#219]
Липсва нпц то Vol'jin http://wowhead.project-nemesis.cz/an/?npc=31649#starts пред Undercity, :)

**Comment by Warglaive** [comment]
spawned.

**Comment by AnTOLI** [comment]
Не че нещто но трябва да се премести и да е на раптор боса. Да има 29806 мана и кръв 8608к.
![wowscrnshot_072215_035455](https://cloud.githubusercontent.com/assets/2588705/8815763/4fd2599c-3026-11e5-9558-8fdb215ac2af.jpg)

**Comment by Warglaive** [comment]
Като се прибера, ще го оправя.

**Comment by Warglaive** [comment]
raptor hp/mana не му трябват.
