### ISSUE TITLE
[Quest] Bang a Gong !

### ISSUE THREAD

**Issue by buxliviq** [Warglaive/DragonFireOriginal-3.3.5#22]
Здравейте,аз също завърших тази поредица http://www.wowwiki.com/The_Scepter_of_the_Shifting_Sands_quest_chain.

След куеста Might of Kalimdor,въпросният Bang a Gong !,бива прескочен и ми дава последния  от поредицата Treasure of the Timeless One.След връщането му взех Епик Итем и толкова.

Въпросът ми е нарочно ли не работи или след fixovete се е бъгнал и ще бъде ли пуснат?

**Comment by FALL1N1** [comment]
Копие: #1
