### ISSUE TITLE
Quest: [Nexus-King Salhadaar]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#229]
http://www.wowhead.com/quest=10408
Проблема е, че при активиране на quest item-a(http://www.wowhead.com/item=29618), нищо не се случва.

**Comment by AnTOLI** [comment]
Fix за Нпц то https://github.com/TrinityCore/TrinityCore/commit/7691d477d58be45635c38cfccdd0ec2928ad791a

**Comment by FALL1N1** [comment]
@AnTOLI Ще е активен след рестарт, пиши ако има нещо нередно.

**Comment by AnTOLI** [comment]
Чудно и тоя куест ми го дава че ауто направен и трябва само да предам Куест итема на тоя от които се взима Куеста http://www.wowhead.com/item=29618/protectorate-disruptor.
И на други Куести забелязах това които ги имам в Куест лога.
Не знам ама маи само при мен ми дава така тия Куести.
