### ISSUE TITLE
Achievement: [Save The Day]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#235]
http://www.wowhead.com/achievement=207/save-the-day
Постижението неможе да бъде направено.

**Comment by AnTOLI** [comment]
че бъде ли оправено. ?

**Comment by AnTOLI** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5a4dfbf300bdd27f928e73437eebd71773f30426 fix?

**Comment by AnTOLI** [comment]
Днес го пробвахме и не го даде.

**Comment by FALL1N1** [comment]
#35
