### ISSUE TITLE
Quest:  [Tools of War]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#236]
http://www.wowhead.com/quest=12759
Въпросният Quest дава "Missing header! (quest designers)" и неможе да бъде взет от играч.

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/474

**Comment by FALL1N1** [comment]
test

**Comment by kurevaglava** [comment]
Все още не го дава куеста на играчите.

**Comment by FALL1N1** [comment]
fxied
