### ISSUE TITLE
Quest:  [Fuel for the Fire]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#237]
http://www.wowhead.com/quest=12690/fuel-for-the-fire
Когато Quest Item-a(http://www.wowhead.com/item=39238#objective-of) се активира въху - Bloated Abomination(http://www.wowhead.com/npc=28843/bloated-abomination)
Би трябвало чрез Abomination-a да се убият въпросният брои NPC-та, НО Abomination-а НЕ може да прави нищо(неможе да се движи, да атакува и т.н)

**Comment by denislav92** [comment]
#216

**Comment by AnTOLI** [comment]
Не работи Bloated Abomination.
