### ISSUE TITLE
Quest: Time to Hide

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#238]
http://www.wowhead.com/quest=13275/time-to-hide
При въпросният quest, при опит за влизане в подземието, ни телепортира в Dalaran City и няма как да се стигне до нужните за quest-a NPC-та.

**Comment by FALL1N1** [comment]
Вече няма да портва в даларан, как е?

**Comment by Warglaive** [comment]
Вече не телепортира.
