### ISSUE TITLE
[Quest] On Spirit's Wings (H) id 10714 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#24]
http://www.wowhead.com/quest=10714
Получава се в най-Thunderlord Stronghold в Edge Mountains Блейд.

Quest изисква от вас да се намери Bloodmaul Taskmaster и ангажирани в разговор Bloodmaul гадател и да използвате предоставения стремежа елемента, за да призове бухал име Spirit.

Двете тълпи Натискането със зелената AoE кръг марка не свика бухала, за да завършите куеста.
Видео как се прави. https://www.youtube.com/watch?v=pgrhmK4zeM4

**Comment by Dragonspower** [comment]
Quest-а се изпълнява като се убият трите огрета.
