### ISSUE TITLE
Quest: [The First Trial] Paladin Spell

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#243]
http://www.wowhead.com/quest=9678/the-first-trial
Quest-a се минава, но неможе да се върне ( NPC-то е наред, явно не отчита нещо както трябва, въпреки че дава Complete в Quest Log-a).
NPC на което трябва да се върне - http://www.wowhead.com/npc=17717/knight-lord-bloodvalor

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Работи.
