### ISSUE TITLE
NPC: Novos the Summoner ( BOSS ) ( Drak'Tharon Keep )

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#246]
http://www.wowhead.com/npc=26631/novos-the-summoner
Въпросното NPC( BOSS ) се намира в Drak'Tharon Keep(http://www.wowhead.com/zone=4196), преди него има евент, който служи за сваляне на бариерата около боса, след което се убива боса.

 Проблема е, че евента НЕ тръгва.

**Comment by AnTOLI** [comment]
Все още си е така Боса оправете го.

**Comment by FALL1N1** [comment]
Оправен, пиши ако има нещо.

**Comment by Pavslav** [comment]
Въпросния бос все още няма  script,дори няма auto-attack.

**Comment by FALL1N1** [comment]
Убива ли се, дава ли ачивмънт?

**Comment by Pavslav** [comment]
Боса си е типично dummy за achievement не мога да кажа.
