### ISSUE TITLE
Achievement:  [Crashin' & Thrashin']

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#248]
http://www.wowhead.com/achievement=1295/crashin-thrashin
Постижението НЕ работи, защото робота(http://www.wowhead.com/item=54343/blue-crashin-thrashin-racer-controller)
Няма spell-а който трябва да се използва(http://www.wowhead.com/spell=49444/racer-kill-counter) /
(http://www.wowhead.com/spell=49297/racer-rocket-slam)

**Comment by AnTOLI** [comment]
Поне не го адд на хората постижението като не  го оправите.

**Comment by AnTOLI** [comment]
Маи другата година. ;д

**Comment by AnTOLI** [comment]
Fix https://github.com/TrinityCore/TrinityCore/commit/381285865cdd1fc5904a2f8694dd3a115d1e842f

**Comment by Ritokoko** [comment]
Все още е така.Ако може да се фиксне .

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
http://www.wowhead.com/spell=49297/racer-rocket-slam го има но не атакува другия робот .Дефакто трябва да се Charge вурху него и да го счупи ,но не го прави.

**Comment by Ritokoko** [comment]
Дори след като е настъпил евента пак не работи .Същото е като по горния ми коментар.

**Comment by kurevaglava** [comment]
Ако не може да бъде оправено,то поне hack fix да го вземат хората които гонят ачивмънти.

**Comment by FALL1N1** [comment]
мирнете с тея хакфиксове.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Hackfix е, при активиране на предмета дава постижението и играта errorna при натискане на escape key.
Но виждам, че спела на количката си го има.
