### ISSUE TITLE
Achievement: I've Had Worse

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#249]
http://www.wowhead.com/achievement=3804 Не работи като се направи по постижението не го дава .

**Comment by AnTOLI** [comment]
По добре хак фикс го направи.

**Comment by Ritokoko** [comment]
Аз тествах този ачиевемент на 27.06 и все още не работи.Убихме зомбитата за да не експлодират и след това убихме и боса но не го даде.
