### ISSUE TITLE
 [Quest] [Volatility] #1436 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#25]
Куеста се намира в Icecrown взима се от http://www.wowhead.com/npc=30825.
После се отива се се вземат 3 итема дето са на земята и с тях се сумм един дракон и дракона взима едно Нпц и лети ето видео как става,http://www.youtube.com/watch?v=2u4XA00NhfQ
( Всичко по куеста работи в момента , освен че не отчита credit когато дракона отнесе войника .)

**Comment by Warglaive** [comment]
http://www.wowhead.com/quest=13261/volatility

**Comment by AnTOLI** [comment]
Дано да  стават https://github.com/raczman/TrinityCore/commit/89ad730131bf4bd5f73c450f885cb5272c22e27e

**Comment by FALL1N1** [comment]
Оправен.

**Comment by AnTOLI** [comment]
Пак е така не не отчита credit когато дракона отнесе войник.
