### ISSUE TITLE
Quest -  [Blueleaf Tubers]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#253]
Куест итема Crate With Holes ( http://www.wowhead.com/quest=1221/blueleaf-tubers ), чрез който се призовава ''полската мишка'' не функционира. На мястото на което трябва да бъде активиран изписва, че ''не се намираш на точното място''.
Видео https://www.youtube.com/watch?v=S9lrdq0AeoM
Fix https://github.com/raczman/TrinityCore/commit/f2e5a7bfc3335391f59adacdd511e7107d9a1ee0

**Comment by FALL1N1** [comment]
Оправен, пиши ако има проблеми!

**Comment by AnTOLI** [comment]
Като се изкара мишка нищто не прави седи на едно място само и до там.

**Comment by FALL1N1** [comment]
Авто е, нямам нерви да го пренаписвам.

**Comment by AnTOLI** [comment]
Итемите не могат се вземат за куеста.
