### ISSUE TITLE
Halls of Reflection - instance

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#256]
Проблема в HOR е че липсва кораба на края на инса като минем ескорта на Lich King и не може да се вземе итемите от кобчега на кораба.
Видео https://www.youtube.com/watch?v=RhuDSMD8sIg

**Comment by AnTOLI** [comment]
Че го оправите ли кораба. :)

**Comment by FALL1N1** [comment]
Ще преместя сандъка по-надоло.

**Comment by AnTOLI** [comment]
Премести и портала. :)

**Comment by AnTOLI** [comment]
Кога да очакваме да го преместиш днес направихме ХОР и го няма.

**Comment by AnTOLI** [comment]
Gunship в ХОР https://www.youtube.com/watch?v=RhuDSMD8sIg&hd=1

**Comment by FALL1N1** [comment]
test, трябва да има кораби вече.

**Comment by Warglaive** [comment]
Тествах го, след като се минат 10-те вълни и трябва да се стигне до http://prntscr.com/7q8ska
Където Sylvanas трябва да е sap-нала Lich King-а и след което да почне да се бяга, НО нищо не се случва просто седят.

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/573
