### ISSUE TITLE
Achievement:Don't Look Up

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#257]
http://www.wowhead.com/achievement=4525/dont-look-up#screenshots:id=160635
НЕ работи.

**Comment by AnTOLI** [comment]
Направете го като се убие боса да го даде докато бъде оправен официално. :)

**Comment by FALL1N1** [comment]
Hackfix, когато е убит Тиранус ще го дава.
