### ISSUE TITLE
 Battle at Valhalas: The Return of Sigrid Iceborn - Q - B - ID#13216 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#26]
http://www.wowhead.com/quest=13216 Не работи нпц http://www.wowhead.com/npc=30086#abilities  си седи на драгона и не може да се атакува .

**Comment by Warglaive** [comment]
Цялата поредица РАБОТИ!

**Comment by AnTOLI** [comment]
Мс
