### ISSUE TITLE
Boss Ichoron [Violet Hold]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#262]
http://www.wowhead.com/npc=29313 Боса се бъга и става evaded и не може да се мине инса.

**Comment by FALL1N1** [comment]
Повече инфо, къде как и защо бъгва?

**Comment by AnTOLI** [comment]
Като се бие мобовете които идват  към Bоса всички и много дмг по боса се бъгва... става на 1 Hp

**Comment by Warglaive** [comment]
Самият евент на боса е следния:
Появява се, скрива се и изкарва траш, след като бъде убит траш-а се появява пак и така периодично, явно след като се скрие и появи има шанс да еваде-не.

**Comment by FALL1N1** [comment]
Добавен е фикс, тествайте и репортвайте ако има нещо нередно!
