### ISSUE TITLE
Quest Item  [Banishing Crystal]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#266]
http://www.wowhead.com/item=32696 Не може да се пусне итема при опит да се пусне изписва (the spell is not available to you) без него не може да се мине куста http://www.wowhead.com/quest=11051/banish-more-demons.

**Comment by FALL1N1** [comment]
Оправен!

**Comment by AnTOLI** [comment]
Пак е така показва the spell is not available to you.

**Comment by Warglaive** [comment]
Все още е така.

**Comment by FALL1N1** [comment]
Вече е ок.
