### ISSUE TITLE
NPC: Archmage Pentarus

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#268]
http://www.wowhead.com/npc=28160/archmage-pentarus
Event-а от NPC-то НЕ работи, просто изкарва самолета чрез които трябва да се лети и до там.

**Comment by AnTOLI** [comment]
Дано да става https://github.com/britus/TrinityCore.EoF.Fixes/commit/08c044077da39208d1f15df212097535e6d45f69

**Comment by AnTOLI** [comment]
Fix за Flying Machine https://github.com/TrinityCore/TrinityCore/commit/1aecc27ad8c25bbf755509addf1956fa0a3992d2

**Comment by FALL1N1** [comment]
Оправен, пишете ако има нещо.

**Comment by AnTOLI** [comment]
Пак е така  просто изкарва самолета чрез които трябва да се лети и до там  и портала не се показва.

**Comment by AnTOLI** [comment]
Може да стана с този https://github.com/TrinityCore/TrinityCore/commit/46828c48b041c78ed901605833c1ba6d10f501f5

**Comment by FALL1N1** [comment]
test sled restart

**Comment by AnTOLI** [comment]
Работи.
