### ISSUE TITLE
Quest   [Assault by Air] 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#270]
http://www.wowhead.com/quest=13310 Не работи самолета не може да се позва.
Видео https://www.youtube.com/watch?v=QocqIwmiMpk

**Comment by FALL1N1** [comment]
Оправен.

**Comment by AnTOLI** [comment]
Пак си е така не може да се стартира самолета.
Фикс https://github.com/TrinityCore/TrinityCore/commit/b155ef2d254ddd2b271eab4336a58243ec1b6d68

**Comment by AnTOLI** [comment]
До днес пак си е така.
