### ISSUE TITLE
Pet [Argent Gruntling]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#271]
Пета не работи няма му го другите опци като на видеото https://www.youtube.com/watch?v=7Vectgmyto4

**Comment by JunkyBG** [comment]
http://i.imgur.com/f05CWfu.png 
Ще бъде оправено след рестарт.

**Comment by AnTOLI** [comment]
Кога че бъде рестарта.

**Comment by AnTOLI** [comment]
Няма кои да го сложи още си е така пета. :)

**Comment by AnTOLI** [comment]
Дано. :)

**Comment by AnTOLI** [comment]
Тоя рестарт много време ли в ДФ ли се чака. :)

**Comment by FALL1N1** [comment]
Оправен!

**Comment by AnTOLI** [comment]
Пета пак си е само вендор и до там.

**Comment by FALL1N1** [comment]
Сигурен ли си, че си изпълнил ачивмънтите нужни за другите опции?

**Comment by AnTOLI** [comment]
Всичките ачивмънтите ги имам.

**Comment by FALL1N1** [comment]
Ок, ще го погледна.

**Comment by FALL1N1** [comment]
След рестарта ще е ок.
