### ISSUE TITLE
Quest -   [All Things in Good Time]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#272]
http://www.wowhead.com/quest=13190/all-things-in-good-time Не работи няма го Ahn'kahar Watcher Corpse Burned

**Comment by AnTOLI** [comment]
Fix за куеста https://github.com/TrinityCore/TrinityCore/commit/6b24a8a7a72ebd1379ab1520958a15230544dd6c

**Comment by FALL1N1** [comment]
Активен след рестарт.
