### ISSUE TITLE
The Oculus instance

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#274]
http://www.wowhead.com/zone=4228/the-oculus 
NPC - 
http://wotlk.openwow.com/npc=27657
http://wotlk.openwow.com/npc=27658
http://wotlk.openwow.com/npc=27659 
НЕ дават дракони, както трябва да бъде, също така отчита всички постижения с въпросните дракони:
 http://wotlk.openwow.com/achievement=2046,
 http://wotlk.openwow.com/achievement=2044,
 http://wotlk.openwow.com/achievement=2045

**Comment by Warglaive** [comment]
Мисля, че проблема все още го има.
@AnTOLI редактирал съм ти пост-а за да бъде по-разбираем и за да не си губи времето колегата да  търси ид-та.

**Comment by AnTOLI** [comment]
:+1:
