### ISSUE TITLE
Npc Perry Gatner 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#275]
http://www.wowhead.com/npc=19228/perry-gatner Не работи евента с него.
Видео https://www.youtube.com/watch?v=_m-F58CfcUs.

**Comment by FALL1N1** [comment]
Кодиран и е напълно близлайк!

**Comment by AnTOLI** [comment]
Не работи нещто Нпц  то си седи винаги тама .
