### ISSUE TITLE
[Reign of the Dead] [The Lightning Capacitor]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#276]
http://www.wowhead.com/item=47316/reign-of-the-dead Не ги дава 3 стака от Mote of Flame при spell critical strike и другия пак така 3 Electrical Charges http://www.wowhead.com/item=28785/the-lightning-capacitor.

**Comment by FALL1N1** [comment]
Оправени.

**Comment by AnTOLI** [comment]
Не ги дава стака.

**Comment by Warglaive** [comment]
Работят и двете.
