### ISSUE TITLE
Npc Magister Surdiel Wintergrasp Battle-Mage id 32170

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#278]
Не работи Нпц http://wotlk.openwow.com/npc=32170 не те телепортира на бг WG и не те вкарва в райд група.

**Comment by FALL1N1** [comment]
Оправено.

**Comment by AnTOLI** [comment]
Пак са си така.

**Comment by Warglaive** [comment]
ИД-то не е това което трябва да е.
http://wotlk.openwow.com/npc=32170
Затова казвам да се внимава с тия ид-та и най-добре да се гледат от wotlk.openwow.com

**Comment by AnTOLI** [comment]
На 10 мин  Нпц трябва да отвори портал до Wintergrasp. И говори (Magister Surdiel yells: the horde needs more for Wintergrasp! A portal has been opened at the Sunctuary. in Dalaran).

**Comment by FALL1N1** [comment]
Не са кодирани.

**Comment by AnTOLI** [comment]
Дано да ги оправят.
