### ISSUE TITLE
Npc Scourge Banner-Bearer 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#279]
http://www.wowhead.com/npc=31900/scourge-banner-bearer#drops и на http://www.wowhead.com/npc=34127/boneguard-commander Липсва им  аурата която трябва да си пуска http://www.wowhead.com/spell=60023/scourge-banner-aura

**Comment by FALL1N1** [comment]
За куест ли е?

**Comment by AnTOLI** [comment]
Не просто нямат магята която трява да има в тази зона нпц та.

**Comment by AnTOLI** [comment]
С този буф нпц та в това място така бият повече.

**Comment by FALL1N1** [comment]
Мисля, че вече трябва да са ок.
