### ISSUE TITLE
Npc Converted Hero

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#280]
http://www.wowhead.com/npc=32255/converted-hero#drops Няма му аурата която трябва да си пуска http://www.wowhead.com/spell=60231/grip-of-the-scourge

**Comment by FALL1N1** [comment]
За куест ли е?

**Comment by AnTOLI** [comment]
Не но им липсват буфа в този зона.

**Comment by FALL1N1** [comment]
Какъв е проблема тогава?

**Comment by AnTOLI** [comment]
Да си имат магите :)

**Comment by AnTOLI** [comment]
Фикс https://github.com/TrinityCore/TrinityCore/commit/cb48f454fa9b01e7a0ca0175ed7b948f69ca5ba4
