### ISSUE TITLE
Quest: Precarious Predicament

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#282]
http://www.wowhead.com/quest=4121 Евента не работи за куеста.

**Comment by FALL1N1** [comment]
Вече е авто.

**Comment by AnTOLI** [comment]
Пак си е така не е авто.
Като се вземе куеста трябва да даде Куест итем http://www.wowhead.com/item=11286/thorium-shackles без него не може да се мине куеста.
