### ISSUE TITLE
Quest:The Valiant`s Charge

### ISSUE THREAD

**Issue by Dylarcus** [Warglaive/DragonFireOriginal-3.3.5#283]
http://www.wowhead.com/quest=13718/the-valiants-charge   NPC-а не ми дава quest-а.

**Comment by FALL1N1** [comment]
В Петък като се прибера ще го оправя.

**Comment by Dylarcus** [comment]
Ако искаш пиши тука за някакъв час да съм в сервера защото мисля, че само на мен не го дава но не съм сигуре,но благодаря ако го оправите

**Comment by FALL1N1** [comment]
Куеста работи, трябва да изпълниш първо http://www.wowhead.com/quest=13684/a-valiant-of-stormwind
