### ISSUE TITLE
Achievement  [Many Whelps! Handle It! (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#284]
Не работи на 10 и 25 модем http://www.wowhead.com/achievement=4403/many-whelps-handle-it-10-player. Оправете го 
Видео как се прави https://www.youtube.com/watch?v=9BQ7lnemmWs

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Не работи.

**Comment by AnTOLI** [comment]
Работи. :+1:
