### ISSUE TITLE
Achievement  [Take Out Those Turrets (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#285]
Не работи постижението http://www.wowhead.com/achievement=2909/take-out-those-turrets-10-player.

**Comment by FALL1N1** [comment]
Оправен.

**Comment by AnTOLI** [comment]
Хак фикс ли е направен.?

**Comment by FALL1N1** [comment]
Не, защо?

**Comment by AnTOLI** [comment]
Не го даде.

**Comment by FALL1N1** [comment]
Убихте ли първо къртечницата (turret)?
http://prntscr.com/7e7rj7

**Comment by AnTOLI** [comment]
Не работи спела http://www.wowhead.com/spell=62324/throw-passenger  .....

**Comment by AnTOLI** [comment]
Не работи спела http://www.wowhead.com/spell=62324/throw-passenger#comments

**Comment by FALL1N1** [comment]
Не ми го пиши това тук, ачивмънта работи. Първо трябва да убиете къртечницата му.

**Comment by AnTOLI** [comment]
Kъде са къртечницата (turret)  сега сме тама и не ги пусна?

**Comment by FALL1N1** [comment]
Това отгоре какво е?
