### ISSUE TITLE
Achievement   [Shattered (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#286]
Не работи постижението http://www.wowhead.com/achievement=2925/shattered-10-player

**Comment by FALL1N1** [comment]
Оправен (10/25).

**Comment by AnTOLI** [comment]
Не работи не го дава като ги замразихме 2 нпц та в водата не го даде.

**Comment by FALL1N1** [comment]
#521

**Comment by Ritokoko** [comment]
Траша не е активен за този ачивмент на 10 а на 25 не го дава ачивмента.
