### ISSUE TITLE
Achievement   [Nerf Scrapbots (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#287]
Не работи няма ги нпц та http://www.wowhead.com/npc=33343/xs-013-scrapbot които трябват за постижението http://www.wowhead.com/achievement=2933/nerf-scrapbots-10-player#comments

**Comment by FALL1N1** [comment]
Boss-а пуска магия която призовава тези ботове.

**Comment by Warglaive** [comment]
Мисля, че проблема е че не ги призовава.

**Comment by AnTOLI** [comment]
Да няма ги и не може да се направи постижението.
