### ISSUE TITLE
{Quest} Blinding the Eyes in the Sky

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#288]
http://www.wowhead.com/quest=13313/blinding-the-eyes-in-the-sky За куеста проблема е че не работи Куест итема http://www.wowhead.com/item=44212/sgm-3 с които трябва да се уцелим самолетчетата които обикалят http://www.wowhead.com/npc=32189/skybre.

**Comment by FALL1N1** [comment]
Оправен, пиши ако има нещо.

**Comment by AnTOLI** [comment]
Не умират самолетчетата при удар с куест итема.

**Comment by FALL1N1** [comment]
Сега?

**Comment by AnTOLI** [comment]
Работи. :+1:

**Comment by AnTOLI** [comment]
Работи, :+1:
