### ISSUE TITLE
Achievement: [Hadronox Denied] Class B

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#29]
Линк до постижението - http://www.wowhead.com/achievement=1297
Постижението се изпълнява с босът Hadronox ( http://www.wowhead.com/zone=4277 ) в Azjol-Nerub ( http://www.wowhead.com/zone=4277.
Целта на постижението е да убиете Hadronox ( http://www.wowhead.com/zone=4277 ) на Heroic трудността.Преди да запуши горните врати и спре размножаването на съществата босът трябва да бъде убит.
Проблемът е,че когато боса бъде убит не отчита постижението.

**Comment by AnTOLI** [comment]
Fix за https://github.com/joschiwald/TrinityCore/commit/80b487244ea52345fa0ec853d52955ec33bb39eb

**Comment by AnTOLI** [comment]
Става ли или не.?

**Comment by FALL1N1** [comment]
Не, това е цяло пренаписване на кода. Когато имам време ще го оправя.

**Comment by AnTOLI** [comment]
Ок

**Comment by AnTOLI** [comment]
Работи.
