### ISSUE TITLE
БГ предложение

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#290]
Не може ли да направите БГ та за по малко хора а не на 12 играчи да вика БГ. Например може да WSG да го направите за малко хора поне е лесно БГ и да има кво да правим по цял ден. :)

**Comment by AnTOLI** [comment]
Маи никои няма да ми отговори...

**Comment by Warglaive** [comment]
За момента не е възможно.

**Comment by FALL1N1** [comment]
След ъпдейта ще е направено (ще се съобщи днес)!

Графа ( Battleground - Минимални Играчи )
Random battleground - 10
Alterac Valley - 20
Warsong Gulch - 10
Arathi Basin - 10
Eye of The Storm - 5
Strand of the Ancients - 20 (защото е огромен)
Isle of Conquest - 20 (защото е огромен)

**Comment by AnTOLI** [comment]
Пак си е на всички бг да по 11 играчи за да викне.
Spored mene moje i za po malko hora da se igrae samo vremeteto na bg e problema 5 min deto e ;d
Предлагам графа.
Random battleground - 6
Alterac Valley - 20
Warsong Gulch - 4
Arathi Basin - 8
Eye of The Storm - 5
Strand of the Ancients - 8 (Прави се много бързо това БГ с тия машини)
Isle of Conquest - 20

**Comment by AnTOLI** [comment]
Strand of the Ancient не вика много оправете го.?
