### ISSUE TITLE
Quest:  [Vyletongue Corruption]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#291]
http://www.wowhead.com/quest=7041/vyletongue-corruption Не работи Куеста като се позва куест итема http://www.wowhead.com/item=17696/filled-cerulean-vial не става нищто.

**Comment by AnTOLI** [comment]
Fix https://github.com/TrinityCore/TrinityCore/commit/d2836cfe242d7647e585b469005a16d9e7a9a79a

**Comment by FALL1N1** [comment]
Оправен, пиши ако има нещо!
