### ISSUE TITLE
Npc Crazed Mana-Surge 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#293]
http://www.wowhead.com/npc=26737/crazed-mana-surge не могат да се бият.

**Comment by FALL1N1** [comment]
Дай снимка или кажи какво точно им има.

**Comment by AnTOLI** [comment]
http://www.wowhead.com/npc=26737/crazed-mana-surge#screenshots:id=99567

**Comment by FALL1N1** [comment]
Не такава, от самия сървър ми трябва. Мъртви ли са и скачат на бой или каквото там правят..

**Comment by AnTOLI** [comment]
Не могат да те бият но и аз тях не мога да бия. ;д

**Comment by Warglaive** [comment]
http://prntscr.com/78fwgc 
Не е мъртво NPC-то, но неможе да се удари.

**Comment by FALL1N1** [comment]
Оправени!

**Comment by Warglaive** [comment]
Пак са така.

**Comment by FALL1N1** [comment]
Е вече трябва да е ок.
