### ISSUE TITLE
Quest: [Get Kraken!](Argent tournament daily quest)

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#294]
http://www.wowhead.com/quest=14108/get-kraken Не работи не го отчита за ''Hurl Spears at North Sea Kraken (8)'' като бием с Kуест итема http://www.wowhead.com/item=46954/flaming-spears елита  http://www.wowhead.com/npc=34925/north-sea-kraken.

**Comment by FALL1N1** [comment]
Оправен, пиши ако има нещо.

**Comment by AnTOLI** [comment]
Не работи пак така си е.

**Comment by FALL1N1** [comment]
Оправен.
