### ISSUE TITLE
Achievement  [Hot Pocket (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#295]
http://www.wowhead.com/achievement=2927/hot-pocket-10-player Нужното за завършването на постижението е:
След като боса Ignis the Furnace Master ( http://www.wowhead.com/npc=33118 ) кастне на вас или на човек от групата Slag Pot ( http://www.wowhead.com/spell=62717 ) . Лечителите трябва да се съсредоточат върху човека, пуснат в ''кофата'' на боса и да го хеалват през тези 10 секунди. Ако играчът (в това число можеби и вие) оцелее, след като босът го пусне на земята трябва да отчита постижението.

**Comment by AnTOLI** [comment]
Дано да става. https://github.com/TrinityCore/TrinityCore/commit/21820b425b0b573229f683a2d45b23d8a42c888d

**Comment by FALL1N1** [comment]
Оправен, пиши ако има нещо.

**Comment by AnTOLI** [comment]
Не работи. :(

**Comment by FALL1N1** [comment]
Оправени и 2-та (10/25), отворете отново ако има проблеми.

**Comment by AnTOLI** [comment]
Крашва сървъра от  Slag Pot  като го пусне това маи. :(

**Comment by Warglaive** [comment]
Работи и сървъра НЕ крашва!
