### ISSUE TITLE
Quest:  [The Perfect Dissemblance] 12260

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#297]
Не работи като изпозваме Куест итемаhttp://www.wowhead.com/item=37381/banshees-magic-mirror  на Нпцто http://www.wowhead.com/npc=27202/onslaught-raven-priest не става нищто.
Видео как се прави. https://www.youtube.com/watch?v=gLgjBVbXE8c

**Comment by FALL1N1** [comment]
Направен е автоматичен.

**Comment by AnTOLI** [comment]
Не работи може да пробваш с този фикс. https://github.com/TrinityCore/TrinityCore/commit/77d083eb16758832bf465d460ff6275ba8de8445
