### ISSUE TITLE
Children's Week  [World Event]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#299]
http://www.wowhead.com/event=201/childrens-week
В Northrend куест.
http://www.wowhead.com/quest=13929/the-biggest-tree-ever Не работи куеста като се отиде с пета до Grizzlemaw зоната с пета http://www.wowhead.com/quest=13929/the-biggest-tree-ever#screenshots:id=141982.
В Outland Куест.
http://www.wowhead.com/quest=10945/hchuu-and-the-mushroom-people Като се отиде до нпц то http://www.wowhead.com/npc=22823/hchuu ни с пета нищто не става.
http://www.wowhead.com/quest=10953/vis не го отчита куеста.
В Orgimmar.
Детето не дава куести реснете ги http://www.wowhead.com/item=18597/orcish-orphan-whistle#provided-for.
За Алитата нз как се ако има некои да пише дали са бъгави.
Като цяло ако реснете Куестите на всички че има хора които не им дава Куестите децата.
Ако може да ги FIX те. :)

**Comment by AnTOLI** [comment]
https://github.com/TrinityCore/TrinityCore/blob/41e2b0046dc73ab2adf9c15442d70a7b769013f9/src/server/scripts/Events/childrens_week.cpp#L1023

**Comment by AnTOLI** [comment]
Развитие по евента?

**Comment by AnTOLI** [comment]
Кога че го пуснете пак евента с работещти куестове :)

**Comment by FALL1N1** [comment]
Не обещавам да е скоро, има по-важни неща.

**Comment by AnTOLI** [comment]
Даите по един пет на хората. :)

**Comment by AnTOLI** [comment]
Искам пет за тази година. ;д
