### ISSUE TITLE
[Quest] A Short Fuse

### ISSUE THREAD

**Issue by opalq** [Warglaive/DragonFireOriginal-3.3.5#3]
http://www.wowhead.com/quest=13263

Куестът се взима от Saronite Bomb Stack под ICC. Проблемът е, че след update-a, бездната, в който трябва да се скочи е "затворена" (има лед върху нея и няма как да се падне долу, където продължава куеста). Преди въпросният лед го нямаше и можеше свободно да се падне. 
Явно идеята е бомбите да отворят дупка, но това не става. Този куест е част от дълга поредица, важна за хората, които минават Loremaster

**Comment by Warglaive** [comment]
Трябва да работи.
