### ISSUE TITLE
(Quest) [A Tangled Skein] id 12555

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#30]
Ято е http://www.wowhead.com/quest=12555 взима се от http://www.wowhead.com/npc=28284 в Zul'Drak.
Как трябва да работи:

Използвайте Tangled Thrower бъркотията по същество Plague пръскачка, за да я свали и да я превърне от елитния към нормалното след това да го убие.

**Comment by Dragonspower** [comment]
Самите creature са на ниско и ако застанеш под тях те атакуват, след като ги убиеш ги отчита за questa.
