### ISSUE TITLE
Quest:  [Your Fortune Awaits You...]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#300]
http://www.wowhead.com/quest=7944/your-fortune-awaits-you Няма го сандъка http://www.wowhead.com/object=180055/mysterious-wailing-caverns-chest в инса Wailing Caverns на които трябва да се остави куеста .

**Comment by FALL1N1** [comment]
Darkmoon Faire?

**Comment by AnTOLI** [comment]
Да

**Comment by FALL1N1** [comment]
То целия евънт не е кодиран, ще бъде по-нататък!

**Comment by FALL1N1** [comment]
Както и да е, този е авто!

**Comment by FALL1N1** [comment]
Грешка, оправен е blizzlike.

**Comment by AnTOLI** [comment]
Сандъка ли е сложен.

**Comment by FALL1N1** [comment]
Да и е кодиран куест-евънта.

**Comment by AnTOLI** [comment]
Като го има фестивала ли и сандъка че го има тама.?

**Comment by FALL1N1** [comment]
По принцип и сега трябва да е там, опитай го.

**Comment by AnTOLI** [comment]
Няма го.

**Comment by AnTOLI** [comment]
Търсих го в целия инс и не го намерих.

**Comment by AnTOLI** [comment]
Няма го и до днес.

**Comment by AnTOLI** [comment]
Няма го и до днес не го виждам.
