### ISSUE TITLE
ДФ спира ли?

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#301]
Нямате ГМ или  Developers които да поддържате че спирате ДФ сървъра или поради финанси по сървъра или че няма хора вече тука .?

**Comment by Warglaive** [comment]
Сървъра се прехвърля на нова машина и се събира нов екип, панда реалмите, ще бъдат премахнати, остава само WOTLK 3.3.5.

**Comment by AnTOLI** [comment]
:+1:
