### ISSUE TITLE
Argent Tournament Grounds - Немогат да се вземат всички титли "Champion of", неясен бъг.

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#304]
http://www.wowhead.com/achievement=2771/exalted-champion-of-the-horde
/alliance
Мисля, че трябва да се пренапише отново.
Примерно играч human може да вземе титлата of stormwind, но quest пореди за титла към Darnassus примерно, НЕ му дава.

**Comment by Warglaive** [comment]
За момента е ОК.

**Comment by Warglaive** [comment]
Днес беше извършен тест, проблема стой.

**Comment by Ritokoko** [comment]
За да се вземе http://www.wowhead.com/achievement=2771/exalted-champion-of-the-horde/Alliance трябва да се минат куестовете за Аспирал сеал http://www.wowhead.com/item=45192/aspirants-seal и да се съберат 15 от тях и да се мине куестът http://www.wowhead.com/item=45192/aspirants-seal#objective-of след това трябва да минете http://www.wowhead.com/search?q=The+Aspirant%27s+Challenge и да ви даде куест http://www.wowhead.com/item=44987/valiants-seal#objective-of за съответната раса която сте.След като го минете този куест трябва да ви предостави куестове за останалите столици от вашата раса дали било хорд или алианс.Но не работи за момента може да се вземе само за вашата столица а за останалите не предоставя куестовете за да ги направите и тях.

**Comment by Warglaive** [comment]
High Prio - Титли/Постижения/Петове и т.н
