### ISSUE TITLE
Quest: Steady as a Rock?

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#310]
Quest-а е Auto, въпреки че става въпрос за 2 итема които трябва да се лоотнат.
http://www.wowhead.com/quest=12014/steady-as-a-rock

Проблема е, че неможеха да се лоотнат и беше направен ауто, ако може да бъде фикснат и да се премахне от графата с Autocomplete questове.

**Comment by FALL1N1** [comment]
Оправен.
