### ISSUE TITLE
Pet  [Tiny Emerald Whelpling]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#313]
Този пет http://www.wowhead.com/item=8498/emerald-whelpling  няма drop дроп от дракона http://www.wowhead.com/npc=740/adolescent-whelp.
"Patch 3.1.
In Patch 3.1, the aforementioned Adolescent Whelps will now drop the pet."

**Comment by Warglaive** [comment]
Има дроп, просто е минимален( http://wotlk.openwow.com/item=8498 )

**Comment by FALL1N1** [comment]
Има, 0.10% е в БД.

**Comment by AnTOLI** [comment]
И от 2 та ли са 0.10% дроп да падне пета.

**Comment by Warglaive** [comment]
Да
