### ISSUE TITLE
Bloodsail Admiral Title проблем.

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#315]
Трябва да сваля реп-а с Booty Bat, Gatgetzan и останалите гоблински градове, НО вместо това вдига репутацията заедно с Bloodsail Buccaneers, а трябва при убиването на гоблините да сваля реп-а с всички гоблински градове и да вдига с Bloodsail Buccaneers.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
http://prntscr.com/7j8oy6
По същият начин е в момента.

**Comment by FALL1N1** [comment]
#447
