### ISSUE TITLE
The Culling of Stratholme

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#318]
В началото на инса Arthas си говори сам ( Jaina и Uther не издават звук)

Понякога пропуска първите 2 бос-а.( понякога си е ОК и си се бият)

Arthas НЕ бие:
infinite hunter - http://www.wowhead.com/npc=27743/infinite-hunter#drops
infinite Agent - http://www.wowhead.com/npc=27744/infinite-agent
infinite Adersary - http://www.wowhead.com/npc=27742/infinite-adversary

Най-добре да се направят, да могат да се бият от играчи.

Възможно е Arthas да изчезне ако играчите се отделечат ое него.

'Good work with the crates! Come talk to me in front of Stratholme for your next assignment!'
Текста на Chromie като се направи 5/5 кутите да го изпишe.
https://github.com/SkyFireArchives/SkyFireEMU_406a/blob/master/sql/old/3.3.5a/2011_04_30_02_world_instance_culling_of_stratholme.sql

**Comment by AnTOLI** [comment]
Като се бие зомби не показва вътре в Аchievement колко си убил 0/100 си седи.
- Това НЕ е от значение, постижението работи, проблема е че има само 70 зомбита.

**Comment by AnTOLI** [comment]
'Good work with the crates! Come talk to me in front of Stratholme for your next assignment!'
Текста на Chromie като се направи 5/5 кутите да го изпишe.
https://github.com/SkyFireArchives/SkyFireEMU_406a/blob/master/sql/old/3.3.5a/2011_04_30_02_world_instance_culling_of_stratholme.sql

**Comment by AnTOLI** [comment]
Липсва Нпц то в инса http://www.wowhead.com/npc=27731/acolyte
