### ISSUE TITLE
Wintergrasp Bg

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#319]
1. Не може да се позва наземни моултове по време на битка в бг .
2. Машините не ги пуска където трябва и не може да се изкарат от тама където ги пуска.

**Comment by FALL1N1** [comment]
Опитай след 1 ден (рестарт-а).

**Comment by Warglaive** [comment]
Още го има проблема с машините, пуска ги 2 ярда в страни и неможе да се изкарат от сградата.

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/340

**Comment by akoyo** [comment]
единственото возило което може да се изкара е катапулта

**Comment by Warglaive** [comment]
Оправено.
