### ISSUE TITLE
Quest-Dragonmaw Race: The Ballad of Oldie McOld-Class B 11064

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#32]
http://www.wowhead.com/quest=11064
Трябва да се последва въпросното НПЦ (http://www.wowhead.com/npc=23340) на летящ маунт.След,което НПЦ-то трябва да бъде убито,което е и цел на куеста.

Проблемът е в това,че евента не тръгва и НПЦ-то е Friendly.Може да се направи неутрал и да може да се бие.

**Comment by FALL1N1** [comment]
Авто.
