### ISSUE TITLE
Npcta cast spell

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#321]
Липсват на доста Нпц та магите сега само те бият на атак само без маги и тнт.
Дано да ви помогне това https://github.com/TrinityCore/TrinityCore/blob/98f98fa17fde4a1294b3e9227973ce5df70fbd6b/sql/old/3.3.5a/TDB54_to_TDB55_updates/world/2014_07_14_01_world_misc.sql

**Comment by FALL1N1** [comment]
Добавено, трябва feedback.
