### ISSUE TITLE
Npc Queen Angerboda

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#322]
Липсвам му на нпц то звук и текста които казва като се бие и на 3.3.5 би трябва да работи така. https://github.com/TrinityCore/TDB_4.3.4_No_Longer_Used/blob/master/old/updates_07/033_2014_09_18_01_world_misc.sql

**Comment by FALL1N1** [comment]
Добавен.

**Comment by AnTOLI** [comment]
Липсва към нея и Боса King Ymiron http://www.wowhead.com/npc=29393/king-ymiron и http://www.wowhead.com/npc=24014/necrolord които държат боса King Ymiron,
