### ISSUE TITLE
Mising Quest

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#323]
От Нпц то http://www.wowhead.com/npc=32430 като се мине Куеста http://www.wowhead.com/quest=13374/amped-for-revolt другите 2 куеста не ти ги дава http://www.wowhead.com/quest=13406/riding-the-wavelength-the-bombardment
http://www.wowhead.com/quest=13376/total-ohmage-the-valley-of-lost-hope

**Comment by FALL1N1** [comment]
Оправени.
