### ISSUE TITLE
Doomguard pet [Warlock]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#324]
Няма го в Spellbook Doomguard peta http://www.wowhead.com/spell=18540/summon-doomguard на Lock.

**Comment by FALL1N1** [comment]
Добавен е по трейнърите.

**Comment by AnTOLI** [comment]
Не ми го дава.

**Comment by AnTOLI** [comment]
До момента липсва.!

**Comment by AnTOLI** [comment]
Няма го Doomguard peta по треинърите не ми го дава.

**Comment by FALL1N1** [comment]
test

**Comment by FALL1N1** [comment]
По трейнърите е, отвори тикет защото има проблем точно с твоя герой, някой да ти го доабави.

**Comment by Warglaive** [comment]
Оправен!

**Comment by AnTOLI** [comment]
Ми само при мен може  е тоя проблем с пета.
Опитах да мина http://www.wowhead.com/quest=7583/suppression но не става.
