### ISSUE TITLE
Npc ta ''Ymirheim Chosen Warrior'' text sound mising

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#325]
Липсват им текста и говора на тия Нпц та http://www.wowhead.com/npc=31258/ymirheim-chosen-warrior.
https://github.com/TrinityCore/TrinityCore/blob/98ca9a77491196ef501093572867236712d74938/sql/old/4.3.4/TDB6_to_TDB7_updates/world/014_2014_08_16_00_world_misc.sql

**Comment by FALL1N1** [comment]
Добавени.

**Comment by AnTOLI** [comment]
На тези нпц та нямат тексти и говора.
Icecrown
http://www.wowhead.com/npc=31258/ymirheim-chosen-warrior
http://www.wowhead.com/npc=31267/ymirjar-element-shaper
Howling Fjord
http://www.wowhead.com/npc=23991/gjalerbron-warrior
http://www.wowhead.com/npc=23989/gjalerbron-sleep-watcher#comments
http://www.wowhead.com/npc=23990/gjalerbron-rune-caster

**Comment by FALL1N1** [comment]
Нова тема.
