### ISSUE TITLE
[Spell] Dreadsteed - Flame visual

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#326]
http://www.wowhead.com/spell=23161/dreadsteed Липсва огъня които прави коня на лока.
Снимка http://www.wowhead.com/spell=23161/dreadsteed#screenshots:id=4449
Фикса https://github.com/TrinityCore/TrinityCore/commit/efd37417530296b29f1417fde5f3a11144d4a97e

**Comment by FALL1N1** [comment]
Добавен.
