### ISSUE TITLE
[item] Argent Pony Bridle, Argent Squire, Argent Gruntling

### ISSUE THREAD

**Issue by GalaxyWoW** [Warglaive/DragonFireOriginal-3.3.5#327]
http://www.wowhead.com/spell=62609/argent-squire когато се използва трябва да се появят следните опции

*Bank
*Trader (vendor)
*Mailbox

NPC то използва само флага за Trader(vendor), другите липсват, в допълнение item [Argent Pony Bridle], трябва да предостави маунт към този компанион.

http://www.wowhead.com/item=44998/argent-squire
http://www.wowhead.com/item=45022/argent-gruntling
http://www.wowhead.com/item=47541/argent-pony-bridle

https://github.com/TrinityCore/TrinityCore/commit/64bed16a5761ee98da5386575ae39f237a8721d3 - може би е решението !

**Comment by FALL1N1** [comment]
Трябва да имаш определени постижения за тях, кодирал съм го!

**Comment by GalaxyWoW** [comment]
проблемът вече е оправен, Благодаря !

**Comment by GalaxyWoW** [comment]
само да попитам https://github.com/TrinityCore/TrinityCore/commit/64bed16a5761ee98da5386575ae39f237a8721d3 тоя ли го използва ?

**Comment by FALL1N1** [comment]
@GalaxyWoW 
Не, написах изцялно нов C++ скрипт с проверките за ач-ове, няма го никъде.

**Comment by GalaxyWoW** [comment]
е тука вече не мога да те настигна :D , благодаря за усилията
