### ISSUE TITLE
Quest: The Battle For The Undercity Chain Quest Липсва

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#328]
След като минем куест [Return To Angrathar] http://www.wowhead.com/quest=12500/return-to-angrathar#comments трябва да се смени зонта и да се покажат два дракона за Куести от http://www.wowhead.com/npc=31333/alexstrasza-the-life-binder и http://www.wowhead.com/npc=31334/korialstrasz които дават 4 куеста.
1. http://www.wowhead.com/quest=13242 се вземем Куест итем които е на земята до нея http://www.wowhead.com/item=43615 и да го дадем наhttp://www.wowhead.com/npc=25256/high-overlord-saurfang в Warsong Hold.
(След взимането да другия куест трбва да отвори портал до Orgrimmar)
2.http://www.wowhead.com/quest=13257/herald-of-war Да се закара при  в Orgrimmar или при Garrosh Hellscream в Warsong Hold.
(След даване да този и взимане да другия куест трябва да излезе портал до Undercity пред града).
3.http://www.wowhead.com/quest=13266/a-life-without-regret трябва да намерим Vol'jin пред Undercity след това идва Thrall и почва битка в Undercity.
4.Взима се от Vol'jin  http://www.wowhead.com/quest=13267/the-battle-for-the-undercity Дава се после куеста на Thrall и си взимаш итеми. :)
Видео https://www.youtube.com/watch?v=flPCbRZAaQI

**Comment by opalq** [comment]
Ако не се лъжа, това е timed event някъде от началото на Wotlk, който е нормално на 3.3.5 да го няма (тъй като вече е минал и си ги има Kor'kron guards в UC в резултат на even- та и тн.)

**Comment by AnTOLI** [comment]
Тука евента дали  е работил това и ако искат го оправят и тука, (Сега си го бях минал в един сървър и си работи добре). Даже си го пуснах и видеото :) https://www.youtube.com/watch?v=hyh1AiVeUOI

**Comment by FALL1N1** [comment]
Би трябвало да са призовани вече, отвори темата на ново и пиши ако има нещо.

**Comment by AnTOLI** [comment]
Зоната тама не се е променила.
Не че има значение но Alexstrasza the Life Binder  http://www.wowhead.com/npc=31333/alexstrasza-the-life-binder трябва да е дракон. :)

**Comment by FALL1N1** [comment]
Ще го погледна.

**Comment by AnTOLI** [comment]
Няма го буф като си в тази зона http://www.wowhead.com/spell=60778/serenity.
Текста на драгона като си до тях.

Korialstrasz says: My Queen, do they know?
Alexstrasza the Life-Binder says: No, my beloved.
Alexstrasza the Life-Binder says: [Draconic Ashj zila gul kirasath lok ante il lok buras danashj Gul gul
Korialstrasz nods.
Korialstrasz says: They will not.
Alexstrasza whispers: Come to me, <name> (И името да играча)

**Comment by AnTOLI** [comment]
Драконите само сложи в тази фаза че след буф в този зона  не се виждат.
