### ISSUE TITLE
[Spell] Rogue Poison Duration

### ISSUE THREAD

**Issue by GalaxyWoW** [Warglaive/DragonFireOriginal-3.3.5#329]
http://wotlk.openwow.com/item=43231
http://wotlk.openwow.com/item=43233
http://wotlk.openwow.com/item=43237
http://wotlk.openwow.com/item=5237
http://wotlk.openwow.com/item=43235
http://wotlk.openwow.com/item=3775

всичките имат 24h duration, вместо 1h.

**Comment by Warglaive** [comment]
Да, направено е нарочно, не мисля че е проблем.

**Comment by GalaxyWoW** [comment]
ок
