### ISSUE TITLE
Quest - Trial of the Naaru: Mercy #10884

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#33]
Trial of the Naaru: Mercy - http://www.wowhead.com/quest=10884 - Като се отиде в The Shattered Halls - http://www.wowhead.com/zone=3714 на heroic трябва да има моб - Shattered Hand Executioner - http://www.wowhead.com/npc=17301 , който да се убие и да дропне Unused Axe of the Executioner - http://www.wowhead.com/item=31716 , само че този моб в момента го няма.

**Comment by Dragonspower** [comment]
Npc-то е добавено на оказаното място и шансът на падане на quest итема е 15%.
