### ISSUE TITLE
Profession Specializations

### ISSUE THREAD

**Issue by GalaxyWoW** [Warglaive/DragonFireOriginal-3.3.5#331]
линкове относно проблема

https://github.com/TrinityCore/TrinityCore/issues/226
https://github.com/TrinityCore/TrinityCore/issues/7857

**Comment by Warglaive** [comment]
Проблема го има при герой Hellygun

**Comment by FALL1N1** [comment]
Какъв точно е проблема?

**Comment by Warglaive** [comment]
Има 3та професия ( Transmutation Master ) която немога да я махна, .unlearn - Не става, след релогване се появява.

**Comment by GalaxyWoW** [comment]
проблема е, че самия спелл ( Transmutation Master ) е куест ревард, а спелове които са куест ревард се рекастват при всяко логване, колкото и да го унлеарн при всяко релогване то пак ще се появи единствения начин е самия куест да се изтрие от character_queststatus_rewarded все едно не го е минал и след това да се .unlearn от GM

``` javascript
DELETE FROM `character_queststatus_rewarded` WHERE `guid`=??? AND `quest`=10899;
```

само да се добави guid а на героя вместо ???

**Comment by FALL1N1** [comment]
test

**Comment by GalaxyWoW** [comment]
трябва да го unlearn gm ако си импортнал

**Comment by GalaxyWoW** [comment]
трябва да логнеш да го .unlearn

**Comment by GalaxyWoW** [comment]
Проблема е решен
