### ISSUE TITLE
Argent Tournament event 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#335]
Липсва евента с разговор с  Król Varian Wrynn i Lady Jaina Proudmoore алита и хорда  Thrall i Lord Hellscream на Lord Tirion Fordring в Argent Tournament.
Фикс https://github.com/TrinityCore/TDB_4.3.4_No_Longer_Used/blob/master/old/updates_07/018_2014_08_30_03_world_sai.sql
Видео https://www.youtube.com/watch?v=nz7LtWCdESY

**Comment by FALL1N1** [comment]
Вкаран.

**Comment by AnTOLI** [comment]
:+1:
