### ISSUE TITLE
Quest:  [Among the Champions]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#337]
http://wotlk.openwow.com/quest=13793
Quest-a работи, просто трябва да се махне от графата с autocomplete quests.

**Comment by AnTOLI** [comment]
И хорде не може да се бием натиска се опцията (I am ready to fight!) и до там.

**Comment by AnTOLI** [comment]
Пак трябва да се сложи фикса пак  нито с хорде не може да правим дуели сега https://github.com/TrinityCore/TrinityCore/commit/505e8357d517d7757229691b1b14c64249f69509.

**Comment by FALL1N1** [comment]
След рестарта го пробвайте.

**Comment by Ritokoko** [comment]
Лично на мен ми е все още Ауто.За другите нямам на идея как им е .

**Comment by AnTOLI** [comment]
Работи може да се бием с Хорде. Но Алита  не може пак да се бием. :(

**Comment by AnTOLI** [comment]
Работи  много добре може да се бием с всички вече :)
Но им няма текста преди да се бием с тях. 
Argent Champions texts тука може да го видите.  https://github.com/TrinityCore/TrinityCore/commit/505e8357d517d7757229691b1b14c64249f69509

**Comment by Warglaive** [comment]
Нов репорт за текстовете моля.

**Comment by FALL1N1** [comment]
това е SQL, аз съм го писал директно в ядрото на C++
ще ги добавя като имам свободно време
