### ISSUE TITLE
Npc Onslaught Footman  text

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#343]
http://www.wowhead.com/npc=27203/onslaught-footman Нямат текст тези Нпц та.
https://github.com/TrinityCore/TDB_4.3.4_No_Longer_Used/blob/master/old/updates_06/014_2014_08_15_02_world_misc.sql

**Comment by FALL1N1** [comment]
Добавен.

**Comment by AnTOLI** [comment]
Пак са си така Нпц та няма текста.
