### ISSUE TITLE
2 Bugged Quests

### ISSUE THREAD

**Issue by smackdwn** [Warglaive/DragonFireOriginal-3.3.5#345]
"Riding the red rocket" - Не може да се качи върху ракетата с която се изпълнява самия куест

"Betrayal" - Това е последния куест за ачивмента " Guru of Drakuru " и единствения който не работи. Дефакто има определен евент който се стартира като говориш с НПС-то Overlord Drakuru , но той не се стартира

**Comment by AnTOLI** [comment]
Script за Betrayal https://github.com/TrinityCore/TrinityCore/commit/dd985a8c2635d31b66b12624dfbafe59673d4fdd

**Comment by FALL1N1** [comment]
Betrayal е оправен.
Riding the Red Rocket - хакфикс (може да биете мобовете без ракетата)
