### ISSUE TITLE
Archievements- [Save The Day] battetthle ground WSG bugget

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#35]
Просто като направиш това което пише на арч то него отчита че работи

**Comment by FALL1N1** [comment]
Още ли е така?

**Comment by AnTOLI** [comment]
Да не го дава. :(

**Comment by AnTOLI** [comment]
Fix https://github.com/TrinityCore/TrinityCore/commit/79cd2f9bb9e4cc214150ec36a85817bafad814d6

**Comment by AnTOLI** [comment]
Развитие има ли по постижението.

**Comment by kurevaglava** [comment]
Все още не работи,ще може ли да бъде фикснат.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи си.
