### ISSUE TITLE
Quest:  [Killing Two Scourge With One Skeleton]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#355]
http://wotlk.openwow.com/quest=13144
След като изкарам Burning Skeleton, не намирам Chained Abominations, мисля че липсват, също така Skeleton-а си бие най-близкия таргет.

**Comment by AnTOLI** [comment]
Fix https://github.com/TrinityCore/TrinityCore/commit/5f033694dac42b910a5edd5c77037762105da2a5 https://github.com/raczman/TrinityCore/commit/90fa31bb21b9868729944eb44fc96e61dfcb6a4e
