### ISSUE TITLE
Quest: [Mystery of the Infinite, Redux]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#356]
http://wotlk.openwow.com/quest=13343
След поставянето на http://wotlk.openwow.com/item=44450 , нищо не се случва.

**Comment by AnTOLI** [comment]
FIX https://github.com/TrinityCore/TrinityCore/commit/ba6f0d064a9ea712979c03baa9c2861a113d2e92
