### ISSUE TITLE
Npc Mising Icecrown

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#361]
Липсват тия Нпц та  в Icecrown.
Нa Alliance.
http://www.wowhead.com/npc=32444/kibli-killohertz
http://www.wowhead.com/npc=32523/johnny-yes
http://www.wowhead.com/npc=32524/willy-maybe
http://www.wowhead.com/npc=31648/karen-no
http://www.wowhead.com/npc=32526/alliance-infra-green-engineer
На Хорде.
http://www.wowhead.com/npc=32529/horde-infra-green-engineer
http://www.wowhead.com/npc=32528/horde-infra-green-bomber-parked
http://www.wowhead.com/npc=31839/rizzy-ratchwiggle

**Comment by Warglaive** [comment]
Spawn са.
