### ISSUE TITLE
Quest:  [The Heart of the Mountain]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#362]
http://www.wowhead.com/quest=27596/the-heart-of-the-mountain Не работи не може да се отвори http://www.wowhead.com/object=160845/dark-coffer.
Фикс https://github.com/TrinityCore/TrinityCore/commit/d2224dcd7adca251c17d61125cdbeae6af84399c

**Comment by FALL1N1** [comment]
fixed
