### ISSUE TITLE
Quest:  [Redemption] [Spell] 

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#364]
http://wotlk.openwow.com/quest=9600
Проблема е, че при използването на предмета върху NPC-то всичко е ОК, НО не отчита деиствието и няма как да се мине quest-а и да се вземе паладинския спел
http://wotlk.openwow.com/spell=7329

**Comment by FALL1N1** [comment]
fixed
