### ISSUE TITLE
Uldaman

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#368]
На последния босс  в инса Uldaman http://www.wowhead.com/zone=1337/uldaman не може да се стартира  евента за да се бие  боса Archaedas http://www.wowhead.com/npc=2748/archaedas.

**Comment by Warglaive** [comment]
Все още е така.

**Comment by Ritokoko** [comment]
Няма промяна и до този момент все още не може да се стартира евента .

**Comment by FALL1N1** [comment]
фиьед

**Comment by FALL1N1** [comment]
fixed*
