### ISSUE TITLE
 [To the Looter Go the Spoils] ach Battleground AV bugget

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#37]
Няма дроп итема в бгто

**Comment by AnTOLI** [comment]
http://www.wowhead.com/achievement=1166/to-the-looter-go-the-spoils
Би било добре, ако се добави ръчно на някое NPC с по - висок шанс за drop или нещо друго да се измисли, иначе в момента е невъзможно да се направи.
Коментари от wowhead:
Got it after some 500+ kills in AV. Just remember to loot every player kill and you should be able to get it fairly quick.

**Comment by FALL1N1** [comment]
За момента цялата система за looting в батълграундите не работи, фикс не ви обещавам скоро.

**Comment by AnTOLI** [comment]
Нещто ако само този ни остава  да минем може ли да не се адне или да се измисли нещто. :)

**Comment by AnTOLI** [comment]
Адд итема в мини боса да пада. :)

**Comment by FALL1N1** [comment]
Един айтъм няма да го оправи.

**Comment by AnTOLI** [comment]
Achievement ли не го дава като се вземе итема.

**Comment by AnTOLI** [comment]
-- alliance loot
DELETE FROM `creature_loot_template` WHERE `entry`=1;
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `mincountOrRef`, `maxcount`) VALUES
(1, 17306, 50, 2, 5),
(1, 17326, 30, 1, 1),
(1, 17327, 20, 1, 1),
(1, 17328, 10, 1, 1),
(1, 17422, 85, 15, 22),
(1, 18228, 1, 1, 1);

-- horde loot
DELETE FROM `creature_loot_template` WHERE `entry`=0;
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `mincountOrRef`, `maxcount`) VALUES
(0, 17423, 50, 2, 5),
(0, 17502, 30, 1, 1),
(0, 17503, 20, 1, 1),
(0, 17504, 10, 1, 1),
(0, 17422, 85, 15, 22),
(0, 18228, 1, 1, 1);

**Comment by AnTOLI** [comment]
Дано да става.
-- alliance loot
DELETE FROM `creature_loot_template` WHERE `entry`=1;
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `mincountOrRef`, `maxcount`) VALUES
(1, 17306, 50, 2, 5),
(1, 17326, 30, 1, 1),
(1, 17327, 20, 1, 1),
(1, 17328, 10, 1, 1),
(1, 17422, 85, 15, 22),
(1, 18228, 1, 1, 1);

-- horde loot
DELETE FROM `creature_loot_template` WHERE `entry`=0;
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `mincountOrRef`, `maxcount`) VALUES
(0, 17423, 50, 2, 5),
(0, 17502, 30, 1, 1),
(0, 17503, 20, 1, 1),
(0, 17504, 10, 1, 1),
(0, 17422, 85, 15, 22),
(0, 18228, 1, 1, 1);

**Comment by FALL1N1** [comment]
JunkyBulgaria commented on Jun 6
Един айтъм няма да го оправи.

 JunkyBulgaria commented on May 26
За момента цялата система за looting в батълграундите не работи, фикс не ви обещавам скоро.

**Comment by FALL1N1** [comment]
test
