### ISSUE TITLE
Критичен проблем с ключови механизми!

### ISSUE THREAD

**Issue by TheWhiteShadow** [Warglaive/DragonFireOriginal-3.3.5#372]
Абсолютно всички ключови или "open" механизми от сорта на:  врати, клетки, сейфове, картини и т.н. са повредени. Те остават отворени или използвани за не по-малко от секунда,  след което пак се затварят или остават в неутрална позиция все едно не са докосвани. Оправянето на проблема е от голяма важност, защото коренно променя някои места в играта. Примерно: 
В Scholomance, една от вратите след първите босове иска ключ за да се отвори, след вземането на ключа и  използването му върху вратата  се консумира и не може повече да се отвори вратата, нито пък да се вземе ключа, тъй като боса, от който е взета, е убит и трябва да се ресетне инстанцията и наново да се стигне до същото място,  а вратата мигновено се затваря  за по-малко от секунда, а в този период от време няма как да преминат през нея 5 човека (примерно). Моля отзовете се. Благодаря предварително.

**Comment by FALL1N1** [comment]
Не мога да си го обясна, някой да тества.

**Comment by Warglaive** [comment]
Можеш ли да дадеш пример?

**Comment by TheWhiteShadow** [comment]
Примерно, отварям сейф във банката в Blackrock Depths с ключ, който пада от NPC-та  от инса. В момента, в който свърши cast-а на отварянето, сейфа се затваре мигновено. Това беше само пример, иначе става абсолютно с всички механизми, като: врати, клетки, сейфове, контейнери, и т.н.

**Comment by FALL1N1** [comment]
Ясно, ще е ок спед рестарта.

**Comment by Judgemenday** [comment]
Описаният проблем все още е налице.

**Comment by FALL1N1** [comment]
test
