### ISSUE TITLE
Black Temple [Raid 70lvl]

### ISSUE THREAD

**Issue by Satanique** [Warglaive/DragonFireOriginal-3.3.5#377]
Reliquary of Souls не работи изобщо , смисъл нито се пуска евента нито може да се бие
от там не работи и Акама (като бос понеже не може се мине през вратата която странно е прозрачна или невидима)
Илидан влиза във фаза ,но не излиза от нея което означава ,че не може да се бие/ убие и прочие. Огънят който пуска не може да се избегне също и колкото и да бягаш ударите от него се сипят като по чудо.

**Comment by FALL1N1** [comment]
Направих няколко промени, тест.

**Comment by AnTOLI** [comment]
Има врата пред Акама  и евента не може да се пусне.

**Comment by FALL1N1** [comment]
Няма нищо общо с Akama. Reliquary of Souls

**Comment by Warglaive** [comment]
В момента евент на акама НЕ можа да се пусне и има нещо като врата през кеото неможе да се може.

**Comment by FALL1N1** [comment]
ТОВА НЕ Е ЗА АКАМА, СЛЯПИ ЛИ СТЕ? Reliquary of Souls

**Comment by AnTOLI** [comment]
Ок де ама и Reliquary of Souls като бях не работих отиваме до там и нещо.

**Comment by FALL1N1** [comment]
test

**Comment by Chillie** [comment]
Така проблема със стената го няма,диалог с Akama в началото не може да се осъществи http://prntscr.com/7rgl9o боса може да се бие,но след това има мобове без таргет ,които те бият,но ти тях не можеш http://prntscr.com/7rglm9 . Проблема с Reliquary of Souls си седи. С Illidan Stormrage всичко е наред като изключим ,че дава грешка,ако се налива накрая,трябва да се бие много бавно.

**Comment by FALL1N1** [comment]
fixed - 2
