### ISSUE TITLE
[Achievement]  [Friend or Fowl?]

### ISSUE THREAD

**Issue by GalaxyWoW** [Warglaive/DragonFireOriginal-3.3.5#379]
http://www.wowhead.com/achievement=1254/friend-or-fowl

не ги отчита пуйките и самия таймер не тръгва

**Comment by FALL1N1** [comment]
Проверете сега как е.

**Comment by GalaxyWoW** [comment]
проблемът си остава същия

**Comment by FALL1N1** [comment]
Когато го направите (убиете 15 пуйки) релогнете и проверете дали го имате.

**Comment by GalaxyWoW** [comment]
не е комплиитнат и след релога, все още не работи

**Comment by FALL1N1** [comment]
test

**Comment by FALL1N1** [comment]
@Warglaive @Ritokoko

**Comment by Warglaive** [comment]
Убиваш 15, релогваш - получаваш постижението и 15 пуики се spawn-ват при теб и те атакуват.
