### ISSUE TITLE
Неработещ куест за роугове ( Darkmantle set или още познат като D2 set , Dungeon set 2 и  quest set и прочие)

### ISSUE THREAD

**Issue by crimsonrage** [Warglaive/DragonFireOriginal-3.3.5#38]
http://www.wowwiki.com/Quest:Mea_Culpa,_Lord_Valthalak  [Mea Culpa, Lord Valthalak] <- това е куеста, проблема е очеваден само ще допълня че още преди време ми изчезна и айтъм - що помоля ако може да ми се върне (имам доказателство за съществуването му айтъма е левъл 56 ако не се лъжа)
Така , нека се представя- Crimsonrage съм ингейм и съм туинк 59 левел  блууд елф роуг.. Минавам много интерестна и легендарна поредица от куестове и  стигнах до този както казах по- горе който е към края на куест- чейновете за така слабо популярния сет...
Нека ви запозная и с Валталак -> неутрално НПС , което просто стои там безцелно... и не ви върши никаква работа освен да можете да върнете куеста който сте взели ,но така и жално мъчите да минете... нито може да използвате куест айтъма - нито да го убиете - абе нищо...
Минавам към точка 2 - изчезналият ми айтъм е накитник ( или още известен като брейзър)  който отива в съответния слот.
Един ден още когато бяха стария екип който не обръщаше внимание на нищо бях помолил да ми се върне нали... но- уви ...
та сега моля за 2ри или 3ти път да ми се върне айтъма (http://www.wowwiki.com/Darkmantle_Bracers) доказателството за съществуването му минало време в чантите ми ще е само факта ,че той е 1вия айтъм който се взема от поредицата от куестове (на 1вия още) а аз съм в момента на 26-тия - така че редно е да е бил в мен все някога нали ? логично е :D ... и е логично също така и да ми се върне айтъма ако е възможно , та в свое оправдание ще кажа ,че вендори с този герой НЕ посещавам и НЕ захвърлям айтъми. Така ,че вероятност да съм продал айтъм който нося или да съм го хвърлил- НЯМА. Просто е станало нещо.. нямам идея какво...
Искам да отправя големи благодарности също така на екипа за добре свършената работа до сега и изобщо се надявам всичко да е все така гладко и да има съдействие както до сега.
Благодарности за отделеното време :)
-Crimsonrage 59 lvl twink rogue blood elf (Horde) - Realm: Dragonfire-bg (Wotlk build:3.3.5) server:Dragonfire-bg.net

**Comment by Warglaive** [comment]
http://www.wowhead.com/quest=8995

**Comment by FALL1N1** [comment]
Ако още го искаш пиши тук.
