### ISSUE TITLE
The Violet Hold - Cyanigosa

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#381]
При появяването на Cyanigosa,преди да се превърне в дракон,трябва да се вижда Arcane Power-a около нея - http://www.wowhead.com/npc=31134/cyanigosa#screenshots:id=133512
Също така в момента не се вижда Staff-a който тя държи.
При появяването на Cyanigosa трябва да казва - A valiant defense, but this city must be razed. I will fulfill Malygos's wishes myself! А не да казва същото като започнем битката. - We finish this now, champions of Kirin Tor!

**Comment by FALL1N1** [comment]
Безсмислено.
