### ISSUE TITLE
Thrallmar - Reputation Fail

### ISSUE THREAD

**Issue by Min4AKK** [Warglaive/DragonFireOriginal-3.3.5#382]
Вчера реших да си вдигна репутацията на Thrallmar и да стане Exalted,понеже бях на Revered на половина,но установих,че мобовете от дингеоните на Хелфайър Ситадел не дават репутация на съответната факция на HC mode,както би трябвало да бъде (http://www.wowhead.com/faction=947/thrallmar).

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Има го проблема все още.

**Comment by FALL1N1** [comment]
#447
