### ISSUE TITLE
The Consortium - Reputation Fail 

### ISSUE THREAD

**Issue by Min4AKK** [Warglaive/DragonFireOriginal-3.3.5#383]
Същото важи и за The Consortium,мобовете от Mana Tombs (http://www.wowhead.com/zone=3792/mana-tombs) 
Мобовете на HC mode би трябвало да дават репутация до Exalted (аз съм Honored) ,но не дават (http://www.wowhead.com/faction=933/the-consortium)

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
По същият начин .

**Comment by FALL1N1** [comment]
#447
