### ISSUE TITLE
Among the Champions - quest !!

### ISSUE THREAD

**Issue by Min4AKK** [Warglaive/DragonFireOriginal-3.3.5#385]
http://www.wowhead.com/quest=13811/among-the-champions е куеста.
1.Undercity,Sen'Jin,Orgrimmar Champions отиват по средата на ринга но не могат да бъдат атакувани
2.Накрая като да победиш Champion и се връща на мястото си не ти отчита ачийвмънт (http://www.wowhead.com/achievement=2836/lance-a-lot),както и не ти дава Mark of the Champion,а получаваш само и единствено buffa,че си победил скоро Champion от съответната класа
3.Не знам дали е бъг или е от факциите,но не можеш да се дуелираш с Alliance Champion (Stormwind,Exodar,Darnassuss,Ironforge,Gnomeregan)

(Аз съм Horde)

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/337
