### ISSUE TITLE
Quest:   [Sacrifices Must be Made]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#386]
http://www.wowhead.com/quest=12007/sacrifices-must-be-made Не може да се вземе Куест итема от Seer of Zeb'Halak http://www.wowhead.com/object=188458/seer-of-zebhalak  за да мина куеста.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Пак си е така.

**Comment by AnTOLI** [comment]
Пак си е така.

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/512
