### ISSUE TITLE
Npc Ymirjar Deathbringer

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#387]
Ymirjar Deathbringer ( http://www.wowhead.com/npc=36892 ) е npc , което се намира в Pit of Saron
(http://www.wowhead.com/zone=4813). 
Тя трябва да има следната  магии. Summon Undead (http://www.wowhead.com/spell=69516 )

**Comment by FALL1N1** [comment]
test

**Comment by FALL1N1** [comment]
fixed
