### ISSUE TITLE
Bloodlust Spell Bug

### ISSUE THREAD

**Issue by Cantouchthis** [Warglaive/DragonFireOriginal-3.3.5#39]
Става дума за Bloodlusta при шамана да кажем ако го пусне в райд или в парти няма значение къде ако примерно шамана реши да смени таланти или друг човек с Дебъфа :http://www.wowhead.com/spell=57724
Дебъфа му се маха след като дадения човек смени таланти а не трябва да е така.

**Comment by FALL1N1** [comment]
Няма нищо, нека е така. Ще има система като от Warlords при убиване на boss да ви реска cooldown-ите и да маха дебъфове.
