### ISSUE TITLE
Npc Griselda Hunderland text missing 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#391]
Липсва и текста на Нпц то http://www.wowhead.com/npc=28997/griselda-hunderland
Фикс за текса. https://github.com/TrinityCore/TDB_4.3.4_No_Longer_Used/blob/master/old/updates_06/017_2014_08_19_02_world_misc.sql

**Comment by FALL1N1** [comment]
Готов.
