### ISSUE TITLE
Npc Plagueborn Horror

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#392]
http://www.wowhead.com/npc=36879/plagueborn-horror#drops Липсват итемите дето влачат тич Нпц та след тях http://www.wowhead.com/npc=36879/plagueborn-horror#screenshots:id=150553.
Фикс https://github.com/TrinityCore/TrinityCore/commit/164c12cab0cc3c4226738a12bf24a55437679047

**Comment by FALL1N1** [comment]
Готов.
