### ISSUE TITLE
Achievement  [If Looks Could Kill (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#393]
http://www.wowhead.com/achievement=2955/if-looks-could-kill-10-player Не работи трябва да бъдем ударени от магията Focused Eyebeam http://ptr.wowhead.com/spell=63346/focused-eyebeam.

**Comment by Ritokoko** [comment]
Все още не може да се вземе това постижение

**Comment by AnTOLI** [comment]
Не работи и до днес.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Не работи.
