### ISSUE TITLE
Achievement  [Rubble and Roll (10 player)

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#396]
http://www.wowhead.com/achievement=2960/rubble-and-roll-25-player Трябва да убием  25 Rubble http://www.wowhead.com/npc=33768/rubble и  5 пъти ръцете на боса за achievement .
Fix https://github.com/Arkania/ArkCORE4/commit/3bb3283c0715850916d5727ae73f585e7c3459f4
Видео https://www.youtube.com/watch?v=U3zCnGvqvJA

**Comment by FALL1N1** [comment]
Оправен.

**Comment by Ritokoko** [comment]
Все още не може да се вземе това постижение.
