### ISSUE TITLE
Achievement   [Who Needs Bloodlust? (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#397]
Не работи липсва спела http://www.wowhead.com/spell=62320/aura-of-celerity за да се мине achievement.

**Comment by FALL1N1** [comment]
Оправен.

**Comment by AnTOLI** [comment]
Нпц не става пет за да даде Спела.
https://www.youtube.com/watch?v=2W751gnXGpQ&hd=1
