### ISSUE TITLE
Achievement   [Deforestation (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#398]
http://www.wowhead.com/achievement=2985/deforestation-10-player За achievement трябва да убием Нпц та за 10 секунди .
1. 2  Ancient Water Spirits http://www.wowhead.com/npc=33202/ancient-water-spirit
2. 2  Storm Lasher http://www.wowhead.com/npc=32919/storm-lasher
3. 2 Snaplasher http://www.wowhead.com/npc=32916/snaplasher

Видео https://www.youtube.com/watch?v=l7w1PLyRwPE

**Comment by FALL1N1** [comment]
dupe
