### ISSUE TITLE
Bloodlust and Heroism Bug

### ISSUE THREAD

**Issue by Cantouchthis** [Warglaive/DragonFireOriginal-3.3.5#40]
Значи ако пусне 2 играча алианс и хорд комбинарано в Battleground и хордата реши да пусне Bloodlust и алианса също те стакват и дава  Дебъфа и 2 Бъфа на Heroism и Bloodlust.Прикачам и снимка да може да се види добре за какво става дума.
http://prikachi.com/images.php?images/228/7645228o.jpg
http://prikachi.com/images.php?images/229/7645229g.jpg

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Супер е!
