### ISSUE TITLE
Ulduar Achievements

### ISSUE THREAD

**Issue by ghurtalak** [Warglaive/DragonFireOriginal-3.3.5#400]
тези ачиеви не работят.

http://www.wowhead.com/achievement=2891/the-keepers-of-ulduar-25-player
http://www.wowhead.com/achievement=2895/the-secrets-of-ulduar-25-player
http://www.wowhead.com/achievement=2906/unbroken-25-player
http://www.wowhead.com/achievement=2912/shutout-25-player
http://www.wowhead.com/achievement=2926/shattered-25-player
http://www.wowhead.com/achievement=2928/hot-pocket-25-player
http://www.wowhead.com/achievement=2942/i-choose-you-runemaster-molgeim-25-player
http://www.wowhead.com/achievement=2943/i-choose-you-stormcaller-brundir-25-player
http://www.wowhead.com/achievement=2944/i-choose-you-steelbreaker-25-player
http://www.wowhead.com/achievement=3098/dwarfageddon-25-player
http://www.wowhead.com/achievement=2948/cant-do-that-while-stunned-25-player
http://www.wowhead.com/achievement=2952/with-open-arms-25-player
http://www.wowhead.com/achievement=2954/disarmed-25-player
http://www.wowhead.com/achievement=3185/knock-on-wood-25-player
http://www.wowhead.com/achievement=3017/theyre-coming-out-of-the-walls-25-player
http://www.wowhead.com/achievement=3118/lumberjacked-25-player
http://www.wowhead.com/achievement=2997/shadowdodger-25-player

**Comment by FALL1N1** [comment]
Тествайте отново и разпределете всички в разделни теми.
