### ISSUE TITLE
Achievement   [Lumberjacked (10 player)]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#401]
http://www.wowhead.com/achievement=2979/lumberjacked-10-player За Achievement трябва да убием и 3 те елдера за 10 секунди.
Fix https://github.com/TrinityCore/TrinityCore/commit/14e4a557ed5063bcb20a3be58547ab1a3f9bb12d

**Comment by FALL1N1** [comment]
Оправен.

**Comment by Ritokoko** [comment]
Все още не може да се вземе постижението

**Comment by Vanx3lzing** [comment]
Може да се вземе след като се убие Фрейа и след това елдерите.
