### ISSUE TITLE
Npc Ruul the Darkener

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#402]
http://www.wowhead.com/npc=21315/ruul-the-darkener Нпц то седи на едно място а трябва да се разхожда тама.
Фикс https://github.com/TrinityCore/TrinityCore/commit/9feabd1a9e22c34317509a3a3d3003469da678bc

**Comment by FALL1N1** [comment]
Fixed.

**Comment by AnTOLI** [comment]
Не го виждам Нпц то.?

**Comment by Warglaive** [comment]
NPC-то лети, както трябва да е.
