### ISSUE TITLE
NPC Text Missing

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#404]
Няма им текста на Нпц та.
http://www.wowhead.com/npc=16769/firewing-warlock
http://www.wowhead.com/npc=1410/firewing-bloodwarder
http://www.wowhead.com/npc=5355/firewing-defender
http://www.wowhead.com/npc=21661/cabal-skirmisher
http://www.wowhead.com/npc=19469/magistrix-larynna

Fix https://github.com/TrinityCore/TDB_4.3.4_No_Longer_Used/blob/master/old/updates_06/014_2014_08_11_01_world_misc.sql

**Comment by FALL1N1** [comment]
fixed

**Comment by AnTOLI** [comment]
Пак са си така Нпц та  няма текста.

**Comment by AnTOLI** [comment]
Не работи няма текста.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи :+1:
