### ISSUE TITLE
Tempering The Blade (Quest)

### ISSUE THREAD

**Issue by Cantouchthis** [Warglaive/DragonFireOriginal-3.3.5#406]
Става дума за този Quest:http://www.wowhead.com/quest=24476/tempering-the-blade
Вчера тъй като реших за пореден път да пробвам да мина поредицата от Battered Hilt за 4-ти път ми се наложи първо да мина : http://www.wowhead.com/quest=24461/reforging-the-sword
минах го и след като се опитах да взема Tempering the blade ми изписа you are not eligible for this quest и до там ? Някакво развитие ще има ли за напреде или изобщо да не се мъча за поредицата вече...Тъй като ще стане 5-ти път където ще се мъча да мина поредицата.. и все неуспешни опити..

**Comment by Warglaive** [comment]
Все още неможе да се мине, сив въпросителен вади ( ауто ).
