### ISSUE TITLE
Quest:  [Lost Thunderbrew Recipe]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#408]
http://www.wowhead.com/quest=4134/lost-thunderbrew-recipe Липсват Нпц то http://www.wowhead.com/npc=9541/blackbreath-crony от които пада Куест итема http://www.wowhead.com/item=11312/lost-thunderbrew-recipe.

**Comment by FALL1N1** [comment]
Fixed.

**Comment by Warglaive** [comment]
Проблем:
Spawn-ва http://www.wowhead.com/npc=9541/blackbreath-crony 
http://wotlk.openwow.com/npc=9537
Но са Evade.

**Comment by AnTOLI** [comment]
Оправени са. :+1:

**Comment by Warglaive** [comment]
Щом си тествал и си сигурен пишеме го и в changelog-a.
