### ISSUE TITLE
Boss - Instructor Razuvious - Naxxramas

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#409]
http://www.wowhead.com/npc=16061/instructor-razuvious
1.Чува се гласът му,когато говори,но не се вижда какво казва.

**Comment by FALL1N1** [comment]
Не е фатален.

**Comment by AnTOLI** [comment]
Фикс https://github.com/TrinityCore/TrinityCore/commit/54d583b0fbb7ecfb97a731be21218bbb72d80b4d
