### ISSUE TITLE
Quest: Mission: The Murketh and Shaadraz Gateways

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#410]
http://www.wowhead.com/quest=10129/mission-gateways-murketh-and-shaadraz Horde
http://www.wowhead.com/quest=10146/mission-the-murketh-and-shaadraz-gateways Alliance

При приемането на quest-а, не се пуска fly моунт-а чрез които трябва да се изпълни quest-а.

**Comment by FALL1N1** [comment]
Оправен
