### ISSUE TITLE
Food Buff Slippery Eel

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#413]
http://www.wowhead.com/item=43652/slippery-eel При опит да се яде изписва "you're too full to eat that right now" итема те буфф с http://www.wowhead.com/spell=59230/well-fed

**Comment by FALL1N1** [comment]
Работи си, просто трябва да изчакаш 10 секунди нищо че ти дава тази грешка.
