### ISSUE TITLE
[Quest] Banish the Demons & A Crystalforged Darkrune

### ISSUE THREAD

**Issue by GalaxyWoW** [Warglaive/DragonFireOriginal-3.3.5#414]
http://wotlk.openwow.com/quest=11026
http://wotlk.openwow.com/quest=11060

autocomplete са обаче не могат да се върнат, а са част за репутацията с Ogri'la

**Comment by Warglaive** [comment]
Първият е ОК.
https://github.com/DragonFire/3.3.5/issues/511

**Comment by Warglaive** [comment]
Първият е ок.
https://github.com/DragonFire/3.3.5/issues/511
