### ISSUE TITLE
The Culling Of Stratholme (COS)

### ISSUE THREAD

**Issue by Satanique** [Warglaive/DragonFireOriginal-3.3.5#424]
Тествах инстанса на 2та мода (heroic и normal) и това което установих е следното:
1. Само аудиото на Prince Arthas (http://www.wowhead.com/npc=26499/arthas) работи, 
гласът на Uther The Lightbringer (http://www.wowhead.com/npc=26528/uther-the-lightbringer)
и гласът на Jaina Praudmore (http://www.wowhead.com/npc=26497/lady-jaina-proudmoore) 
не се чува изобщо в инстанцията на нито 1 от модовете.
2. Arthas още в началото след разговора с Утър и Джейна понякога бъгва и не може да се пусне евента (този бъг е само на Heroic(5hc)).
3. Липсват 3 боса които са следните:
-Meathook (http://www.wowhead.com/npc=26529/meathook)
-Salramm the Fleshcrafter (http://www.wowhead.com/npc=26530/salramm-the-fleshcrafter)
-Infinite Corruptor (http://www.wowhead.com/npc=32273/infinite-corruptor)

**Comment by FALL1N1** [comment]
След ъпдейта ли я пробва?

**Comment by Warglaive** [comment]
Снощи имаше проблеми.
