### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghurtalak** [Warglaive/DragonFireOriginal-3.3.5#428]
не работи

http://www.wowhead.com/achievement=2188/leeeeeeeeeeeeeroy

**Comment by Min4AKK** [comment]
raboti si wee chovek

**Comment by Min4AKK** [comment]
ili ne si hvanal 50 ili si gi ubil za poveche vreme

**Comment by Min4AKK** [comment]
http://s24.postimg.org/z7o1uunb9/rende.jpg

**Comment by Warglaive** [comment]
Работи от краи време.
