### ISSUE TITLE
Desolace double rep

### ISSUE THREAD

**Issue by Skars666** [Warglaive/DragonFireOriginal-3.3.5#43]
Magram rep increase.
Gelkis rep increase.
P.S. Убих маграм кентавър!/I killed a magram.
http://prikachi.com/images.php?images/700/7645700a.png

**Comment by Skars666** [comment]
бъга е много по голям!
Бия рейвънхолд/сандукейт и си вдигам репа и с двете наведнъж;
Бия картела/пиратите - същото
тимбермал, аргент даун, сенарион... всичко което има опция at war го има бъга.

The bug is way bigger!
I kill Ravenholdt/Sanducate and I get rep from both
I kill the goblin cartel/bloodsail - the same
Timbermaw, Argent Dawn, Cenarion... every faction that has "at war" has this bug.

**Comment by FALL1N1** [comment]
Още ли стои проблема?

**Comment by Warglaive** [comment]
Проблема стои.

**Comment by FALL1N1** [comment]
#447
