### ISSUE TITLE
Achievement  [I Love the Smell of Saronite in the Morning] (10 player)

### ISSUE THREAD

**Issue by Zancrow** [Warglaive/DragonFireOriginal-3.3.5#434]
постижението не работи изпълнихме каквото трябва убихме саронит анимуса и след това убихме генерала но постижението не ни беше зачетено
http://wowwiki.wikia.com/I_Love_the_Smell_of_Saronite_in_the_Morning_(10_player)
http://www.wowhead.com/achievement=3181/i-love-the-smell-of-saronite-in-the-morning-10-player

**Comment by FALL1N1** [comment]
Работи, трябва просто да го вкарате в "Hard Mode"

> > Ако "Saronite Vapor" са повече от 6 то тогава ще е на "Hard Mode"
> > http://prntscr.com/7gd9sz
