### ISSUE TITLE
Item missing  [Cache of the Ley-Guardian]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#435]
Трябва да падна итема на хероник модем от съндака http://www.wowhead.com/object=191349/cache-of-eregos . Но при назе не дропва този итем трябва на всеки от групада да си взема този итема. http://www.wowhead.com/item=52676/cache-of-the-ley-guardian

**Comment by FALL1N1** [comment]
'Loot Cache of the Ley-Guardian only when aura Luck of the Draw applied' т.е не е за всеки по отделно.
