### ISSUE TITLE
Achievement  [The Keepers of Ulduar (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#436]
Не отчита Ходир за ачивмента.http://www.wowhead.com/achievement=2890/the-keepers-of-ulduar-10-player

**Comment by FALL1N1** [comment]
test

**Comment by Chillie** [comment]
Вече го дава,но проблема е,че го дава и на 25 за 10. И обратно на 10 за 25 .

**Comment by Ritokoko** [comment]
Все още е така от 25 трудност дава за 10 и от 10 дава за 25.

**Comment by Ritokoko** [comment]
Работи.
