### ISSUE TITLE
Achievement  [Shattered (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#437]
За него се изискват два моба които боса трябва да спалнне по време на битката но,след като го тествахме изобщо ги нямаше.А преди като сме го пробвали и ги спалнваше сме ги водили във водата да ги гасим но не се е получавало.http://www.wowhead.com/achievement=2925/shattered-10-player

**Comment by FALL1N1** [comment]
Оправен. #286

**Comment by Ritokoko** [comment]
Не работи.Спалнва траша за ачивмента но изчезват не са активни.

**Comment by FALL1N1** [comment]
duplicate
