### ISSUE TITLE
Achievement  [Hot Pocket (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#438]
За този ачивмент се изисква да те качи така да го кажа в казана,и след като те свали от там трябва да ти даде автоматично ачивмента.http://www.wowhead.com/achievement=2927/hot-pocket-10-player ето и клип тои е 20 сек.https://www.youtube.com/watch?v=YkLEa3SoAvk

**Comment by FALL1N1** [comment]
#295
