### ISSUE TITLE
Achievement  [Nerf Scrapbots (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#439]
При последното ни ходене не спалнваше мобове за който и да бил ачивмент. http://www.wowhead.com/achievement=2933/nerf-scrapbots-10-player

**Comment by FALL1N1** [comment]
Оправен. (10/25)

**Comment by AnTOLI** [comment]
Липсва траша сега бяхме тама.?

**Comment by Ritokoko** [comment]
Да нямаше го .

**Comment by FALL1N1** [comment]
Траша го пуска боса.
