### ISSUE TITLE
Achievement  [Champion of Ulduar]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#442]
Не отчита повечето босове при положение че не сме умирали на тях. http://www.wowhead.com/achievement=2903/champion-of-ulduar

**Comment by AnTOLI** [comment]
Fix https://github.com/treak/TrinityCore/commit/341e374c723f0dc78e755ca962d22d5d9a8f54d8
https://github.com/treak/TrinityCore/commit/3530b938a8d390d4d39ac840d5b0e7403b08dbc5

**Comment by FALL1N1** [comment]
Преправен и добавен, ако има нещо отворете пак и пишете.

**Comment by Ritokoko** [comment]
Не отчита http://www.wowhead.com/npc=32845/hodir за ачиевмента

**Comment by Ritokoko** [comment]
Работи.

**Comment by Ritokoko** [comment]
http://wotlk.openwow.com/npc=33113 Този не го отчита на 10 мод
