### ISSUE TITLE
Boss (Тhorim) Ulduar

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#443]
На самият бос след като стартираме евента има невидими нпц-та които не могат да се таргетнат или да се атакуват и същевременно убиват хеалерите в раида .Също така има и в самият тунел където трябва да се премине през него за да се активира битката със Торим. http://www.wowhead.com/npc=32865/thorim

**Comment by FALL1N1** [comment]
Когато го правите отново викнете Game Master за помощ и премахване на тези NPC-та.
