### ISSUE TITLE
Reps problem

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#447]
http://prntscr.com/7fvoxy
При убиване на NPC което принадлежи към фракциите на гоблините, би трябвало да сваля репутацията с всички гоблински зони.

Всъщност мисля, че има проблем с повечето репутации, моля да се погледнат.

**Comment by FALL1N1** [comment]
тест

**Comment by Warglaive** [comment]
Проблема го има все още.

**Comment by FALL1N1** [comment]
merge

**Comment by AnTOLI** [comment]
Много малко реп дава по 1 реп на Kill  на Npc та които дигат репа  с Gadgetzan. Booty Bay. Ratchet. Everlook. в Tanaris пиратите.
Както и в STV гоблините са така по  1 реп.
