### ISSUE TITLE
The Culling of Stratholme

### ISSUE THREAD

**Issue by Attractivee** [Warglaive/DragonFireOriginal-3.3.5#45]
http://www.wowhead.com/npc=26499 не тръгва евента.
Енкоунтъра прескача 50% от босовете в инса, траша преди Epoch hunter-a неможе да се бие и винаги се умира на него.
infinite hunter - http://www.wowhead.com/npc=27743/infinite-hunter#drops
infinite Agent - http://www.wowhead.com/npc=27744/infinite-agent
infinite Adersary - http://www.wowhead.com/npc=27742/infinite-adversary

**Comment by JunkyBG** [comment]
todo: rewrite. :D

**Comment by AnTOLI** [comment]
Развитие по инса има ли че се пусне ли скоро.?

**Comment by AnTOLI** [comment]
Като сте пуснали инса щто вътре има стена и не може да не мина напред ...

**Comment by FALL1N1** [comment]
Къде по-точно?

**Comment by AnTOLI** [comment]
Вътре в инса като влизаш.

**Comment by FALL1N1** [comment]
При мен на 5 normal / heroic няма?

**Comment by AnTOLI** [comment]
На heroic само го има.

**Comment by AnTOLI** [comment]
Траша преди Epoch hunter-a неможе да се бие и винаги се умира на него... Пак така си е. :)

**Comment by AnTOLI** [comment]
Че го оправите ли.?

**Comment by Warglaive** [comment]
Оправен е.

**Comment by AnTOLI** [comment]
Еми маи не е оправен (Траша преди Epoch hunter-a неможе да се бие.)
И като се пусне евента направо на 3 босс отива  Arthas  оправете го.

**Comment by AnTOLI** [comment]
Не се чува никакъв глас на [Uther the Lightbringer] и [Lady Jaina Proudmoore] като говори. :)

**Comment by AnTOLI** [comment]
Arthas като говори с Mal'Ganis  и бум краш на сървъра. :) fix go

**Comment by AnTOLI** [comment]
Развитие по инса.?

**Comment by FALL1N1** [comment]
Пуснете нов issue с ясно описаните бъгове.
