### ISSUE TITLE
Reputation BUG

### ISSUE THREAD

**Issue by ghurtalak** [Warglaive/DragonFireOriginal-3.3.5#451]
http://prntscr.com/7g4rl6 - дава 9 rep, а би трябвало да дава 15 ( http://www.wowhead.com/npc=18405/tempest-forge-peacekeeper )

http://prntscr.com/7g4smq - дава 94 rep, а би трябвало да дава 250 ( http://www.wowhead.com/npc=17976/commander-sarannis )

http://prntscr.com/7g4szo - дава 9 rep, а би трябвало да дава 250 ( http://www.wowhead.com/quest=29692/bring-me-another-shrubbery )

Само тези 2репа тествах, но мисля, че като цяло rep rate-а е свален и то доста

**Comment by FALL1N1** [comment]
Оправен.
