### ISSUE TITLE
Quest - The Grand Melee - Horde Side

### ISSUE THREAD

**Issue by Herflik** [Warglaive/DragonFireOriginal-3.3.5#453]
Ето всички куестове от поредицата : 
1. http://www.wowhead.com/quest=13772/the-grand-melee
2. http://www.wowhead.com/quest=13767/the-grand-melee
3. http://www.wowhead.com/quest=13782/the-grand-melee
4. http://www.wowhead.com/quest=13787/the-grand-melee
5. http://www.wowhead.com/quest=13777/the-grand-melee

Проблемът е че когато отидеш до мястото за битка , не можеш да проведеш диалог със съответните NPC'та - " I'm ready to fight " трябва да е изписано , но липсва.
Ето ги и NPC'тата : 
1.Undercity Valiant - http://www.wowhead.com/npc=33384
2. Undercity Valiant - http://www.wowhead.com/npc=33469
3. Orgrimmar Valiant - http://www.wowhead.com/npc=33460
4. Orgrimmar Valiant - http://www.wowhead.com/npc=33306
5. Sen'jin Valiant - http://www.wowhead.com/npc=33285
6. Sen'jin Valiant - http://www.wowhead.com/npc=33476
7. Silvermoon Valiant - http://www.wowhead.com/npc=33382
8.  Silvermoon Valiant - http://www.wowhead.com/npc=33468
9. Thunder Bluff Valiant - http://www.wowhead.com/npc=33383
10. Thunder Bluff Valiant - http://www.wowhead.com/npc=33473

Ето клип как трябва да протичат битките : https://www.youtube.com/watch?v=7rLF_8mgRaY

**Comment by Herflik** [comment]
Предполагаем fix : https://github.com/TrinityCore/TrinityCore/commit/d84f7c5ebd173f7d99bc21b564e356110a3e07be

**Comment by Herflik** [comment]
Trinity Issue - https://github.com/TrinityCore/TrinityCore/issues/14603

**Comment by FALL1N1** [comment]
Добавен, опитай сега.

**Comment by AnTOLI** [comment]
Пак са си така нямат 'I'm ready to fight' за да почне битка с тях.

**Comment by AnTOLI** [comment]
Пак са си така нямат 'I'm ready to fight' за да почне битка с тях.

**Comment by AnTOLI** [comment]
Работи си.
