### ISSUE TITLE
Quest: Fumping

### ISSUE THREAD

**Issue by Larua** [Warglaive/DragonFireOriginal-3.3.5#459]
barabancheto ne raboti, ne moje se sum nishto i da se izpulni quest.a fix plz

**Comment by AnTOLI** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2a262aad21f7f9205a49769fd39c207c7ff59768

**Comment by Warglaive** [comment]
Моля репортвай както трябва ( написано разбираемо ( на кирилица най-добре ) и с линкове )) или въобще не репортвай.
