### ISSUE TITLE
Ulduar Loot quest bugget

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#46]
Bosa v Ulduar Hodir  [Hodir's Sigil] ne dava itema za questa

**Comment by FALL1N1** [comment]
Повече инфо.

**Comment by Warglaive** [comment]
http://www.wowhead.com/item=45786/hodirs-sigil
Не пада от
http://www.wowhead.com/object=194200/rare-cache-of-winter

**Comment by Warglaive** [comment]
Работи.
