### ISSUE TITLE
Цялостен проблем с CoS ...

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#462]
Така да започна с бъговете , гнома Chormie не дава итема , с който да се отворят кутиите,след което Arthas въобще няма опция за диалог с Uther ,а направо да върви напред. Но след подлеза се бъгва няма евент с Mal'Ganis и си върви напред пропускайки първите два боса и вълните от траш ,следователно по този начин не се активирва таймера за (The Culling of Time ) . После в къщата са бъгави 3-те и 4-тите вълни от траш ( Infinite Adversary,Infinite Agent, Infinite Hunter ) ,но с помощ като се убият третият бос се появява  и всичко до Mal'Ganis е ок ,но когато се убие Infinite Corruptor не дава  (The Culling of Time ) . А главният проблем от цялата работа е,че Arthas когато му хрумне изчезва по средата на пътя,това може да е още преди третия бос или след него. Долу ще опиша как точно трябва да е с подробности .

Да започна с гномчето Chromie ,тя дава куест Dispelling Illusions http://www.wowhead.com/quest=13149/dispelling-illusions под него трябва да има опция за говорене 1 : (Why have I been sent back to this particular place and time? ) ... 2: (What was this decision. ) 3 : (So how does the Infinite Dragonflight plan to intethere. ) ... След което трябва да даде Arcane Disruptor http://www.wowhead.com/item=37888/arcane-disruptor ,това го дава след говоренето И С   куеста  Dispelling Illusions ,ако куеста е минат трябва да има тази опция за говоренето . След това Arcane Disruptor се използва върху кутиите по пътя към Arthas, те са 5 на брой,това е един вид евент .. След това по пътя пак се говори с  Chromie : 1 : ( What do you think they're up to? ) ... 2 : (You want me so do what? ) 3 : (Very well,Chormie . ) След ,което се появява Uther и те имат диалог с Arthas и Jaina. В някои сървъри този диалог се пропуска, защото е дълъг и като се кликне на Arthas има опция за преглед на диалога и за пропускането му. След диалога Uther се маха заедно с Jaina , Arthas  слиза от хълмчето и започва да върви . Точно ,подлез ли да го нарека :D спира там и има опция за говорене (Yes my Prince.We are ready. ) След което казва няколко изречения и продължава. Трепи там двама и се появява Mal'Ganis те имат някакъв диалог. След това се появява траш от двете страни - 10 вълни.По принцип това трябва да се изпише горе Scourge Wave : 0/10 и отдолу Time:25 min. След 5 вълни се появява първия бос Meathook http://www.wowhead.com/npc=26529/meathook ,след още 5 вълни идва втория - Salramm the Fleshcrafter http://www.wowhead.com/npc=26530/salramm-the-fleshcrafter . След тези два боса Arthas трябва да се придвижи към къщата,да се говори с него ,за да се влезе вътре,след което започват пак вълни от траш от Infinite Adversary,Infinite Agent, Infinite Hunter - те са три вида.След като се убият 4 вълни от тях се появява третия бос Chrono-Lord Epoch ,след като той падне Arthas отваря тайната врата и продължава,след като излезе от къщата пак има диалог, говори се с него и продължава . Чисти се целия траш ЗАЕДНО С НЕГО . След това той остава и пуска някакъв диалог,през това време играчите (само на хероик ) трябва да отидат да убият Infinite Corruptor,но той ще е там само ако се стигне до него за 25 минути,след като падне трябва да даде The Culling of Time - http://www.wowhead.com/achievement=1817/the-culling-of-time . И накрая с Аrthas се продължава до последния бос,който е  Mal'Ganis.

**Comment by FALL1N1** [comment]
Кашоните са махнати тъй като още работя по него (ще ги върна когато го завърша)
Има странен бъг когато Alliance говори с Arthas (или сте в смесена Horde/Ally група) да пропуска първите 2, за това съм ги призовал.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Инса може да се мине, остана проблема с пропускането на първите 2 боса.

**Comment by FALL1N1** [comment]
Проблема е от смесените групи, пробвайте ако е смесена да pull-не(говори с Arthas) ХОРД и обратното, ако НЕ са смесени.

**Comment by FALL1N1** [comment]
fixed
