### ISSUE TITLE
Quest "Seal of Ascension"

### ISSUE THREAD

**Issue by Drunds** [Warglaive/DragonFireOriginal-3.3.5#464]
Quest "Seal of Ascension" <-!!!!!!!След като поставя Quest itema - ["Unforged Seal of Ascension"] ,пред самия дракон  ,бия дракона докато падне до 20% или под ,след това с другия Quest Item  ["Orb of Draconic Energy"] mind controlvam самия дракон ,след като е mind control трябва да има 1 магия с която да счупя самия камък ["Unforged Seal of Ascension"] и да си взема Quest Itema от счупения камък за да complete Questa, но тая магия я няма и затова не мога ,ако може да се направи нещо по въпроса ще бъда благодарен. :)

**Comment by Warglaive** [comment]
Моля слагайте линкове, за да не се занимава колегата да търси, а директно да фиксне.
http://wotlk.openwow.com/?search=Seal+of+Ascension#quests

**Comment by FALL1N1** [comment]
Оправен.

**Comment by Warglaive** [comment]
При нас е 10% HP, и понякога cancel на дракона ( за освобождаване ) не работи.
НО Quest-а си работи!
