### ISSUE TITLE
Проблем с  Gundrak .

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#468]
Боса Drakkari Colossus http://www.wowhead.com/npc=29307/drakkari-colossus като е под 70k hp се бъгва и се връща на мястото си и си възвръща кръвта,следователно не може да се убие.По принцип трябва да стане така като е под 50% да кастне emerge,но да излиза елементалa Drakkari Elemental http://www.wowhead.com/npc=29573/drakkari-elemental  и така да се сменят няколко пъти докато не се убият.

**Comment by FALL1N1** [comment]
http://prntscr.com/7j8hje
50% e.

**Comment by Warglaive** [comment]
Проблема е, че когато почне да каства се връща назад, каста интеруптва, боса се реска и така, трябва да го погледнеш да видиш как е точно.

**Comment by FALL1N1** [comment]
test

**Comment by Chillie** [comment]
Работи.

**Comment by AnTOLI** [comment]
Работи но само боса Drakkari Colossus си го убиваме и не излиза другия босс Drakkari Elemental.
