### ISSUE TITLE
Achievement [Abuse te Ooze]

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#469]
След като се убият 5те озета и след тях боса,ачивмънта не го отчита.

**Comment by AnTOLI** [comment]
http://wotlk.openwow.com/achievement=2155

**Comment by FALL1N1** [comment]
Да се провери след рестартра.

**Comment by kurevaglava** [comment]
Работи ачивмънта.
