### ISSUE TITLE
Ulduar Quest bugget 

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#47]
Algalon Questa itema  [Reply-Code Alpha] nemoje dase polzva ot horde (Dont hame need requirements)

**Comment by FALL1N1** [comment]
Повече инфо!

**Comment by Warglaive** [comment]
http://www.wowhead.com/item=46053 / http://www.wowhead.com/item=46052
Са разменени най-вероятно, тоест при хордите пада алианското, а при алиансите - хордското.

Падат от 
http://www.wowhead.com/object=194821/gift-of-the-observer#see-also

**Comment by FALL1N1** [comment]
Падат 2 предмета, използвай хордския.
