### ISSUE TITLE
Achievement [ My Girl Loves to Skadi All the Time ] -  Utgarde Pinnacle.

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#470]
Работеше до преди няколко дена,но сега дракона Grauf http://www.wowhead.com/npc=26893/grauf няма таргет и не може да се бие и не дава  [ My Girl Loves to Skadi All the Time ] след като се убие боса Skadi the Ruthless http://www.wowhead.com/npc=26693/skadi-the-ruthless .
"Defeat Skadi the Ruthless in Utgarde Pinnacle on Heroic Difficulty after having killed Grauf from 100% to dead in a single pass."  http://www.wowhead.com/achievement=2156/my-girl-loves-to-skadi-all-the-time

**Comment by AnTOLI** [comment]
Работи си.

**Comment by FALL1N1** [comment]
Трябва да го стреляте с харпуна, колежке.. :D

**Comment by Chillie** [comment]
Копията са ок,знам го..Проблема е ,че дава вече инстант [ My Girl Loves to Skadi All the Time ] ,а бъга с дракона си седи ама се тая ;д

**Comment by AnTOLI** [comment]
Няма фикс за драгона или поне не е оправен добре за това е направен така..

**Comment by Warglaive** [comment]
Реално има проблем по последният бос.

**Comment by Warglaive** [comment]
Работи.
