### ISSUE TITLE
NPC Elder Nadox(Ahn'kahet: The Old Kingdom)

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#471]
След като нпцто пусне гардиън,то получава бъф който го прави имюн към всякакъв вид дпс.След като бъде отдалечен гардиъна от него на над 30 ярда,бъфа на пада и по този начин не може да бъде изпълнен ачивмънта [Respect Your Elders]

**Comment by AnTOLI** [comment]
Боса http://www.wowhead.com/npc=29309/elder-nadox
Achievement http://www.wowhead.com/achievement=2038/respect-your-elders

**Comment by FALL1N1** [comment]
Оправен.
