### ISSUE TITLE
Голям Бъг! Vehicles в Wintergrasp 

### ISSUE THREAD

**Issue by Larua** [Warglaive/DragonFireOriginal-3.3.5#472]
Когато се извати машина от който и да било от 4-те уъркшопа, тя не пада на платформата, от която може да се изправи, а точно на НПС-то, следователно засича и няма как да бъде извадена. Следователно крепоста не може да се превземе и ордата си я държат, трупат онор и ми се смеят в уърлд по цял ден. Имаме нужда от хотфикс, да се оправи тая бъгня или поне да се направи неутрална крепостта, за да не се ояждат едните!

**Comment by FALL1N1** [comment]
Оправен.
