### ISSUE TITLE
Loken Text Missing

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#473]
http://www.wowhead.com/npc=28923/loken  Липса му този текст на боса преди да се отиде до него да се бие казва. 
https://github.com/WingsEmulation/ProjectRisingDarkness/blob/master/sql/updates/world/2012_02_29_03_world_creature_text.sql

**Comment by FALL1N1** [comment]
fixed

**Comment by AnTOLI** [comment]
Не работи не казва нищто като се отиде до него.

**Comment by Warglaive** [comment]
Вчера съм го тествал, ок е.
