### ISSUE TITLE
[Quest] Shredder Repair

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#475]
Куестът http://www.wowhead.com/quest=12244/shredder-repair не работи както трябва.От 4 възможни шредера за ползване само 1 работи,но и той след един път като се качиш на него и го върнеш спира да става достъпен за "маунтване".

**Comment by FALL1N1** [comment]
fixed

**Comment by Warglaive** [comment]
Проблемите с спеловете и маунтването са оправени, но не отчита при опит за изпълнение.

**Comment by Larua** [comment]
Да, куеста не работи, чаакм фикс с нетърпение, благодаря предварително, дано да е скоро.
