### ISSUE TITLE
Item: Scourgestone

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#476]
http://prntscr.com/7hlnl0
Вместо показаният предмет на снимката, мобовете трябва да дропват http://wotlk.openwow.com/item=43169
а в момента дропват http://wotlk.openwow.com/item=40582

предмета е зa quest.

**Comment by FALL1N1** [comment]
Да беше дал и кои мобове го дропват :D

**Comment by Warglaive** [comment]
Дал съм http://prntscr.com/7ho3qs :D

**Comment by Warglaive** [comment]
Проблема всъщност не е че ид-тата са объркани, самите итеми нещо са прецакани, моля огледаи ги, преди да го оправиш.

**Comment by Pavslav** [comment]
Точно ИД-тата са объркани .Няма как да носиш повече от 1 http://wotlk.openwow.com/item=40582 (това си е hearthstone който ти го дава когато си направиш 55-лвл DK). Просто при миналия fix-а не е съобразено че е възможно да съществува 1 предмет с две различни ид-та.

**Comment by Warglaive** [comment]
http://wotlk.openwow.com/item=40582 Това е за DK-тата, но при нас е http://prntscr.com/7isrhm
http://wotlk.openwow.com/item=43169 - Това е за quest-а, но при нас е http://prntscr.com/7isrcy

**Comment by FALL1N1** [comment]
fixed

**Comment by Warglaive** [comment]
Нов проблем, неможе да се предаде.
http://prntscr.com/7lqfyw

**Comment by Warglaive** [comment]
Работи.

**Comment by AnTOLI** [comment]
Не работи.
Пак са си така дроп само  [Scourgestone]..
