### ISSUE TITLE
Ulduar Mimiron Quest Bugged

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#48]
Quest itema za questa  [Mimiron's Sigil] ot mimiron kovchega ne pada

**Comment by FALL1N1** [comment]
Повече инфо!

**Comment by Warglaive** [comment]
http://www.wowhead.com/quest=13611/mimirons-sigil#comments
Не дропва от 
http://www.wowhead.com/object=194789/cache-of-innovation

**Comment by FALL1N1** [comment]
Оправено.
