### ISSUE TITLE
Achievement  [Gonna Go When the Volcano Blows (10 player)] The Obsidian Sanctum 10/25

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#482]
Не работи ,тествахме го тои е за сам играч не изисква целия раид да се пази и аз успях да се предпазя от лавата но нямаше късмет да зема ачивмента. http://www.wowhead.com/achievement=2047/gonna-go-when-the-volcano-blows-10-player

**Comment by FALL1N1** [comment]
Местя #95 тук тъй като тази е описана по-добре.

**Comment by FALL1N1** [comment]
hack, при убийство на boss-a ще го дава на всички.

**Comment by Warglaive** [comment]
Отново не го дава, дори само при убииство на бос-а.

**Comment by AnTOLI** [comment]
Не работи. :(

**Comment by Ritokoko** [comment]
Все още не работи този ачиевемент ако има вариант да го направите hack или ако има възможност да го фикс .Чакаме го над 15 души за да си завършим ачиевемента http://wotlk.openwow.com/achievement=2138 също и http://wotlk.openwow.com/achievement=2137

**Comment by Ritokoko** [comment]
Работи.Благодаря :)
