### ISSUE TITLE
Invisibility-Spells-Mage

### ISSUE THREAD

**Issue by Pavslav** [Warglaive/DragonFireOriginal-3.3.5#483]
При пускането на http://wotlk.openwow.com/spell=67765 кастера влиза във битка с всички създания(агресивни/пасивни)които са около него (подобно на taunt но не взима agrro от вече биещи се създания).Проблема най вероятно е от бъф-а който получаваме не мога да намеря ид ето един screen дано помогне http://prntscr.com/7j0is8

**Comment by FALL1N1** [comment]
test

**Comment by Pavslav** [comment]
fixed.
