### ISSUE TITLE
Wintergrasp: Warsong Champions

### ISSUE THREAD

**Issue by Larua** [Warglaive/DragonFireOriginal-3.3.5#484]
http://www.wowhead.com/npc=30739/warsong-champion

Тези НПК-та трябва да се рескат из зоната, когато крепостта е контролирана от Ордата. Добре, обаче те не се рескат. Нито на мостовете, нито около кулите, нито около крепостта. Следователно няма как да се убият. Следователно няма как да се вземе ранг. Следователно няма как да се вземе машина. Следователно няма как да се бутне крепостта. Следователно, WG е непревземаем и в ръцете на ордата перманентно отново! HOTFIX PLS!

**Comment by Warglaive** [comment]
Потвърдено, spawn-ват се само вътре 1-2 и това е, извън сградата също трябва да има ако хордите контролират.

**Comment by Warglaive** [comment]
Трябва да е ОК.

**Comment by Larua** [comment]
Не бързай да го затваряш, понеже проблемът не е решен. Шампионите вече са там, но не дават бъфа, който вдига ранг-а с който се взимат машини. Убих Warsong Champion-и 10 на брой и нищо. Пак не мога да взема машина, пак не мога да взема крепостта.

**Comment by FALL1N1** [comment]
Wintergrasp-а започнал ли е?
Репорта ти е за липсващи NPC-та а не за бъф. Отвори нов ако наистина има този проблем.

**Comment by Warglaive** [comment]
Пак не се появяват воиниците както трябва, при контрол на алианце над даден workshop трябва да има алли воиници, но няма, понякога се появяват на места, но не е както трябва.

**Comment by AnTOLI** [comment]
Няма ги пак по БГ то Нпц та http://www.wowhead.com/npc=30739/warsong-champion .
