### ISSUE TITLE
[Dungeon Finder: The Frost Lord Ahune] Satchel of chilled Goods 

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#485]
При изпълнението на dungeon-а трябва да го отчете като изпълнен и да награди играчите с http://wotlk.openwow.com/item=54536 ( Също така, самият Satchel няма лоот вътре в него при отваряне http://prntscr.com/7j90d1).
Но не работи.

**Comment by FALL1N1** [comment]
fixed.
