### ISSUE TITLE
Quest   [Torch Tossing]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#488]
http://www.wowhead.com/quest=11922/torch-tossing Не работи не може  направа  20 hit  braziers за даденото време Куеста. (Таимера на Куеста трябва да е 1 мин и 25 сек).
https://www.youtube.com/watch?v=45marDeb-Dk

**Comment by Warglaive** [comment]
Проблема е, че липсваха обекти ( аднах ги ) сега вече трябва да се направи да отчита ( Емо ти си  :D )

**Comment by Warglaive** [comment]
работи.

**Comment by Warglaive** [comment]
При алиансите - Работи ( отчита го при първият хит,hackfix ), при хорде - не.

**Comment by AnTOLI** [comment]
Развитие при хорде има ли.

**Comment by Warglaive** [comment]
Ако има, ще напишеме?

**Comment by FALL1N1** [comment]
Авто е, пробвайте го.

**Comment by AnTOLI** [comment]
Пак си е така не е ауто.
