### ISSUE TITLE
 Quest: [Decoy!]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#49]
Неможе да се постави http://www.wowhead.com/item=21041/bag-of-gold на оказаното място.

**Comment by FALL1N1** [comment]
Оправен.

**Comment by Warglaive** [comment]
Проблема все още го има, неможе да се постави торбата и NPC-то НЕ излиза.
Spawn-нато е NPC-то и quest-a работи.
