### ISSUE TITLE
Npc Earthen Ring Elder Missing Quest

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#491]
Липсват Куестите от Нпц то http://www.wowhead.com/npc=26221/earthen-ring-elder за евента Midsummer Fire.
1. http://www.wowhead.com/quest=11917/striking-back да убием в Ashenvale нпц то Frostwave Lieutenant http://www.wowhead.com/npc=26116/frostwave-lieutenant
2. http://www.wowhead.com/quest=11947/striking-back да убием в Desolace нпц Hailstone Lieutenant http://www.wowhead.com/npc=26178
3. http://www.wowhead.com/quest=11948/striking-back да убием в Stranglethorn Vale нпц то Chillwind Lieutenant http://www.wowhead.com/npc=26204/chillwind-lieutenant
4. http://www.wowhead.com/quest=11952/striking-back да убием в Searing Gorge нпц то Frigid Lieutenant http://www.wowhead.com/npc=26214/frigid-lieutenant
5. http://www.wowhead.com/quest=11953/striking-back да убием в Silithus нпц то Glacial Lieutenant http://www.wowhead.com/npc=26215/glacial-lieutenant

**Comment by FALL1N1** [comment]
An Innocent Disguise test
