### ISSUE TITLE
Npc Magmoth Shaman (Totem Missing)

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#493]
http://www.wowhead.com/npc=25428/magmoth-shaman Липсват тотемите към тия Нпц та.
Фикс https://github.com/TrinityCore/TrinityCore/commit/0e4db8964b2b92b077ad8f5637a9dc0bcfcebf88

**Comment by AnTOLI** [comment]
:+1:

**Comment by AnTOLI** [comment]
Да се сложи пак фикса.

**Comment by FALL1N1** [comment]
Стига отваряхте и затваряхте, оправен е при следващия ъпдейт.

**Comment by AnTOLI** [comment]
Не няма ги тотемите.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи.
