### ISSUE TITLE
Achievement :  [Burning Hot Pole Dance] Midsummer World Event

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#495]
http://www.wowhead.com/achievement=271/burning-hot-pole-dance. Трябва да се съберат три части от сета http://www.wowhead.com/item=34683/sandals-of-summer / http://www.wowhead.com/item=34685/vestment-of-summer / http://www.wowhead.com/item=23324/mantle-of-the-fire-festival   и да се танцува до Риббон Поле (Ribbon Pole) 60 секунди за да даде ачиевемента но не го дава.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Вече дава http://prntscr.com/7m9ihv
този бъф, но все още не работи.

**Comment by FALL1N1** [comment]
http://prntscr.com/7q0hgo След рестарта евънта ще бъде удължен с 7 дни и постижението ще работи.

**Comment by Moonlord** [comment]
Само, че нещо удължаването не се е получило :/

**Comment by FALL1N1** [comment]
HC>1 - Midsummer Fire Festival  [active]
