### ISSUE TITLE
Quest: Prayer to Elune

### ISSUE THREAD

**Issue by Larua** [Warglaive/DragonFireOriginal-3.3.5#496]
http://wotlk.openwow.com/quest=3378

Ковчежето на скрийншота е ключово за изпълняването на този куест в Searling Gorge. Обикалях като луд в горния ляв ъгъл на картата и не го намерих. Няма как да изпълна куеста. Fix plz.

**Comment by Warglaive** [comment]
Благодаря за репорт-а, само ако е възможно линковете да ги даваш от http://wotlk.openwow.com/ , защото ид-тата се разминават както в случая.
( оправил съм го )

**Comment by Warglaive** [comment]
Quest item-a дропва от NPC-та и quest-а работи, ако имаш проблем - тикет.
