### ISSUE TITLE
Quest : [Torch Catching]  Midsummer World Event

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#497]
http://www.wowhead.com/quest=11657/torch-catching Този куест трябва да се минава по следния начин .Като вземеш куеста ти дава : http://www.wowhead.com/item=34833/unlit-torches .С този куест итем трябва да отидеш до (Midsummer Bonfire) и да запалиш куест итема от този огън като се запали след това трябва да изхвърчи към въздуха запалената факла и ти да и следиш сянката която се показва на земята и да я хванеш.

**Comment by FALL1N1** [comment]
авто
