### ISSUE TITLE
Achievement [Dwarfageddon]

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#498]
http://www.wowhead.com/achievement=3097/dwarfageddon-10-player не го отчита след като се убият 100 траша,а също така след като се убие 1 траш не се вкючва таймера.Това е на 10ка,за 25 не знам дали има същия проблем.

**Comment by FALL1N1** [comment]
test

**Comment by kurevaglava** [comment]
На 10ка все още не работи ачивмънта,отново не се пуска таймера и не отчита джуджетата.

**Comment by Warglaive** [comment]
Все още НЕ работи.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Работи.
