### ISSUE TITLE
Achievement:  [Champion of Ulduar]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#499]
http://wotlk.openwow.com/achievement=2903
Не отчита Hodir  ( http://wotlk.openwow.com/npc=32845 )

**Comment by FALL1N1** [comment]
test

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Отчита си го ходир стар си  е репорта.
