### ISSUE TITLE
[Quest] The Halls of Reflection

### ISSUE THREAD

**Issue by opalq** [Warglaive/DragonFireOriginal-3.3.5#5]
http://www.wowhead.com/quest=24561

Куестът е част от поредицата за Quel'Delar. Когато се приближиш до Frosmourne в центъра на стаята в HoR, трябва да "излезе" мечът Quel'Delar като бос (ако в групата има някои с въпросният куест), който като са убие да дропне http://www.wowhead.com/item=50254. 

Отделно при самото влизане в HoR трябва да се "отчете", че мечът е донесен там. В момента не работи, и не се изпълнява нито едно от 2те условия

**Comment by FALL1N1** [comment]
Авто.
