### ISSUE TITLE
The Challenge

### ISSUE THREAD

**Issue by Rikosanchez** [Warglaive/DragonFireOriginal-3.3.5#500]
Mojete li da go fixnete The Challenge questa pravi se v brd na Ring of the Law , zimase ot edno npc pred stratholme i poprincip kato go nrapvi se predava v dire maul pri shendrelarite.Vednash mi se naloji da go mahna i da go zema na novo , no ne mi dade da go vzema a kato otidoh v dire maul tam mi ot4ita kato daily questa i mi iska quest item i po tozi nachin ne moga da go mina.

**Comment by Warglaive** [comment]
Ако репортваш - репортваи както трябва, подобни маимуници са ненужни.
