### ISSUE TITLE
Icecrown Citadel: Rotface (Boss) - Big Ooze

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#502]
След като боса (Rotface, http://www.wowhead.com/npc=36627/rotface#drops:mode=n10) бъде убит, призованите от него Big Ooze-та (http://www.wowhead.com/npc=36899/big-ooze) НЕ изчезват, а би трябвало.

**Comment by FALL1N1** [comment]
(y) утре ще е оправено.

**Comment by FALL1N1** [comment]
Test

**Comment by Warglaive** [comment]
Оправено.

**Comment by Warglaive** [comment]
На 10 нормал не изчезва.

**Comment by FALL1N1** [comment]
Вече е ок.
