### ISSUE TITLE
Icecrown Citadel: Professor Putricide (Boss) - Gas Cloud

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#503]
Едно от двете озета, които боса (Professor Putricide, http://www.wowhead.com/npc=36678/professor-putricide) пуска, е Gas Cloud (http://www.wowhead.com/npc=37562/gas-cloud#abilities:mode=n10). В момента то не може да бъде манипулирано по никакъв начин -  stun, slow, fear и т.н.

**Comment by FALL1N1** [comment]
(y) утре ще е оправено.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Работи си.

**Comment by AnTOLI** [comment]
Пак са си така озетата не може stun, slow, fear и т.н.
