### ISSUE TITLE
Icecrown Citadel: Valithria Dreamwalker(Boss) -Portals

### ISSUE THREAD

**Issue by Pavslav** [Warglaive/DragonFireOriginal-3.3.5#504]
http://www.wowhead.com/npc=36789/valithria-dreamwalker
При пускането на 1-вите портали всичко е добре има сфери за събиране и получаване на буф в другото измерение,но когото пусне 2-рите портали сферите в другото измерение не се рескат а би трябвало да се.

**Comment by Warglaive** [comment]
Персонален бъг може би, тествах боса - всичко е ОК.
