### ISSUE TITLE
Warsong Gulch:Supreme Defender(Achievement)

### ISSUE THREAD

**Issue by Pavslav** [Warglaive/DragonFireOriginal-3.3.5#505]
http://www.wowhead.com/achievement=206/supreme-defender
Не дава кредит при убийство на флагер.Трябва да  го отчита при honorable kill,(но в момента дори и при killing blow не го отчита)

**Comment by FALL1N1** [comment]
test

**Comment by Pavslav** [comment]
fixed.(тестван при  killing blow)

**Comment by Pavslav** [comment]
при honorable kill все още не работи

**Comment by Pavslav** [comment]
При honorable kill все още не работи.Моля да се погледне отново.

**Comment by kurevaglava** [comment]
Дори и на Killing Blow не ги отчита.

**Comment by FALL1N1** [comment]
#705
