### ISSUE TITLE
Quest - Conversing With the Depths - Dragonblight

### ISSUE THREAD

**Issue by M-Mihailov** [Warglaive/DragonFireOriginal-3.3.5#506]
Quest-а http://wotlk.openwow.com/quest=12032 е направен като instant complete, но когато избереш reward-а и натиснеш Complete quest не се случва нищо.

**Comment by FALL1N1** [comment]
test / kodiran + izpulnqem

**Comment by Warglaive** [comment]
http://prntscr.com/7m9hf0
Неможе да се цъкне на разговора за да се стартира евент-а.
