### ISSUE TITLE
Quest: The Angry Gorloc

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#51]
Когато NPC-то което се spawn-ва от 
http://www.wowhead.com/item=38624
се заведе до селото, нищо не става, а трябва да отчете questa-а като изпълнен.
http://www.wowhead.com/quest=12578/the-angry-gorloc

**Comment by FALL1N1** [comment]
Оправен!

**Comment by Warglaive** [comment]
Autocomplete...
