### ISSUE TITLE
Achievement :  [Didn't Stand a Chance] Wintergrasp Battle

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#510]
http://www.wowhead.com/achievement=1751/didnt-stand-a-chance Този ачивмент не работи.За него не е от значение кой контролва базата просто трябва да се качиш на оръдие " Tower Cannon" .Нужно е само да си на оръдие което е на кула примерно Алианска за Алиансите и така и за Хордите.

**Comment by FALL1N1** [comment]
test
