### ISSUE TITLE
Quest :  [Sacrifices Must be Made]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#512]
http://www.wowhead.com/quest=12007/sacrifices-must-be-made Този куест не работи след като го вземеш от от "Image of Drakuru" той се появява от "Drakuru's Brazier"

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues?q=is%3Aissue+Sacrifices+Must+be+Made+is%3Aclosed
Доста хора чакат за този яуест явно, затова слагам по-голям приоритет.

**Comment by FALL1N1** [comment]
Авто е?

**Comment by Chillie** [comment]
Емо не е авто,бъгав си е още.

**Comment by Ritokoko** [comment]
Самият проблем на този куест е че след като вземеш http://www.thottbot.com/item=35836/zimbos-mojo от http://www.thottbot.com/npc=26544/warlord-zimbo и отидеш и кликнеш на http://www.thottbot.com/object=188458/seer-of-zebhalak трябва да ти даде http://www.thottbot.com/item=35806/eye-of-the-prophets но не го дава.Ако е трудно за фикс може да се направи като в силитус за Скараб лорд титлата.Дефакто вендор с http://www.thottbot.com/item=35806/eye-of-the-prophets в него

**Comment by FALL1N1** [comment]
http://prntscr.com/948kf1

Добавено NPC с куест айтъма.
