### ISSUE TITLE
Item: [Essence-Infused Moonstone]

### ISSUE THREAD

**Issue by Phyorax** [Warglaive/DragonFireOriginal-3.3.5#513]
http://wotlk.openwow.com/item=32449 - с този ексклузивен друидски предмет, се експлоитва боса в Sethekk Halls - Anzu (http://wotlk.openwow.com/npc=23035), като си го призоваваш n-пъти в инстанцията. Идеално "решение" за мързеливите, да си фармят маунта..

**Comment by Warglaive** [comment]
Ако неможе да се фиксне по нормалният начин, предлагам да му се сложи cooldown time 24 hrs.

**Comment by FALL1N1** [comment]
Fixed - 24h cooldown на предмета.

**Comment by Warglaive** [comment]
След релог Cooldown-a се маха.
