### ISSUE TITLE
NPC Shade of Akama

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#516]
Първо има някаква невидима преграда и не може да се влезе в стаята дето е боса,второто е че след като се влезе боса http://www.wowhead.com/npc=22841/shade-of-akama#drops не може да се бие нито траша около него и самия евент не може да почне.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/568
