### ISSUE TITLE
Re:Spell [Death Wish]

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#518]
Отварям го тоя пост,защото предния е затворен.Знаем че http://wotlk.openwow.com/spell=13048 и http://wowwiki.wikia.com/Death_Wish не стакват.Проблема е такъв,че ако пуснем Death Wish и уориъра бъде ударен и прокне таланта Enrage,тоя енрейдж премахва Death Wish,а попринцип не трябва да е така.Докато Death Wish така да се каже стои на уара, той не трябва да бъде изместван от Enrage,също така Enrage не трябва да проква по време на Death Wish.
 "Patch 2.1.0 (22-May-2007): Death Wish and Enrage no longer stack: with both Death Wish (+20% damage) and Enrage present, the greater effect will be picked (Death Wish)." http://wowwiki.wikia.com/Enrage_(warrior_talent)

**Comment by FALL1N1** [comment]
Няма как да бъде оправено, липсват много системи от AuraEffect-ите.. Или ако бъде оправено ще е след месеци..
