### ISSUE TITLE
Quest [ Cleansing Drak`Tharon ] (part 8 of 8 ) 

### ISSUE THREAD

**Issue by drmls** [Warglaive/DragonFireOriginal-3.3.5#519]
http://www.wowhead.com/quest=30120/cleansing-draktharon 
[ Drakuru's Elixir ] Quest item-a не spawnva mob-a

Edit: Quest-а е за http://www.wowhead.com/achievement=1596/guru-of-drakuru затова слагам Priority Mid.

**Comment by Warglaive** [comment]
Quest-a РАБОТИ, За да се изкара mob-a ви трябва
http://www.wowhead.com/item=38303/enduring-mojo
