### ISSUE TITLE
dragonblight quests

### ISSUE THREAD

**Issue by denislav92** [Warglaive/DragonFireOriginal-3.3.5#52]
The plume of Alystros:  posredstvom quest itema Skytalon Molts trqbva da tauntna zelenata ptica ot skalata no nishto ne stava

Mystery of the infinite.Redux: postavqm quest itema Hourglass of eternity i nishto ne se spawnva

**Comment by Warglaive** [comment]
http://www.wowhead.com/quest=12456/the-plume-of-alystros
http://www.wowhead.com/quest=12470/mystery-of-the-infinite
http://www.wowhead.com/quest=13343

**Comment by FALL1N1** [comment]
Оправени.
