### ISSUE TITLE
NPC: Ebru 

### ISSUE THREAD

**Issue by Larua** [Warglaive/DragonFireOriginal-3.3.5#520]
http://wotlk.openwow.com/npc=5768

Toва НПК ми излиза на мини-мап-а, когато влизам през входа на пещерата за Wailing Caverns в The Barrens. За съжаление обаче, НПК-то го няма никъде и не мога да взема куеста който иска да ми даде. Spawn pls.

**Comment by Warglaive** [comment]
NPC-то си е на мястото, разгледай по-добре.
