### ISSUE TITLE
Battlegrounds - Deserter debuff

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#522]
При напускане на батъл граунд преди да е приключил би трябвало плеърът да получи дебъфа Deserter (http://www.wowhead.com/spell=26013/deserter). В момента не работи.

**Comment by AnTOLI** [comment]
Ако искат да няма БГ та да го пуснат . ;д

**Comment by Warglaive** [comment]
Направено е умишлено.
