### ISSUE TITLE
Achievement :  [Nerf Scrapbots (10 player)] 

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#523]
http://www.wowhead.com/achievement=2933/nerf-scrapbots-10-player Не спалнва траша за ачивмента.

**Comment by AnTOLI** [comment]
Не работи няма ги нпц та 10/25.

**Comment by Ritokoko** [comment]
Напротив колега всичко си е наред с тях просто трябва да доглеждате нещата.Всичко си е добре
