### ISSUE TITLE
Achievement :  [Supermassive (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#524]
http://www.wowhead.com/achievement=3003/supermassive-10-player . След като се затвотят 3 портала и после се убие боса не зачита че сме затборили 3те Black Holes

**Comment by FALL1N1** [comment]
hack

**Comment by FALL1N1** [comment]
hack test

**Comment by Ritokoko** [comment]
Дава го .
