### ISSUE TITLE
Achievement :  [I Choose You, Stormcaller Brundir (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#525]
http://www.wowhead.com/achievement=2940/i-choose-you-stormcaller-brundir-10-player Не работи след като оставим дадения босс да се убие последен

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Не работи

**Comment by Ritokoko** [comment]
Работи.
