### ISSUE TITLE
Achievement :  [I Choose You, Runemaster Molgeim (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#526]
http://www.wowhead.com/achievement=2939/i-choose-you-runemaster-molgeim-10-player  Не работи след като сме оставили определения босс да умре последен

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Не работи.

**Comment by Ritokoko** [comment]
Работи.
