### ISSUE TITLE
Achievement :  [I Choose You, Steelbreaker (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#527]
http://www.wowhead.com/achievement=2941/i-choose-you-steelbreaker-10-player  Не работи след като се остави дадения босс да се убие последен.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Не работи.

**Comment by Ritokoko** [comment]
Работи.
