### ISSUE TITLE
Achievement :  [I Love the Smell of Saronite in the Morning (10 player)]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#528]
http://www.wowhead.com/achievement=3181/i-love-the-smell-of-saronite-in-the-morning-10-player Не работи оставихме Saronite Vapors шест броя от които се появява Saronite Animus и трябва да се убие първо Saronite Animus след това да се убие боса

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Работи.
