### ISSUE TITLE
Липсващо NPC njormeld

### ISSUE THREAD

**Issue by cvasilev** [Warglaive/DragonFireOriginal-3.3.5#529]
http://www.wowhead.com/search?q=njormeld това NPC го няма на нито едното от двете места където може да е според  поредицата от куестове. http://www.wowhead.com/quest=12976/a-monument-to-the-fallen няма на кого да се върне.

**Comment by Warglaive** [comment]
NPC-то е там просто не се вижда от играчи, явно бърка фазите нещо, остави тикен ингаме ако желаеш помощ.

**Comment by FALL1N1** [comment]
test

**Comment by cvasilev** [comment]
Не, трих и кеш папката и всичко. Даже ако сме в парти в момента в който горе доло стигна до К3 кампа не ме виждат повече.... Дори в К3 не ми дава дейли куеста който имаше някога. Може ли героя да е бъгнат нещо ?

**Comment by FALL1N1** [comment]
Махнал съм му фазата вчера, вече трябва да си се вижда

**Comment by cvasilev** [comment]
Няма го npc-то, няма му наковалнята няма я каската няма го копието, хорна
също липсва и ледения отгоре. Явно героя не е у ред защото въпреки
репутацията и куестовете изобщо не е в фазата която трябва.

2015-07-03 20:49 GMT+03:00 Emiliyan notifications@github.com:

**Comment by Warglaive** [comment]
Ticket ingame да го видиме, затварям репорт-а, ако в бъдеще има още оплаквания от въпросното нпц, ще отворя репорт-а.
P.S: Най-вероятно проблема е в героят.

**Comment by Herflik** [comment]
NPC'то все още липсва и не се вижда от играчите , като проблема явно не е в Phasemask ..
Ето Trinity issue  по  въпроса - https://github.com/TrinityCore/TrinityCore/issues/10106   §  
предполагаем fix - https://github.com/raczman/TrinityCore/commit/418e9d9b61ebeacf25fb058b0f0f95cd103aa9da .
