### ISSUE TITLE
Quest:  Thalorien Dawnseeker

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#53]
Remnants of Quel'Delar .. последният куест от тази серия не работи . http://www.wowhead.com/quest=24535/thalorien-dawnseeker

NPC-то може да се hackfix-не предполагам, като се направи така че да дава http://wotlk.openwow.com/spell=70265 на всеки които говори с него.

**Comment by FALL1N1** [comment]
Оправен.

**Comment by Warglaive** [comment]
Отварям наново репорт-а за да не пиша друг и го редактирам.

**Comment by Warglaive** [comment]
Все още не работи.
