### ISSUE TITLE
Quest:Blowing Hodir's Horn

### ISSUE THREAD

**Issue by cvasilev** [Warglaive/DragonFireOriginal-3.3.5#531]
Мобовете са там, но след като ги убиеш маркираш трупа надуваш хорна и не се случва нищо... Не ги зачита. http://www.wowhead.com/quest=12977/blowing-hodirs-horn

**Comment by cvasilev** [comment]
Куеста може да бъде изпълнен, на всеки около 10 моба някак си един моб бива отчетен и така криво ляво куеста може да се каже че работи.За около 2 часа циклене се изпълнява.

**Comment by FALL1N1** [comment]
http://prntscr.com/7o3cbu
Кода му е ОК, убивай тези мобове.
