### ISSUE TITLE
Quest chain:[Scarlet Subterfuge], [In Dreams]

### ISSUE THREAD

**Issue by Phyorax** [Warglaive/DragonFireOriginal-3.3.5#532]
[Scarlet Subterfuge](http://wotlk.openwow.com/quest=5862) от [Myranda the Hag](http://wotlk.openwow.com/npc=11872), quest-а работи, но евента след него не започва, а без него не може да заработи quest-a от [Taelan Fordring](http://wotlk.openwow.com/npc=1842) - [In Dreams](http://wotlk.openwow.com/quest=5944) . Втория куест го взимам, но Taelan си седи на едно място и не тръгва. Ето по-ясен пример - https://www.youtube.com/watch?v=aHrFZgJt3Zg

**Comment by FALL1N1** [comment]
И 2-та са авто, оставям това за бъдещ фикс (трябва да се пренапише).
ref: https://bitbucket.org/mangoszero/scripts/commits/00ffce187c8119d3ec203a9d9cf8a292dc8e72af
