### ISSUE TITLE
NPC: Thrall [Old Hillsbrad Footh...]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#534]
http://wotlk.openwow.com/npc=17876
Проблема е, че NPC-тата които заобикалят въпросното NPC, го убиват преди играч да успее да стигне до него и целият дънгеон става неизползваем.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Проблема може би е оправен ( инса може да се минава ), NPC-тата около Thrall НЕ го бият, но той си ги налага.
