### ISSUE TITLE
Naxxramas : Thaddius { bug }

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#535]
След като се убият Feugen http://www.wowhead.com/npc=15930/feugen и Stalagg http://www.wowhead.com/npc=15929/stalagg и ако евентуално се умре на боса Thaddius http://www.wowhead.com/npc=15928/thaddius не може да се направи друг опит тъй като Thaddius няма таргет ,а Feugen и Stalagg не са реснати. :)

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
ок е!
