### ISSUE TITLE
Item: Alchemist's Cache 

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#537]
Не се отваря торбата Alchemist's Cache дори и да имаш макс алхимия ,която пада от Freya http://www.wowhead.com/item=46110/alchemists-cache . :crying_cat_face: :crying_cat_face:

**Comment by Ritokoko** [comment]
Дори в момента няма лоот самият бос

**Comment by FALL1N1** [comment]
test
