### ISSUE TITLE
Achievement [ High Learning ] 

### ISSUE THREAD

**Issue by drmls** [Warglaive/DragonFireOriginal-3.3.5#538]
http://www.wowhead.com/achievement=1956/higher-learning 

The Schools of Arcane Magic - Enchantment - http://www.wowhead.com/object=192713/the-schools-of-arcane-magic-enchantment ; Няма я.

**Comment by Pavslav** [comment]
The books are on spawn timers anywhere from 3 hours to 4 hours
Each book only spawns in one location (so once you find it you do not need to keep checking that location)
Book spawn times are shared with non-achievement books (so you may see a book spawn and it will not be the one you need)
!!==>>>Each location seems to have 2-3 other books (non-achievement) which spawn in that location (randomly)
If you read the book it will disappear within 3min (resetting the spawn timer)
If you do not read the book it will disappear within 5min (resetting the spawn timer)
If an achievement book does spawn, more than one player can read the book and get the credit for reading it. (if they read it within 3min of the first person who read it)

**Comment by Warglaive** [comment]
Не се spawn-ва.

**Comment by Warglaive** [comment]
spawned.
