### ISSUE TITLE
Pit of Saron HEROIC  - Ick (2-nd Boss) - Explosive Barrage (Spell)

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#539]
Втoрият бос в Pit of Saron (САМО на HEROIC mode) Ick има спел, който не работи. Въпросната магия е Explosive Barrage (http://www.wowhead.com/spell=69263/explosive-barrage).
Ето и снимка по време на самия файт: http://prntscr.com/7nxgjb

**Comment by FALL1N1** [comment]
Работи си.
