### ISSUE TITLE
Reputation "At War" problem

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#540]
Когато дадена репутация ( Frenzyheart примерно ) е Hated http://prntscr.com/7o1gmj 
трябва да има отметка на "At war" иначе NPC-тата немогат да се бият, те атакуват, но неможе да бъдат атакувани.
Проблема е глобален затова слагам висок приоритет.

**Comment by FALL1N1** [comment]
#447
