### ISSUE TITLE
Quest :Tools of War "Honorary Frenzyheart" 

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#542]
Нпс-то http://www.wowhead.com/npc=29146/vekgar трябва да предостави на играчите http://www.wowhead.com/quest=12759/tools-of-war но липсва и не могат да си направят ачиевемента http://www.wowhead.com/achievement=961/honorary-frenzyheart

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/236
