### ISSUE TITLE
NPC's: Time-Lost Proto Drake, Vyragosa, Skoll

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#543]
http://wotlk.openwow.com/npc=32491
Въпросното NPC каства http://wotlk.openwow.com/spell=61084
и почти не се движи, просто каства и стой на едно място.

Също така мисля, че се spawn-ва винаги или то или http://wotlk.openwow.com/npc=32630
моля да се погледне.
NPC-то пуска маунт, който се предполага че трябва да е изключително рядък.

Skoll също не се движи.
http://wotlk.openwow.com/npc=35189

**Comment by FALL1N1** [comment]
Нищо им няма.
