### ISSUE TITLE
Boss : Valithria Dreamwalker Icecrown Citadel

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#544]
http://www.wowhead.com/npc=36789/valithria-dreamwalker При този бос трябва на определено време да пуска http://www.wowhead.com/spell=71196/dream-slip така наречените портали,но след като поднови порталите горе в измерението Емерал Дреам не се рефрешват Dream Cloud -Сверите от които се взема бонус хеалинг .

**Comment by Warglaive** [comment]
Надявам се да си сигорен, защото когато аз тествах подобен проблем не намерих.

**Comment by Pavslav** [comment]
https://github.com/DragonFire/3.3.5/issues/504

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Крашва от топките за хеалинга.

**Comment by FALL1N1** [comment]
fixed
