### ISSUE TITLE
Boss : Sindragosa Icecrown Citadel

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#545]
http://www.wowhead.com/npc=36853/sindragosa При този бос трябва да пуска два http://www.wowhead.com/spell=69712/ice-tomb но пуска само един в първа фаза.Другото което е в последната фаза трябва да пуска марка на един играч от раида http://www.wowhead.com/spell=70126/frost-beacon и след това да стане на http://www.wowhead.com/spell=70157/ice-tomb. Но то пуска на двама и дори единият от тях е танка понякога.

**Comment by FALL1N1** [comment]
Test

**Comment by Warglaive** [comment]
Евейдва винаги, неможе да се пулне.

**Comment by FALL1N1** [comment]
Оправено!

**Comment by Warglaive** [comment]
To be tested.
