### ISSUE TITLE
Event: Kalu'Ak Fishing Derby/STV Fishing Extravaganza

### ISSUE THREAD

**Issue by JazzBG** [Warglaive/DragonFireOriginal-3.3.5#547]
За съботния евент в Даларан, той изобщо не се стартира. http://www.wowhead.com/npc=38294/elder-clearwater не се показва в столицата 5минути (13:55 ST) преди началото на евента (14:00 ST). Щом NPC го няма едва ли има смисъл да се коментира улова на въпросната риба.
Относно неделния евент в STV, отново в 14:00 ST NPC (http://www.wowhead.com/npc=15077/riggle-bassbait) не се показва и липсват School of tastyfish от които се добиват необходимите 40 бройки.

**Comment by AnTOLI** [comment]
В даларан работи сега го минах.

**Comment by FALL1N1** [comment]
test
