### ISSUE TITLE
Skadi the Ruthless - Utgarde Pinnacle

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#550]
Боса http://www.wowhead.com/npc=26693/skadi-the-ruthless не слиза когато се пускат копията,няма анимация ,че въобще се мятат. Възможно е проблема да е при смесена група от али и хорде.

**Comment by Ritokoko** [comment]
Не се получава и с несмесени групи .Ходихме само алианси но пак няма анимация на харпуните.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Отново е така боса .Няма анимация на харпуните и не може да се свали от Дракона.

**Comment by FALL1N1** [comment]
Нямаха таргет харпуните, опитайте отново.

**Comment by Chillie** [comment]
Оправен е.

**Comment by AnTOLI** [comment]
Боса пак е бъгав не лети.

**Comment by Warglaive** [comment]
Ще го тествам довечера.
