### ISSUE TITLE
Проблем с Twilight Corrupter ...

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#551]
За куеста (The Nightmare's Corruption) трябва Twilight Corrupter http://www.wowhead.com/npc=15625/twilight-corrupter който се намира в  Duskwood-Twilight Grove . Проблема е ,че когато бутне играчите ги вкарва в графиката .

**Comment by Warglaive** [comment]
Вече се вижда от играчите.
