### ISSUE TITLE
Quest : [Slim Pickings]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#555]
http://wotlk.openwow.com/quest=12075 Този куест не работи трябва да се отиде в пещерата Ice Heart Cavern в Dragonblight и да се таргетне Нпс-то http://www.wowhead.com/npc=26809/ravaged-crystalline-ice-giant и да има торбичка все едно го лоотваш и ти дава куест итема http://wotlk.openwow.com/item=36765

**Comment by AnTOLI** [comment]
FIX  https://github.com/TrinityCore/TrinityCore/commit/74d57fa1c0e90847dc3232b95e4e037e7bc3ba61
