### ISSUE TITLE
Transfercheta

### ISSUE THREAD

**Issue by Min4AKK** [Warglaive/DragonFireOriginal-3.3.5#556]
Добър вечер!Относно промените и новостите в сървъра някой беше казал,че ще има Трансфер на герои от други сървъри.Някой има ли идея кога ще бъде налична тази опция и как точно ще се извърши?Не знам дали е правилното място за питане,но виждам,че тук се споделят в общи линии нещата,които вълнуват хората.

**Comment by Warglaive** [comment]
:D Тук се споделят бъгове/ проблеми по играта, няма точна дата когато е готово - ще се пусне.
