### ISSUE TITLE
Ogri'la (Reputation)

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#557]
Проблемът с репутацията е, че какъвто и куест да бъде минат успшено, той дава само 10% от репутацията, която нормално би трябвало да дава. Например даден куест трябва да дава 350 репутация. В момента дава 35, а не 350.
Линк към репутацията: http://www.wowhead.com/faction=1038/ogrila

**Comment by GalaxyWoW** [comment]
Пробвах го вече си работи както трябва

**Comment by Warglaive** [comment]
ок.
