### ISSUE TITLE
Sunwell Plateau (Raid) - Kalecgos (Boss) & Felmyst (Boss)

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#561]
1). Kalecgos (http://www.wowhead.com/npc=24850/kalecgos)
Проблемът е, че не се появяват портали, в които играчите да влизат, за да могат да убият Sathrovarr the Corruptor (http://www.wowhead.com/npc=24892/sathrovarr-the-corruptor). Ако Sathrovarr the Corruptor  не бъде убит, битката си продължава вечно - Kalecgos си трупа стакове Crazed Rage (http://www.wowhead.com/spell=44806/crazed-rage), но не напада никого. Отделно, че на приблизително 9 000 живот Kalecgos  получава Banish (http://www.wowhead.com/spell=136466/banish) и не може да бъде убит от рейда. Получава се така, че нито играчите могат да убият Kalecgos, нито той може да убие играчите и заради стената няма друг изход от рейда освен Hearhstone.
Това за нещата, които липсват:
1. Spectral Blast (http://www.wowhead.com/spell=44866/spectral-blast)
2. Spectral Realm (http://www.wowhead.com/spell=46021/spectral-realm)
3. Spectral Exhaustion (http://www.wowhead.com/spell=44867/spectral-exhaustion)

2). Felmyst (http://www.wowhead.com/npc=25038/felmyst#abilities)
След като 2-рия бос, Brutallus (http://www.wowhead.com/npc=24882/brutallus), бъде убит, трябва да се появи 3-тия бос - Felmyst. Felmyst се появява, но се вижда само и единствено от <GM>. Дори при килването й с .die и с последващ .respawn, играчите пак не я виждат. Spawn-ване на нов бос Felmyst също не помага - пак се вижда само и единствено от <GM>.
Хубавото е, че поне след като Felmyst бъде убита от Game Master, огнената бариера, която пречи на играчите да продължат, се маха и те спокойно могат да си продължат с рейда.

**Comment by FALL1N1** [comment]
1) fixed
2) fixed
~~
test
