### ISSUE TITLE
Temple of Ahn'Qiraj (40 players Raid) - Battleguard Sartura (Boss)

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#562]
Проблемът с Battleguard Sartura (http://www.wowhead.com/npc=15516/battleguard-sartura) е, че бие прекалено много dmg, както на Auto Attack (130 000, като 60 000 са резистнати), така и със спелове.

**Comment by FALL1N1** [comment]
Boss-a си е ок, просто не трябва да се танква от DPS. :)
