### ISSUE TITLE
Trial of the Crusader (10 Normal & Heroic, 25 Normal & Heroic) - The Northrend Beasts (Boss Encounter)

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#563]
Проблемът е следният:
Ако рейдът умре по време на битката с Acidmaw & Dreadscale, би трябвало всичко да започва отначало - тоест отново да стартират евента и рейдът пак да се изправи срещу Gormok the Impaler. В случая проблемът е, че след като хората се вземат и влязат в инстанцията, там ги очаква Acidmaw (http://www.wowhead.com/npc=35144/acidmaw), който си е напълно функциониращ бос с умения, които използва. Не би трябвало да е така.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Проблема все още го има.

**Comment by FALL1N1** [comment]
fixed
