### ISSUE TITLE
Realm First Naxx,OS,Ulduar i t.n

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#566]
Гледам, че сте реснали реалм фърста на Йог Сарон,нема лошо.Искате от скрипнат бос да се зима ачивмънта,нема ядове.Ама с тая логика треа да реснете сички реалм фърст от рейдове,щото нито Обсидан Санктум,нито Наксрамас,нито ТоК както и другите не работеха както трябва.Пиша тука,че в играта никой не ми отговаря.

**Comment by FALL1N1** [comment]
Тези които са кодирани се рескат автоматично при надвишаване на максимума (25) допустими постижения. Когато кодираме и останалите (Naxx,OS,ToC......) те ще бъдат рестартирани автоматично от ядрото, не зависи от нас.
