### ISSUE TITLE
Akama [Black Temple] Event.

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#568]
http://wotlk.openwow.com/npc=23191
Проблема е, че неможе да се цъкне на http://prntscr.com/7qqsjb
за да се страртира евент-а.

**Comment by FALL1N1** [comment]
Атакувай директно сянката му.

**Comment by Warglaive** [comment]
Не е възможно, няма таргет освен в GM mode on.

**Comment by FALL1N1** [comment]
fixed
