### ISSUE TITLE
Halls of Reflection : бъг в последна фаза.

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#573]
Не протича диалога между Lich King и Lady Jaina Proudmoore/Lady Sylvanas Windrunner .По този начин не може да се стартира евента и да се осъществи придвижването.

**Comment by Warglaive** [comment]
Тествах го, след като се минат 10-те вълни и трябва да се стигне до http://prntscr.com/7q8ska
Където Sylvanas трябва да е sap-нала Lich King-а и след което да почне да се бяга, НО нищо не се случва просто седят.

**Comment by FALL1N1** [comment]
test

**Comment by Chillie** [comment]
Диалога протича,но след като се убие първата вълна с траш Lady Jaina Proudmoore/Lady Sylvanas Windrunner не иска да чупи стената,че да се продължи напред и по този начин Lich King-a я трепи и трябва отначало. http://prntscr.com/7rgilg

**Comment by AnTOLI** [comment]
Няма кораб и лоот няма.

**Comment by FALL1N1** [comment]
test
