### ISSUE TITLE
Rep: Ravenhold/Syndicate

### ISSUE THREAD

**Issue by GalaxyWoW** [Warglaive/DragonFireOriginal-3.3.5#574]
http://www.wowhead.com/faction=349/ravenholdt

при убийството на NPC от Syndicate (http://www.wowhead.com/faction=70/syndicate) би трябвало да дава 5 rep кум Ravenhold и да сваля от Syndicate. Проблема е, че дава 349 към Ravenhold и вместо да сваля от Syndicate дава 70 към тях.

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
При убийството на NPC от Syndicate (http://www.wowhead.com/faction=70/syndicate)
дава 70 към Syndicate ( трябва да сваля )
И дава 34 към Ravenholdt ( Мисля, че е точно).

**Comment by Warglaive** [comment]
Проблема при ravenholdt е, че при убииство на NPC от ravenholdt трябва да намаля реп-а а в момента увеличава. http://prntscr.com/7r9u33
http://wotlk.openwow.com/faction=349

**Comment by Chillie** [comment]
Още си е така ;д

**Comment by FALL1N1** [comment]
#447
