### ISSUE TITLE
Boss :Yogg-Saron Ulduar

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#576]
http://wotlk.openwow.com/npc=33288 .Първа фаза трябва да убиеш 7-9 моба 

http://www.wowhead.com/npc=33988/immortal-guardian#abilities за да свалят кръвта на Сара 

http://www.wowhead.com/npc=33134/sara за да пусне втора фаза но сега се получава още от първия моб.

Когато влезе втора фаза трябва след като се убият пипалата от фаза две да се отворят портали и трябва да се влезе в тях но не ги отваря за да влезеш в долното измерение.
Дефакто самият бос прескача почти цялата втора фаза.

А и проблема с боса е че когато умрем на него http://www.wowhead.com/npc=33988/immortal-guardian#abilities остават EVADE и не може да се бият и след това като почнем втори опит на Боса прескача първа фаза и почва да спами само такива мобове без да продължава битката с фазите напред.

**Comment by FALL1N1** [comment]
fixed
