### ISSUE TITLE
[Rep] Alliance Vanguard

### ISSUE THREAD

**Issue by GalaxyWoW** [Warglaive/DragonFireOriginal-3.3.5#578]
![untitled](https://cloud.githubusercontent.com/assets/12119696/8632964/f4118118-27bb-11e5-89d4-e59ddc7c2047.jpg)

След релог пак се появи "At War", до колкото знам "Horde Expedition" също не трябва да се вижда в таба на "Alliance"

проблема идва от промяна на "flags" в таблицата "character_reputation" където:

faction=1037 следва да има flags=137, но в случая съм сигурен, че и при вас е станало 139 за което нямам обяснение, предполагам че е от смесеното BG от Horde и Ally, което трябва да се тества.

При мене го оправих по следния начин

``` javascript
UPDATE `character_reputation` SET `flags`='137' WHERE `faction`=1037;
```

но това ще смени и flaga на Hordite, които използват 'flags' 6 към "Alliance Vanguard" както би трябвало да е и с Ally към "Horde Expedition" с който се скрива репутацията от бара, но след релог flags си става 6 (поне при мене)

2 = FACTION_FLAG_AT_WAR
4 = FACTION_FLAG_HIDDEN

за сега проблема е само при герой Hellygun, така че може да се използва

``` javascript
UPDATE `character_reputation` SET `flags`='137' WHERE `guid`=??? AND `faction`=1037`;
```

само да се напише "guid" а на героя вместо ???

**Comment by FALL1N1** [comment]
test

**Comment by GalaxyWoW** [comment]
Готово БЛАГОДАРЯ
