### ISSUE TITLE
Boss:Freya -Freya's Gift Ulduar 10/25

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#579]
http://www.wowhead.com/object=194324/freyas-gift След убийството на Фрея сандъка не се явява.

**Comment by FALL1N1** [comment]
Няма как да не се призовава.. лично съм бил там и си работи

**Comment by Chillie** [comment]
Няма никакъв сандък от 10/25 .

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Все още няма сандък.

**Comment by Ritokoko** [comment]
Няма сандък до момента на 10 и 25 трудност.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Сандък има само ако са мъртви всички елдери.

**Comment by Ritokoko** [comment]
Вече и тогава няма сандък.
