### ISSUE TITLE
Borean Tundra , quests : "The Plains of Nasam" . "Coward Delivery... Under 30 Minutes or it's Free"

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#58]
и двата куеста не работят..
http://www.wowhead.com/quest=11711/coward-delivery-under-30-minutes-or-its-free
http://www.wowhead.com/quest=11652/the-plains-of-nasam

**Comment by FALL1N1** [comment]
Оправени.
