### ISSUE TITLE
Achievement : Take Out Those Turrets (10 player)

### ISSUE THREAD

**Issue by Moonlord** [Warglaive/DragonFireOriginal-3.3.5#582]
За изпълнение на ача ( http://www.wowhead.com/achievement=2909/take-out-those-turrets-10-player ), са нужни двама играча. Единият трябва да се качи на оръдието( http://www.wowhead.com/npc=33067/salvaged-siege-turret#abilities ) на демолишер ( http://www.wowhead.com/npc=33109/salvaged-demolisher ) и да използва спелла ( http://www.wowhead.com/spell=64414/load-into-catapult ), а другия играч трябва да го изстреля с демолишера, чрез ( http://www.wowhead.com/spell=62324/throw-passenger ) върху босa - ( http://www.wowhead.com/npc=33113/flame-leviathan ) .

Проблема е, че играча се зарежда в демолишера, но втория играч не може после да го изстреля.

П.С. Когато се качи втория играч върху боса, той трябва да убие "Leviathan Defense Turret" - ( http://www.wowhead.com/npc=33142/leviathan-defense-turret ), но това няма как да се тества на този етап.

**Comment by AnTOLI** [comment]
Да спела Throw Passenger на демолишера не се активира за да изстреля на боса.

**Comment by FALL1N1** [comment]
hackfix

**Comment by Ritokoko** [comment]
Дава го .
