### ISSUE TITLE
Quest: Shred the Alliance

### ISSUE THREAD

**Issue by cvasilev** [Warglaive/DragonFireOriginal-3.3.5#587]
http://www.wowhead.com/quest=12270/shred-the-alliance Може да се карат, като се докарат в каручката която трябва да се върнат не може. Казва requres basecamp. Това е проблема. Не зачита мястото за да се върнат.

**Comment by FALL1N1** [comment]
fix

**Comment by Ritokoko** [comment]
Проблема е същия като информацията дадена по на горе за репорта.
