### ISSUE TITLE
You don`t meet requirements for quest.

### ISSUE THREAD

**Issue by cvasilev** [Warglaive/DragonFireOriginal-3.3.5#589]
Прилагам скреен за да се види след връщането на кой куест се получава. Това е поредицата за Гризли хилс арена. 
![wowscrnshot_071315_211802](https://cloud.githubusercontent.com/assets/13100388/8657319/a69dbb18-29a5-11e5-9841-e762fde5db41.jpg)

**Comment by Warglaive** [comment]
Quest-a за който дава въпросното съобщение е:
http://www.wowhead.com/quest=12422/tactical-clemency

**Comment by FALL1N1** [comment]
test
