### ISSUE TITLE
The Violet Hold

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#591]
http://www.wowhead.com/zone=4415/the-violet-hold .Порталите на инстанцията активират само два боса и http://www.wowhead.com/npc=31134/cyanigosa а попринцип трябва да са три боса и "Cyanigosa"

**Comment by FALL1N1** [comment]
Пренаписана.

**Comment by Warglaive** [comment]
To be tested.
