### ISSUE TITLE
[Raid] Black Temple - Reliquary of Souls

### ISSUE THREAD

**Issue by GalaxyWoW** [Warglaive/DragonFireOriginal-3.3.5#594]
Евента за боса не тръгва.

http://www.wowhead.com/npc=23418/essence-of-suffering
http://www.wowhead.com/npc=23419/essence-of-desire
http://www.wowhead.com/npc=23420/essence-of-anger

**Comment by Pavslav** [comment]
https://github.com/DragonFire/3.3.5/issues/377
