### ISSUE TITLE
Quest : All Hail Roanauk! 

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#597]
Като вземеш куеста от Overlord Agmar (26379) той си седи на мястото не отива при Roanauk Icemist (26810) ,че да се пусне евента. http://prntscr.com/7u5a85 Като се кликне за диалог пак нищо не става.  http://www.wowhead.com/quest=12140/all-hail-roanauk
Куеста е от поредицата за Veteran of the Wrathgate http://www.wowhead.com/achievement=547/veteran-of-the-wrathgate  :sun_with_face:  :balloon:

**Comment by FALL1N1** [comment]
fixed
