### ISSUE TITLE
Quest :Saving Yenniku ...

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#598]
Направен е ауто по някакъв странен начин http://wowwiki.wikia.com/Quest:Saving_Yenniku  не дава   http://wowwiki.wikia.com/Soul_Gem , а без него не може . Клипче https://www.youtube.com/watch?v=BcRcYes3lbU . :smiley_cat:

**Comment by FALL1N1** [comment]
deprecated; не се използва вече.
