### ISSUE TITLE
NPC: Apothecary Tepesh <Alchemy & Poison Supplies>

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#599]
http://www.wowhead.com/npc=29339/apothecary-tepesh
Спалннал съм го, колега ти си наред - @JunkyBulgaria 
( Не продава нищо, неможе да се отвори ( не е вендор ))
- @Warglaive

**Comment by Warglaive** [comment]
Дай ми снимка къде точно трябва да бъде spawn.

**Comment by Warglaive** [comment]
http://www.wowhead.com/npc=29339/apothecary-tepesh
Спалннал съм го, колега ти си наред  - @JunkyBulgaria 
( Не продава нищо, неможе да се отвори ( не е вендор ))

**Comment by AnTOLI** [comment]
Само трябва да е тама не трябва да е  вендор.
![wowscrnshot_072415_171925](https://cloud.githubusercontent.com/assets/2588705/8876431/6a24fd6e-3228-11e5-8cf7-92f59cce316a.jpg)

**Comment by Warglaive** [comment]
rdy, не трябва да е вендор.

**Comment by Warglaive** [comment]
The subject of this article or section was part of the Scourge Invasion, a world event that heralded the opening of Naxxramas in patch 1.11 or for the opening of Northrend. Once the world event has run its course, this will no longer be available.

Мисля, че не трябва да го има, ако някои е сигорен че трябва да го има на въпросното място, моля да остави коментар - защо трябва да го има.
