### ISSUE TITLE
[Quest] Blending In

### ISSUE THREAD

**Issue by Madleine** [Warglaive/DragonFireOriginal-3.3.5#6]
Както казва куестът, трябва да се позлва наметало и да се обиколят 3 кули в Бореан Тундра. Наметалото действа - влиза се в друго измерение, но когато се стигнат кулите и се влезе в тях, не отчита, че са изследвани, а трябва.
http://www.wowhead.com/quest=11633

**Comment by FALL1N1** [comment]
Оправен!

**Comment by AnTOLI** [comment]
Не работи не ги отчита  3 кули за куеста.
https://github.com/TrinityCore/TrinityCore/commit/057bdfdf4f5d0e38ff6ec8c279c963e9af6825a8
