### ISSUE TITLE
Missing Npc Jaxxil Sparks <Holiday Fireworks Vendor>

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#600]
http://wotlk.openwow.com/npc=8121 Липсва Нпц то в Ratchet.

**Comment by Chillie** [comment]
Ти да не обикаляш навсякъде да търсиш липсващи ? :laughing: :laughing: :laughing:

**Comment by AnTOLI** [comment]
Кво друго се прави тука. :laughing:

**Comment by Warglaive** [comment]
Spawned.
