### ISSUE TITLE
Missing Npc Keyanomir and Nimrida <Keyanomir's Minion>

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#605]
Липсват 2 Нпц http://wotlk.openwow.com/npc=18231 и http://wotlk.openwow.com/npc=18232 в Silvermoon City.

**Comment by Warglaive** [comment]
Има ги!Проверявай по-добре преди да репорваш.

**Comment by AnTOLI** [comment]
Няма ги. :)
