### ISSUE TITLE
Quest : Turning Point 

### ISSUE THREAD

**Issue by Chillie** [Warglaive/DragonFireOriginal-3.3.5#606]
http://www.wowhead.com/quest=10507/turning-point 
Socrethar http://www.wowhead.com/npc=20132/socrethar. :hamster:  :chicken:  :laughing:  

@Warglaive - Проблема е, че предмета http://wotlk.openwow.com/item=30259 неможе да се ползва върху NPC-то. ( invalid target )

**Comment by FALL1N1** [comment]
fixed
