### ISSUE TITLE
Quest To Legion Hold

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#608]
http://wotlk.openwow.com/quest=10596 Не работи позвам Куест итема http://wotlk.openwow.com/item=30638 но не се случва нищто не се статирва диалога.
Вероятно решение. https://github.com/raczman/TrinityCore/commit/b930075c8488511f6340da35b479bb947cb72b0d

**Comment by FALL1N1** [comment]
fixed
