### ISSUE TITLE
Brew of the Year vendor

### ISSUE THREAD

**Issue by NuclearPower** [Warglaive/DragonFireOriginal-3.3.5#611]
Вендорът е бъгав от 1 месец, защото миналият месец продаваше Draenic Pale Ale (алкохола, който е за месец август) и изобщо не премина през Stranglethorn Brew (който е за месец юли). Следях го през 4-5 дни дали сменя през целия юли, но това не стана през цялото време. Затова моля всякакви обвинения, че не съм гледал достатъчно добре или че съм пропуснал и че не разбирам за какво става дума да бъдат запазени и тотално заличени. По този начин achievement-а се прецаква заради неоправен вендор когато му е било времето. Моля този алкохол (Stranglethorn Brew) да ми бъде компенсиран по някакъв начин.

**Comment by Warglaive** [comment]
Добре, вендора найстина е бъгав, затова адвам на ръка всичко.
Ето така, ще са:
January      [Wild Winter Pilsner]
February  [Izzard's Ever Flavor]
March   [Aromatic Honey Brew]
April    [Metok's Bubble Bock]
May      [Springtime Stout]
June     [Blackrock Lager]
July     [Stranglethorn Brew] 
August   [Draenic Pale Ale] 
September    [Binary Brew]
October      [Autumnal Acorn Ale] 
November     [Bartlett's Bitter Brew] 
December     [Lord of Frost's Private Label]

А колкото до теб, да - изпуснал си нещо, защото лично съм го правил тази година.Ще ти дам пример и с играч:
http://prntscr.com/85lont

**Comment by Warglaive** [comment]
Ако имаш други въпроси / проблеми - тикет в играта, github е за докладване на бъгове.

**Comment by NuclearPower** [comment]
Никой не е казал, че аз не съм направил всички месеци до този момент. Казах само, че нямаше как да направя САМО юли понеже не се продаваше алкохола (Stranglethorn Brew), за което аз нямам никаква вина. Ако се интересува някой кога съм започнал да го правя - декември 2014 (да това си е мой проблем вече). Не съм изпуснал месец до сега - всичко вървеше по мед и масло. Докато не дойде юли ... седиш и чакаш ... и нищо. Не беше нужно дори да ги линкваш кой от всичките алкохоли за кой месец е ... всички имаме wowhead и предполагам не сме малоумни. В края на деня обаче проблемът отново не е решен. Може да ми се изпрати писмо по пощата, съдържащо Stranglethorn Brew .... maybe ?!?! Име на герой - Stormbrought.

**Comment by Warglaive** [comment]
Изпуснал си един месец, няма как да ти го пратиме.Явно миналите колеги са го добавили по-рано.
