### ISSUE TITLE
Wintergrasp Timer Bug

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#612]
Не работи не показва кога е бг то почва показва само (In Progress).
Намерих фикс дано да става https://github.com/robinsch/TrinityCore/commit/7fbd035620bfc5813a3366b9cb2f91deb7a216aa

**Comment by Warglaive** [comment]
http://prntscr.com/8e31zs моля?
http://prntscr.com/8e32ff

**Comment by AnTOLI** [comment]
![c8c04792-1663-11e5-921f-04292791d185](https://cloud.githubusercontent.com/assets/2588705/9743120/5c76f0be-566d-11e5-8840-606182cfd3fe.png)

**Comment by Warglaive** [comment]
http://prntscr.com/8e35sb

**Comment by AnTOLI** [comment]
Не в самата зона на Бг то. А извън  не показва времето . Като влезеш  БГ много ясно че го покаже излезаш офф и пак така става In Progress .

**Comment by FALL1N1** [comment]
Той е на GM Island?

**Comment by AnTOLI** [comment]
На мен ми показва In Progress и на други хора които се са ходили до WG им показва това.

**Comment by Warglaive** [comment]
Не е от значение, дори и да има проблем то се появява на моменти.
