### ISSUE TITLE
Dalaran  Minigob - World Event 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#613]
Липсва евента които се провежда в Даларан с Нпц то Minigob Manabonk http://wotlk.openwow.com/npc=32838 .
Fix https://github.com/TrinityCore/TDB_4.3.4_NLU/blob/master/old/updates_06/012_2014_07_19_11_world_misc.sql

**Comment by FALL1N1** [comment]
fixed

**Comment by AnTOLI** [comment]
Нпц то излиза и не си използва  магията към играч излиза и се скрива като цяло http://wotlk.openwow.com/spell=61834.
Но работи показва се.

**Comment by Warglaive** [comment]
Нов репорт.
