### ISSUE TITLE
Npc Felendren the Banished missing sound

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#614]
Липсва звука на Нпц то http://www.wowhead.com/npc=15367/felendren-the-banished
Фикс https://github.com/TrinityCore/TrinityCore/commit/2e29501d8d3a3fd4cedb3b1f1d1669e969035bfe

**Comment by FALL1N1** [comment]
Ти сериозно ли..?

**Comment by FALL1N1** [comment]
fixed

**Comment by AnTOLI** [comment]
Пак си е така без звук.

**Comment by FALL1N1** [comment]
Все тая, не е болка за умиране.
