### ISSUE TITLE
Emblem's 

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#615]
Има проблем с обменянето на емблеми от http://wotlk.openwow.com/item=47241 към http://wotlk.openwow.com/item=45624 и някои хора не могат да си закупят някои предмети с по ниските емблеми .Могат да се закупят но изискват по голям брои http://wotlk.openwow.com/item=47241 от колкото са си с нормалните емблеми.

**Comment by FALL1N1** [comment]
(reminder)
71263 - 71275

**Comment by FALL1N1** [comment]
Кои вендори?

**Comment by Ritokoko** [comment]
За хорди http://wotlk.openwow.com/npc=35495 липсва само обменната емблема ,http://wotlk.openwow.com/npc=33963 " при този вендор всички итеми се закупуват с http://wotlk.openwow.com/item=47241 а трябва да са с http://wotlk.openwow.com/item=45624 ".За алианс http://wotlk.openwow.com/npc=35494 " липсва обменната емблема.

**Comment by FALL1N1** [comment]
blagodarsko
