### ISSUE TITLE
Brewfest  Event

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#618]
1. Липсват object http://wotlk.openwow.com/object=189990 от които се взима куеста http://wotlk.openwow.com/quest=12192.
   2, Не работи куеста http://wotlk.openwow.com/quest=11120  липсват Нпц та с които се прави http://wotlk.openwow.com/quest=11120 http://wotlk.openwow.com/npc=23529 http://wotlk.openwow.com/npc=23530.
2. Не се е реснало Куеста http://wotlk.openwow.com/quest=12194 за http://wotlk.openwow.com/item=33016.
3. Липсва куеста http://wotlk.openwow.com/quest=11408 от Нпц то.
4. Боса го няма в инса http://wotlk.openwow.com/npc=23872.
5. Нпц то http://wotlk.openwow.com/npc=24510  не продава  http://wotlk.openwow.com/item=33976 
   7, Липсва Куеста  http://www.wowhead.com/quest=11487/the-best-of-brews които се взима от боса http://www.wowhead.com/npc=23872/coren-direbrew

**Comment by Warglaive** [comment]
Object-a e spawn.
Слоновете са на място.
Боса е на място.
Quest-а си пада от боса.
Вендора който продава козите - може и да ги добавиме, ще видим.

**Comment by AnTOLI** [comment]
Боса не е на точното място при влизане през РДФ.
При правене на РДФ не дава наградата на всички http://wotlk.openwow.com/quest=25483 Ако може да се добави в некои Нпц Куеста..
