### ISSUE TITLE
 [Get Kraken!] Quest

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#619]
http://wotlk.openwow.com/quest=14108 Не работи тази задача.След като вземеш задачата от http://wotlk.openwow.com/npc=35094 трябва да излезеш от палатката и в ляво на нея има http://wotlk.openwow.com/npc=35117 трябва да се качите на този Хипогриф и да ви откара до http://wotlk.openwow.com/npc=34925 след това да хвърлите http://wotlk.openwow.com/item=46954 по http://wotlk.openwow.com/npc=34925 за да ви отчете изтрел и да ви го зачете към задачата.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Отчита ги .Работи
