### ISSUE TITLE
Quest:  [Into The Wild Green Yonder]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#62]
http://www.wowhead.com/quest=13045/into-the-wild-green-yonder
Когато вземеш NPC-то което трябва да върнеш обратно в базата, трябва да го пуснеш с spell от Argent Skytalon(http://www.wowhead.com/spell=56684/drop-off-captured-crusader), но spell-а НЕ работи, дори когато скочиш от дракона и все пак пуснеш Crusader-а, НЕ го отчита.

**Comment by FALL1N1** [comment]
Oprawen!
