### ISSUE TITLE
Traveler's Tundra Mammoth Text Npc 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#620]
Липсвам им текста на Нпц които са на мамута.
Hakmud of Argus <Traveling Trader>  - http://www.wowhead.com/npc=32638
Gnimo <Adventurous Tinker> - http://www.wowhead.com/npc=32638
Drix Blackwrench <The Fixer> - http://www.wowhead.com/npc=32641
Mojodishu <Traveling Trader>\- http://www.wowhead.com/npc=32642
Fix  https://github.com/TrinityCore/TrinityCore/commit/209a77de3abcc76f43755b71a06c75ba85fcca48

**Comment by AnTOLI** [comment]
Не работи ако е сложен фикса.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Не работи пак.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Пак са си така.
