### ISSUE TITLE
Npc Halls of Stone visuals

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#622]
Липсват им магите на некои Нпц в Halls of Stone,
Fix https://github.com/TrinityCore/TrinityCore/commit/52c3ec664b72a8f7d4d0a883ee9494478d17d694

**Comment by AnTOLI** [comment]
Не работи.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Пак са си така.
