### ISSUE TITLE
Npc Hira Snowdawn missing  every 10 min

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#623]
http://www.wowhead.com/npc=31238/hira-snowdawn#teaches-recipe Нпц то трябва да лети на всеки 10 мин в Даларан.
Fix https://github.com/TrinityCore/TrinityCore/commit/6e39aacdf677fe2cc06be4c9aef20a8291a1a977

**Comment by AnTOLI** [comment]
Не работи все ощте е така Нпц то.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи :+1:
