### ISSUE TITLE
Gundrak Movement Text and Emotes

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#624]
Липсват в инса разни движения на Нпц та тама.
Fix https://github.com/TrinityCore/TrinityCore/commit/bb181327c14e1c696c94686d7daeeea87f3216bc
https://github.com/TrinityCore/TDB_4.3.4_NLU/blob/master/old/updates_07/033_2014_09_18_00_world_gundrak.sql

**Comment by FALL1N1** [comment]
sled restart

**Comment by AnTOLI** [comment]
Не работи нямат движения.

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Пак са си така.
