### ISSUE TITLE
Npc Linda Ann Kastinglow & Arcanist Alec Text 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#625]
Липсва им текста на двете Нпц та в Даларан.
http://www.wowhead.com/npc=32692/arcanist-alec#sounds
http://www.wowhead.com/npc=32687/linda-ann-kastinglow
Fix https://github.com/TrinityCore/TrinityCore/commit/2272c63c3516cef5b465d5980f9ca2b72c5b118b

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи :+1:
