### ISSUE TITLE
Oculus missing spells visuals

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#627]
http://www.wowhead.com/npc=27639/ring-lord-sorceress
http://www.wowhead.com/npc=27640/ring-lord-conjurer
http://www.wowhead.com/npc=28183/centrifuge-core
Липсват на некои мобове спела в инса.
Fix https://github.com/TrinityCore/TrinityCore/commit/791356c27e8ec68a49018009d7d1202d9efea2f5
https://github.com/TrinityCore/TrinityCore/commit/e243df4df92e477509c37ac4fd54e49c71e79cd0

**Comment by AnTOLI** [comment]
Не работи няма им ги спела.

**Comment by FALL1N1** [comment]
тест

**Comment by AnTOLI** [comment]
Не работи пак нямат.
