### ISSUE TITLE
Quest: [A Visit to the Doctor]

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#628]
Не работи липсва евента към куеста http://www.wowhead.com/quest=13152/a-visit-to-the-doctor.
Видео https://www.youtube.com/watch?v=boM-tlXi4RI&hd=1
Fix https://github.com/TrinityCore/TrinityCore/commit/9c61f2ce0c1972cf0f3b06cfcce6ecaef3935945

**Comment by FALL1N1** [comment]
test
