### ISSUE TITLE
Shadowfang Keep BUG.

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#63]
NPC: Deathstalker Adamant( http://www.wowhead.com/npc=3849/deathstalker-adamant )
Отваря вратата в SFK, но веднага след като се отвори се затваря, както и trigger за отваряне на решетките за достигане на самото NPC, за стартиране на евента.

**Comment by FALL1N1** [comment]
[todo], изтриване на решетките @Warglaive
