### ISSUE TITLE
Npc Shadow Channeler cosmetic

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#632]
Липсва дадените нещта на Нпц то http://www.wowhead.com/npc=32262/shadow-channeler .
Фикс https://github.com/TrinityCore/TrinityCore/commit/51ac4872f509f7bad79a3a8bc2a74d946ea1cd68

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи :+1:
