### ISSUE TITLE
Quest:  The Booterang: A Cure For The Common Worthless Peon

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#635]
http://www.wowhead.com/quest=11055/the-booterang-a-cure-for-the-common-worthless-peon Куеста е Ауто направен и не може да се мине, ако може да се премахне ауто то и да се сложи фикса.
Фикс https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/a32793ffd371db0f64d30e8a5dbfd4a58d09ae45

**Comment by FALL1N1** [comment]
fixed

**Comment by AnTOLI** [comment]
Пак си е ауто.

**Comment by FALL1N1** [comment]
sled restart
