### ISSUE TITLE
Instance: Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by Vanx3lzing** [Warglaive/DragonFireOriginal-3.3.5#636]
Има проблем с http://www.wowhead.com/npc=17876/thrall още в замъка почва да атакува нпстата над него а не е пуснат евента за да излезе от клетката.След като пуснем евента да излезе от клетката в мазето той отива взема си оръжията и излиза от замъка за да продължи евента напред но на моста когато се показват четири нпста самият Трал спира на едно място както и четирите нпцта не могат да се качат при него на моста да се атакуват .Все едно има някаква бариера .

**Comment by Vanx3lzing** [comment]
Като цяло на този инст може и да няма проблем защото след няколко опита разбрах че хората които се опитват да го направят не бият четирите нпс-та под моста и Трал влиза в битка с тях и за това остава на мота неподвижен.

**Comment by FALL1N1** [comment]
Трябва да се избият.
