### ISSUE TITLE
Npc emote text Shadowmoon Valley

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#638]
Липсват разни text, SAI, emote, на Нпц та в зоната Shadowmoon Valley (Illidari Point) http://wowwiki.wikia.com/wiki/Illidari_Point.
Фикс https://github.com/TrinityCore/TrinityCore/commit/9c8b56d8f0650017310c944954f1fc1e49a06696#diff-16968f65213eb34e4a54fc0e86e0fa30

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи :+1:
