### ISSUE TITLE
Missing  Meeting stone

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#640]
Липсва Meeting stone камъка за пред входа Vault of Archavon http://www.wowhead.com/zone=4603/vault-of-archavon

**Comment by Ritokoko** [comment]
Поради каква причина мислиш че трябва да има Meeting Stone пред Воа.Не би ли трябвало да си е така както е , които спечели битката "Wintergrasp" той може да влезе в инстанцията .

**Comment by AnTOLI** [comment]
Има написан фикс за това от тринити  коре за това и трябва да има.

https://github.com/TrinityCore/TrinityCore/commit/89c6e5dcf4d8a4168802171b80dca2a3330d2d19

**Comment by FALL1N1** [comment]
перманентно е след WoTLK (т.е в Cataclysm)
