### ISSUE TITLE
Spells Item Underbelly Elixir

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#641]
http://www.wowhead.com/item=44012/underbelly-elixir Не работи не те трансформира в flying wasp от итема http://www.wowhead.com/spell=59831/underbelly-elixir.
При опит изписва (the spell is not available to you)

**Comment by FALL1N1** [comment]
fixed

**Comment by AnTOLI** [comment]
При над 15 взети елексира 1 път не ме трансформира в flying wasp.

**Comment by FALL1N1** [comment]
Това си ти е до късмета.
