### ISSUE TITLE
Missing Object Large Jack-o'-Lantern

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#642]
http://www.wowhead.com/object=186887/large-jack-o-lantern#comments Липсва тиквата която дава  Daily Куеста Smash the Pumpkin http://www.wowhead.com/quest=12155/smash-the-pumpkin#see-also
Видео https://www.youtube.com/watch?v=-IWjF_lEjLk&hd=1

**Comment by FALL1N1** [comment]
По принцип когато се убие headless horseman-а се spawn-ва тази тиква.

**Comment by AnTOLI** [comment]
Не ли като се минат Куестовете в Brill.Durotar.Eversong Woods.Elwynn Forest http://www.wowhead.com/quest=11219/stop-the-fires#comments:id=426083.
Да се покаже да тия места.

**Comment by FALL1N1** [comment]
- вземаш куеста
- конника пали сградите
- гасиш ги
- той слиза и започва малка битка, убивате го
- тиквата се spawn-ва

**Comment by AnTOLI** [comment]
Явно не работи евента които Shade of the Horseman лети из тези места като вземеш куеста.
