### ISSUE TITLE
Shattrath City Npc emote sound

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#646]
Липсват некои нещта в Shattrath City с Нпц то Captain Dranarus http://wotlk.openwow.com/npc=25138  и други.
Фикс https://github.com/TrinityCore/TDB_4.3.4_NLU/blob/master/old/updates_06/012_2014_07_25_01_world_misc.sql

**Comment by FALL1N1** [comment]
sled res

**Comment by AnTOLI** [comment]
Работи :+1:
