### ISSUE TITLE
Gurubashi Arena Npc Short John Mithril

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#647]
http://wowwiki.wikia.com/wiki/Gurubashi_Arena Липсва евента с Нпц то http://wotlk.openwow.com/npc=14508  които отива до съндака и текста му.
Фикс https://github.com/yolinlin/trinitycore/commit/4c98a8e762c6749e41bdb4a776a1c0d8b5ca4d60

**Comment by FALL1N1** [comment]
sled res
