### ISSUE TITLE
HOL Hall of the Watchers 

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#648]
Не работи Hall of the Watchers с мобовете да атакуват http://www.wowwiki.com/Hall_of_the_Watchers в Halls of Lightning http://www.wowhead.com/zone=4272/halls-of-lightning
Фикс https://github.com/TrinityCore/TrinityCore/commit/2d884e7d0911897d5459ce0055f968a23ec8665b

**Comment by FALL1N1** [comment]
sled res, utre
