### ISSUE TITLE
Violet Hold missing spells

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#652]
http://www.wowhead.com/zone=4415/the-violet-hold Липсват  спелове на босове в инса  и други нещта.
Фикс https://github.com/mik1893/TrinityCore/commit/0bb7f89e82c65f6b750e5d96766c2092031803b5

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Не ги пуска порталите от които излизат Нпц та и  без тях не може да се мине инса.
Само те липсват.

**Comment by Ritokoko** [comment]
Все още е така.
