### ISSUE TITLE
Npc Frigid Necromancer missing SAI

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#655]
http://www.wowhead.com/npc=27539/frigid-necromancer#drops Некои нещто по Нпц то http://www.wowhead.com/npc=27539/frigid-necromancer#screenshots:id=92876.
фикс https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/5a2452f7d6a85a767e151c8ab5784da693d79286

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Работи :+1:
