### ISSUE TITLE
Ulduar npc missing text

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#656]
Липсва на некои Нпц в Ulduar текста.
Фикс https://github.com/TrinityCore/TrinityCore/commit/c385e537cc0aa9f61828068bd6a2d24b1288bfdc
https://github.com/TrinityCore/TrinityCore/issues/14299

SAY BRONZEBEARD RADIO  Dialogue and Flame leviathan.
Фикс https://github.com/evil-at-wow/scriptdev2-wotlk/commit/f4e4401669955dd439e682ec2c9ad8df6fc51751

Lore Keeper of Norgannon text
https://github.com/TrinityCore/TrinityCore/commit/f067bd8d9094b5c572db7dd5fb8c23d74a161bce

**Comment by FALL1N1** [comment]
test

**Comment by AnTOLI** [comment]
Само текста на не работи SAY BRONZEBEARD RADIO Dialogue and Flame leviathan 
https://github.com/evil-at-wow/scriptdev2-wotlk/blob/f4e4401669955dd439e682ec2c9ad8df6fc51751/sql/updates/r2930_scriptdev2.sql
Другите са добре.
