### ISSUE TITLE
Naxxramas Мissing

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#658]
Диалог на босовете в Naxxramas и други работи по инса.
Fix https://github.com/TrinityCore/TrinityCore/commit/f7a5a19f00d5a5df8df67b051a5606292d6eea6e

Kel'Thuzad Dialogue https://github.com/TrinityCore/TrinityCore/commit/0e995303fb80b5271a516b99b87a83ba61ce57ae
https://github.com/TrinityCore/TrinityCore/commit/037418a116b28ca3dedc52dac70e1d0e8a058ca9

 The Lich King SAY https://github.com/Locknes/ChaosCore/commit/ef3ad0378558c14c8c0164c3d9beb5e1699140d5 

Anub'rekhan encounter https://github.com/TrinityCore/TrinityCore/commit/91de0322bba3ef071338ce5a71f512369486eb1f 

https://github.com/TrinityCore/TrinityCore/commit/e1b322cda19b2e8fa0321dee8e2c27e4a6bd1628

https://github.com/TrinityCore/TrinityCore/commit/577fcf356e9cd54fb0490069d7aa26894e9b5db3

https://github.com/TrinityCore/TrinityCore/commit/91de0322bba3ef071338ce5a71f512369486eb1f

Four Horsemen dialogue.
https://github.com/TrinityCore/TrinityCore/commit/6c7472a6d33696d0695075b1229233145de0e81f

Портала не работи на  Боса Мaexxna  за да се върнем в началото на инса.
http://www.wowhead.com/npc=15952/maexxna
Fix https://github.com/TrinityCore/TrinityCore/commit/aff5229cd1777581bd85079d064037a57bf17799

Kel'Thuzad e като Duumy липсва траша  за ACH в началото които излиза.

Noth encounter Фикс https://github.com/TrinityCore/TrinityCore/commit/3fc1bb1abf0d4ae7b37507c62a3b57175477ce2f

Bosa Thaddius encounter не работи как трябва с + и –
add missing creature text
Фикс https://github.com/Treeston/TrinityCore/commit/29feae5901c049ef2204d956e83cf20507bed37a

Faerlina cleanup SAI spell.
Фикс https://github.com/Treeston/TrinityCore/commit/577fcf356e9cd54fb0490069d7aa26894e9b5db3

Frogger event SAI  https://github.com/TrinityCore/TrinityCore/commit/3629c4128f4df2df9f263bb2d58e291cc6a56eb1

Thaddius encounter
https://github.com/Treeston/TrinityCore/commit/29feae5901c049ef2204d956e83cf20507bed37a

**Comment by FALL1N1** [comment]
kel'thuzad e prenapisan, test.

**Comment by FALL1N1** [comment]
vsichko opraveno
