### ISSUE TITLE
Npc Gymer

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#659]
http://www.wowhead.com/npc=29647/gymer Не може да се говори с Нпцо за да се вземе Куеста от него.

**Comment by Ritokoko** [comment]
За този репорт мога да поспоря.Работи си .Вземаш http://www.wowhead.com/quest=12894 този куест .Той те препраща до http://www.wowhead.com/npc=29689/crusader-mackellar .След това като го върнеш ти отключва куест от нпц-то http://www.wowhead.com/npc=29688/engineer-reed . Продължаваш с тази поредица и ще стигнеш до даденото нпц Gymer

**Comment by AnTOLI** [comment]
Ми не мога да го взема но ми дава куест.
