### ISSUE TITLE
Npc Liquid Pyrite

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#660]
http://www.wowhead.com/npc=33189/liquid-pyrite#abilities Не работи не дава на Demolisher http://www.wowhead.com/npc=33109/salvaged-demolisher  Liquid Pyrite http://www.wowhead.com/spell=62494/liquid-pyrite  като си до него.

На Hard mode не може да се убие боса без него.

**Comment by FALL1N1** [comment]
fixed, test

**Comment by Warglaive** [comment]
Може да се вземе, проблема е че може да се вземе само 1 път и след като се изстреля и отново се качим на машината с която се дърпа pyrite-a , не излизат spells.

Иначе @AnTOLI трябва да го таргетнеш като го дърпаш, така е blizzlike.
