### ISSUE TITLE
Achievement : Disarmed 10/25

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#661]
http://wotlk.openwow.com/achievement=2953 Не работи и на 10 и на 25 мод.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Дава го дори да не е изпълнено както трябва.

**Comment by AnTOLI** [comment]
Не работи на 10 модем.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Не го дава нито на 10 нито на 25 мод
