### ISSUE TITLE
Achievement [Orbit-uary (25 player)] 10/25

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#670]
http://wotlk.openwow.com/achievement=3057 Не работи не ги дава като убием боса Flame Leviathan http://wotlk.openwow.com/npc=33113  с 4 кули активни в Hard modem.

**Comment by FALL1N1** [comment]
test

**Comment by kurevaglava** [comment]
Все още не работи!

**Comment by kurevaglava** [comment]
На 10 го дава ачивмънта,но само на хората които не са умряли по време на енкаунтъра.

**Comment by FALL1N1** [comment]
tets

**Comment by Warglaive** [comment]
На 25 мод - не дава нищо.
На 10 дава.
