### ISSUE TITLE
Achievement   [Shutout (25 player)] 10/25

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#671]
http://wotlk.openwow.com/achievement=2912 Не работи това постижение трябва да го убием боса преди да касне System Shutdown  и да го даде.

**Comment by Enragelolz** [comment]
Achievementa nqma nishto obshto s tova, koeto si napisul :)
Achievementa se vzima, kato ubiem bosa bez da mu pozvolqvame da castne System Shutdown.
System Shutdown se castva, kogato chovekut koito kara  (http://www.wowhead.com/npc=33109/salvaged-demolisher) izpolzva (http://www.wowhead.com/spell=62324/throw-passenger) i tozi passenger ubie Defense Turrets na Leviathana

**Comment by FALL1N1** [comment]
test

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Работи.
