### ISSUE TITLE
Quest :  [Cleansing Drak'Tharon]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#676]
http://www.wowhead.com/quest=12238/cleansing-draktharon Не може да се изпълни защото в инстанцията не дропва от нпц-тата http://www.wowhead.com/item=38303/enduring-mojo за да може на края на инстанцията да се съмме http://www.wowhead.com/npc=58149/image-of-drakuru за да се довърши поредицата за ачиевемента http://www.wowhead.com/achievement=1596/guru-of-drakuru

**Comment by FALL1N1** [comment]
test
