### ISSUE TITLE
Quest : The Aspirant's Challenge

### ISSUE THREAD

**Issue by Enragelolz** [Warglaive/DragonFireOriginal-3.3.5#677]
Ne moje da se govori s npc-to Squire David ( http://www.wowhead.com/npc=33447/squire-david ) , a ot tam sledva che ne moje da se summonne opponent za quest-a The Aspirant's Challenge ( http://www.wowhead.com/quest=13679/the-aspirants-challenge )

**Comment by Ritokoko** [comment]
Все още е така Squire David.

**Comment by Ritokoko** [comment]
Поради зачестели интереси към този куест ще завиша прио.

**Comment by FALL1N1** [comment]
fixed
