### ISSUE TITLE
Quest : Making Peace

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#678]
След като се върне предният куест http://wotlk.openwow.com/quest=12571 и http://wotlk.openwow.com/npc=28027 предостави на играчите http://wotlk.openwow.com/quest=12573 като се опитат да го вземат им изписва "you don't meet the requirements for that quest.Поради тази причина не могат да си продължат поредицата от куестове за The Oracles

**Comment by FALL1N1** [comment]
test
