### ISSUE TITLE
Quest : Banish More Demons

### ISSUE THREAD

**Issue by Vanx3lzing** [Warglaive/DragonFireOriginal-3.3.5#682]
http://wotlk.openwow.com/quest=11051 Не работи за момента.След като вземеш http://wotlk.openwow.com/item=32569 и отидеш на даденото място и се опиташ да отвориш Banishing Portal с куест итема http://wotlk.openwow.com/item=32696 изписва The spell is not available to you.

**Comment by FALL1N1** [comment]
fixed

**Comment by Vanx3lzing** [comment]
Все още няма промяна.
