### ISSUE TITLE
Quest : The Perfect Dissemblance

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#684]
http://wotlk.openwow.com/quest=12260 Не работи за момента.След като го вземеш и отидеш до http://wotlk.openwow.com/npc=27202 и активираш куест итема http://wotlk.openwow.com/item=37381 върху него излиза http://wotlk.openwow.com/npc=27203 но не завършва задачата.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Все още е така.
