### ISSUE TITLE
Quest : Conversing With the Depths

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#685]
http://wotlk.openwow.com/quest=12032 Не работи .След като го вземеш и отидеш на посоченото място http://www.thottbot.com/object=188422 и цъкнеш на перлата за да се появи http://wotlk.openwow.com/npc=26648 ,не се получава .

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Без промяна.
