### ISSUE TITLE
Npc : Wintergrasp

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#686]
Липсва  нпц за хордите и не могат да си закупят итеми от вендора http://wotlk.openwow.com/npc=32296 .

**Comment by FALL1N1** [comment]
@Warglaive  add

**Comment by Warglaive** [comment]
Wintergrasp missing.

**Comment by AnTOLI** [comment]
Wintergrasp не работи.?
