### ISSUE TITLE
Trial of the Champion Bug

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#690]
http://wowwiki.wikia.com/wiki/Trial_of_the_Champion Не може да се бият първите босове дори и да сме само хорде група.
Проблема е че ги сваляме от моунта и до тама не може да бием,
Би трябва да ни свалят всички от моунтовете дето яздим и да отидат и да ги бием без моутове босовете
https://youtu.be/qjHKHFuxBhA?t=3m48s

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Все още няма промяна.След като се убият пазачите на всеки от трите боса и се почне битка със самите босове ,като ги свалим и тях от техните маунтове те падат на земята все едно са мъртви и не могат да се атакуват.
