### ISSUE TITLE
NPC Illian Stormrage

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#693]
Босът има проблем на 3та фаза,защото на 30% трябва да ни стънне и да се появи Maiev,обаче босса ерорва.На 4та фаза която е метаморфозата боса не може да бъде убит а остава на 1 кръв.
http://wowwiki.wikia.com/wiki/Illidan_Stormrage_(tactics) .4та фаза проква през 40-50 секунди в 3та фаза и не е от толкова голямо значение.Проблема е че на 30% не може да почне 5та фаза,а ерорва.

**Comment by FALL1N1** [comment]
test za crash-a

**Comment by kurevaglava** [comment]
Бъгва се боса,ако не може да се оправи то поне да се махне евента и някои от фазите на боса и да се бие като другите босове в рейда.

**Comment by Warglaive** [comment]
Вече НЕ еррорва.
