### ISSUE TITLE
Tempering The Blade (Quest)

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#695]
Quest-a работи, трябва да се махне от Autocomplete таблицата / или да се направи да дава итема който изисква докато е autocomplete.
(http://www.wowhead.com/quest=24560/tempering-the-blade) Tempered Quel'Delar
@Edited

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Работи.Вече не е Ауто.
