### ISSUE TITLE
Achievement: Storm Glory

### ISSUE THREAD

**Issue by Enragelolz** [Warglaive/DragonFireOriginal-3.3.5#698]
При четири взети бази и поставяне на флаг-а, не отчита постижението : Storm Glory                                                               ( http://www.wowhead.com/achievement=211/storm-glory )

http://prntscr.com/98naw9
http://prntscr.com/98nb2a

**Comment by Warglaive** [comment]
Оправям ти двата репорта и за напред репортваи както трябва или не репортваи.

**Comment by FALL1N1** [comment]
test

**Comment by Enragelolz** [comment]
Отново не отчита постижението.

**Comment by FALL1N1** [comment]
trqq da e fixed veche

**Comment by Enragelolz** [comment]
отново не го отчита
