### ISSUE TITLE
[Quest] The Plains of Nasam [part 2 of 2]

### ISSUE THREAD

**Issue by Madleine** [Warglaive/DragonFireOriginal-3.3.5#7]
Трябва да се унищожат 100 единици, да се идентифицира лидера им и да се помогне на 3 ранени войника. Това всичкото трябва да се случи с помоща на танк, който се намира около зоната за изпълнение на куеста. Танкове има, но са развалени и неактивни - не могат да се ползват и няма как да се изпълни куестът.

http://www.wowhead.com/quest=11652
http://www.wowhead.com/npc=25334

**Comment by FALL1N1** [comment]
Оправен.
