### ISSUE TITLE
Achievement: Supreme Defender

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#705]
Ачивмънта http://wotlk.openwow.com/achievement=206 не работи.Не отчита киловете нито при killing blow ,нито при honorable kill.

**Comment by FALL1N1** [comment]
test

**Comment by kurevaglava** [comment]
Все още не работи.Тестван и при killing blow и при honorable kill.

**Comment by FALL1N1** [comment]
test пак

**Comment by kurevaglava** [comment]
Все още не работи.Тестван отново и при killing blow и при honorable kill.
