### ISSUE TITLE
Warrior Charge Path

### ISSUE THREAD

**Issue by Enragelolz** [Warglaive/DragonFireOriginal-3.3.5#709]
50% от Charge-овете по БГ–тата пропадам ...и още по лошото е, че някой път на ETOS като пропадна и не умирам, просто трябва да си седя AFK докато свърши Battle-а

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Пропадането се появява по-рядко, но все пак се появява.

**Comment by FALL1N1** [comment]
Давайте координати където се случи и снимки.
