### ISSUE TITLE
Quest: Bloody Breakout[Death Knight]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#71]
http://www.wowhead.com/quest=12727/bloody-breakout
Проблема е при Object:
http://www.wowhead.com/object=191092, след като се появи - веднага изчезва и играча няма възможност да го вземе.

**Comment by JunkyBulgaria** [comment]
Авто.

**Comment by FALL1N1** [comment]
Грешка...

**Comment by Warglaive** [comment]
Да се махне от аутокомплете графата и да се оправи проблема в темата.
Quest-a e много важен за дк-тата.

**Comment by FALL1N1** [comment]
Трябва тест.

**Comment by Warglaive** [comment]
Проблема стои.

**Comment by Warglaive** [comment]
High prio - DK quest chain.

**Comment by FALL1N1** [comment]
spawn ръчно

**Comment by Warglaive** [comment]
Проблема стой.

**Comment by Warglaive** [comment]
Fixed
