### ISSUE TITLE
NPC Sindragosa

### ISSUE THREAD

**Issue by kurevaglava** [Warglaive/DragonFireOriginal-3.3.5#710]
Боса http://wotlk.openwow.com/npc=36853 в последната си фаза когато пусне http://wotlk.openwow.com/spell=48400 и същевременно пусне http://wotlk.openwow.com/spell=70123, дърпа целия рейд включително и хората със томба и се замразява целия рейд,което не би следвало да става.И в последната си фаза дори и при група от само алианси или само хорди пак има 2 томба вместо 1.

**Comment by FALL1N1** [comment]
fixed
