### ISSUE TITLE
Oracles/Frenzyheart Tribe Quests.

### ISSUE THREAD

**Issue by smokatrap** [Warglaive/DragonFireOriginal-3.3.5#711]
При взимането на някой от куестовете и при двете страни, в които се изисква да убием 30/50 моба от противоположната фракция, нпс-тата от противоположната фракция са Unattackable със обикновени спелове. Могат да се бият само със масови магии, което го прави трудно за някой класове.
Подчертавам, че това става след като вземеш куест. Проблема е и при двете фракции.

**Comment by Ritokoko** [comment]
Проблема като цяло е ако минеш друг куест преди този и заради това не ти дава да ги атакуваш.Опитай да минеш първо него след това останалите и остави коментар.

**Comment by Ritokoko** [comment]
Вапростните куестове с които има проблем са следните . http://wotlk.openwow.com/quest=12761 и http://wotlk.openwow.com/quest=12703 .Могат да се направят само ако те се минат първи преди останалите деили куестове дали било за The Oracles или  Frenzyheart Tribe

**Comment by FALL1N1** [comment]
Моля за списък с дадените NPC-та.
