### ISSUE TITLE
Wintergrasp Battle

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#712]
http://wotlk.openwow.com/maps=4197 в тази зона битката е почти постоянна.След като дали било хорд или алианс спечели битката до една минута почва нова.Дефакто няма помеждутъка между две битки и не може да се ползва по този начин инстанцията http://www.wowhead.com/zone=4603/vault-of-archavon

**Comment by AnTOLI** [comment]
И да добавя като се направи машини от Нпц и ги изкараме от хангара с тях може да се лети в зоната и направо да бутнеш последната врата.

**Comment by Warglaive** [comment]
Всичко е на ниво.
