### ISSUE TITLE
Quest : The Scourgestone

### ISSUE THREAD

**Issue by Enragelolz** [Warglaive/DragonFireOriginal-3.3.5#717]
Куестът : [The Scourgestone](http://www.wowhead.com/quest=13122/the-scourgestone)
не може да се изпълни, защото куест итема : [Scourgestone](http://www.wowhead.com/item=43169/scourgestone), е с няк'во бъгаво ID и го засича като [Hearthstone](http://www.wowhead.com/item=6948/hearthstone) и не могат да се съберат 15 итема, защтото е Unique.  
http://prntscr.com/9cgdm1

**Comment by FALL1N1** [comment]
fixed

**Comment by Ritokoko** [comment]
Работи.
