### ISSUE TITLE
Achievement :  [Avast Ye, Admiral!]

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#718]
http://wotlk.openwow.com/achievement=871 . Някои хора не могат да го направят защото се изисква куест http://wotlk.openwow.com/quest=4621 но той не може да се вземе ако не си над френдли с http://wotlk.openwow.com/faction=87 и хеитед с Steamwheedle cartel .Но в момента не може да се сваля репотацията с тях. За да се вземе куеста и да се направи ачивмента.

**Comment by FALL1N1** [comment]
test
