### ISSUE TITLE
Quest : Find the Ancient Hero

### ISSUE THREAD

**Issue by Enragelolz** [Warglaive/DragonFireOriginal-3.3.5#719]
Куестът : [Find the Ancient Hero](http://www.wowhead.com/quest=13133/find-the-ancient-hero) не може да се изпълни. При намиране на [Iskalder-a](http://www.wowhead.com/npc=30884/iskalder) и кастване на  [The Bone Witch's Amulet](http://www.wowhead.com/item=43166/the-bone-witchs-amulet) върху него той става Friendly ( така трябва да е ), обаче не мърда и не може да се заведе при [The Bone Witch](http://www.wowhead.com/npc=30232/the-bone-witch), а този куест е част от Chain-a за [Battle at Valhalas](http://www.wowhead.com/quest=13213/battle-at-valhalas). След него има още 9 куеста.

**Comment by Ritokoko** [comment]
Все едно нещо не му дава да мръдне след като се кастне куест итема.До преди да стане Френдли те гони и се движи но не и след това.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Няма промяна.
