### ISSUE TITLE
quest 

### ISSUE THREAD

**Issue by puseto** [Warglaive/DragonFireOriginal-3.3.5#72]
GM poglednete  [Sniffing Out the Perpetrator] nemoje da se mauntne tigara za da se izpalni. Ako moje i da poglednete npcto Brijana v storm peaks nemoje da se vzeme questa ot neq kato se doblijish izchezva. I tozi ne raboti  [Thrusting Hodir's Spear]. +  [Feeding Arngrim] i tozi ne raboti

**Comment by Warglaive** [comment]
http://www.wowhead.com/quest=12855/sniffing-out-the-perpetrator
http://www.wowhead.com/quest=12910/sniffing-out-the-perpetrator

**Comment by AnTOLI** [comment]
fix https://github.com/TrinityCore/TrinityCore/commit/50853755d993f941973137d6db30bf53f1ac4b3d

**Comment by FALL1N1** [comment]
Оправен!
