### ISSUE TITLE
Quest : The tome of Divinity "Paladin"

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#721]
http://wotlk.openwow.com/quest=1786 Не работи. С дадения куест итем http://wotlk.openwow.com/item=6866 дето трябва да се съживи http://wotlk.openwow.com/npc=6172 не може да се изпълни задачата.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Все още е така.
