### ISSUE TITLE
Boss : Flame Leviathan

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#722]
http://wotlk.openwow.com/npc=33113 не може да се атакува и да се влезне в битка с него след като сме изчистили http://wotlk.openwow.com/npc=33237 .Нито с машина нито с спел магия или меле атака.

**Comment by FALL1N1** [comment]
fixed, test

**Comment by Warglaive** [comment]
Влизаи излиза от комбат постоянно, неможе да се пулне все още.

**Comment by Ritokoko** [comment]
Нямахме проблем с него на 10 мод
