### ISSUE TITLE
Achievement :  The Sickly Gazelle

### ISSUE THREAD

**Issue by Ritokoko** [Warglaive/DragonFireOriginal-3.3.5#725]
http://wotlk.openwow.com/achievement=223 Има проблем при този ачивмент .Когато убиеш даден играч на центъра на http://www.wowhead.com/zone=2597/alterac-valley докато той е на маунт не ти го отчита.А има и проблем при по старите акаунти на играчи .На тях дори и да работи пак не им го дава.

**Comment by FALL1N1** [comment]
test

**Comment by Ritokoko** [comment]
Не работи . Поне като бях алианс и убих от другия отбор играч но пак алианс
