### ISSUE TITLE
Quest : Forging an Alliance

### ISSUE THREAD

**Issue by Enragelolz** [Warglaive/DragonFireOriginal-3.3.5#737]
При complete на [A Spark of Hope](http://www.wowhead.com/quest=12956/a-spark-of-hope) от NPC-то [Thorim](http://www.wowhead.com/npc=29445/thorim) не може да се вземе следващия куест [Forging an Alliance](http://www.wowhead.com/quest=12924/forging-an-alliance)

**Comment by Herflik** [comment]
Mending Fences quest-a също трябва да cоmplete-неш за да ти отвори Forging an Alliance .
