### ISSUE TITLE
NPC: Big Ooze

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#74]
http://www.wowhead.com/npc=36899/big-ooze
Трябва да изчезне след умирането на бос RotFace, но не се случва.
Озе-то остава живо докато не се убие от раид групата.

**Comment by FALL1N1** [comment]
Оправен!

**Comment by Warglaive** [comment]
Все още го има проблема.

**Comment by Warglaive** [comment]
Оправено е.
