### ISSUE TITLE
NPC : Knot Thimblejack - #14338

### ISSUE THREAD

**Issue by Herflik** [Warglaive/DragonFireOriginal-3.3.5#741]
Knot Thimblejack - http://www.wowhead.com/npc=14338/knot-thimblejack#comments
Не се вижда от играчите .

**Comment by Warglaive** [comment]
Изкарано е, бях го скрил с цел да не се експлойтва.Скрил съм обекта който е към него, но все пак ако хвана някой да го експлойтва, ще има сериозни санкции.
