### ISSUE TITLE
You, Robot - Quest

### ISSUE THREAD

**Issue by Judgemenday** [Warglaive/DragonFireOriginal-3.3.5#749]
http://prntscr.com/9thfy7 - роботът не може да се управлява.
Лесно решение: http://prntscr.com/9thgn6 - ако Negatron се направи attackable, при убиването му куестът се изпълнява.

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/225

**Comment by Warglaive** [comment]
https://github.com/DragonFire/3.3.5/issues/225
