### ISSUE TITLE
DragonFire/3.3.5 ???

### ISSUE THREAD

**Issue by morfen** [Warglaive/DragonFireOriginal-3.3.5#751]
ако работи сървъра, дайте реалм листа.

**Comment by FALL1N1** [comment]
http://wow.hysteria-gaming.org/ сайт
реалм> set realmlist logon.hysteria-gaming.org

**Comment by morfen** [comment]
privet

Emiliyan nikade nemamiram klient za 5.4.1 za pandaria, vsi4ko e minalo na 5.4.8

**Comment by JunkyBulgaria** [comment]
https://gist.github.com/JunkyBulgaria/867ce855237fef7d15df

**Comment by FALL1N1** [comment]
http://www.mediafire.com/download/t0xvex6gi9t43j1/HysteriaWoW-5.zip
