### ISSUE TITLE
Какво се случи ?

### ISSUE THREAD

**Issue by NuclearPower** [Warglaive/DragonFireOriginal-3.3.5#752]
Съобщава ми по e-mail, че затваряте постове. От 2 месеца гледам, че всичко е изгоряло, няма следа нито от сървър, нито от сайт. Има ли начин да се свалят от датабазата поне героите на файл ли каква беше процедурата (ако изобщо съществува някаква запазена датабаза още - нещо, в което се съмнявам ....) ?

**Comment by FALL1N1** [comment]
Грешките са оправени за това и постовете са затворени, сървъра ще бъде анонсиран скоро.
