### ISSUE TITLE
seared scourge (Grizzly Hills)

### ISSUE THREAD

**Issue by Twohand** [Warglaive/DragonFireOriginal-3.3.5#81]
nemogat da se gorqt trolovete

**Comment by FALL1N1** [comment]
Повече инфо.

**Comment by Warglaive** [comment]
Quest:
http://www.wowhead.com/quest=12029/seared-scourge
Проблема е, че при използване на http://www.wowhead.com/item=35908/macks-dark-grog
върху NPC което трябва да бъде изгорено, нищо не се случва.

**Comment by FALL1N1** [comment]
Оправен!
