### ISSUE TITLE
Quest:  [We Strike!]

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#88]
http://www.wowhead.com/quest=11592/we-strike
NPC:
http://www.wowhead.com/npc=25335
трябва да тръгне, след като приемем quest-а, но евента не се стартира.

**Comment by AnTOLI** [comment]
Fix за куеста https://github.com/TrinityCore/TrinityCore/commit/5e5b8e2cd7cca8c8cfb0cd8ba2a5ede4e044139d

**Comment by FALL1N1** [comment]
Оправен!
