### ISSUE TITLE
[NPC] Eris Havenfire

### ISSUE THREAD

**Issue by Ligh7bringer** [Warglaive/DragonFireOriginal-3.3.5#9]
Npc-то Eris Havenfire, от което се взима куеста The balance of Light and shadow ( http://www.wowhead.com/quest=7622 ), го няма. Имам нужните тринкети (и 2та), но NPC-то не е където, пише, че трябва да е. Мисля, че може да ползвате готов fix от тук https://github.com/TrinityCore/TrinityCore/issues/11961

**Comment by FALL1N1** [comment]
Още ли е така?

**Comment by Warglaive** [comment]
Да, нпц-то липсва.

**Comment by Warglaive** [comment]
Spawn е.
