### ISSUE TITLE
The Obsidian Sanctum ACH bugget

### ISSUE THREAD

**Issue by stefanokis** [Warglaive/DragonFireOriginal-3.3.5#95]
Achievement [Gonna Go When the Volcano Blows (10 player)] neraboti

**Comment by AnTOLI** [comment]
Направете го хакфикс като го убием да даде постижението http://www.wowhead.com/achievement=2047/gonna-go-when-the-volcano-blows-10-player.

**Comment by AnTOLI** [comment]
Разбитие :)

**Comment by AnTOLI** [comment]
?
