### ISSUE TITLE
Achievement Call to Arms!

### ISSUE THREAD

**Issue by AnTOLI** [Warglaive/DragonFireOriginal-3.3.5#96]
http://wotlk.openwow.com/achievement=909 Не работи липсват куести за бг та за да се направи ачивмента.

**Comment by AnTOLI** [comment]
Няма ги  куести сложете ги. :)

**Comment by AnTOLI** [comment]
Развитие има ли.?

**Comment by AnTOLI** [comment]
Куестите не могат ли да се добавят в Нпц то. ?

**Comment by AnTOLI** [comment]
Разбите по куестите

**Comment by FALL1N1** [comment]
Оправени са!

**Comment by AnTOLI** [comment]
Куеста не го виждам в Нпцто Horde Warbringer.

**Comment by AnTOLI** [comment]
По точно като има Call to Arms не го дава Куеста за даденото БГ.

**Comment by AnTOLI** [comment]
Развитие.!

**Comment by AnTOLI** [comment]
Днес е Call to Arms на БГ то Eye of the Storm. Или не ги виждаме куеста в Нпц то или не са добавени.!

**Comment by AnTOLI** [comment]
Не ги дава яво трябва да се добавят ръчно от ГМ в Нпц то Куеста при започване на Call to Arms за даденото БГ или само ГМ може да ги вижда Куеста.

**Comment by AnTOLI** [comment]
До днес Нпц не дава никакви Куести за ачивмента. Като има този евент .

**Comment by FALL1N1** [comment]
test

**Comment by Warglaive** [comment]
Проблема стой.

**Comment by AnTOLI** [comment]
Не виждат куеста за бг то от Нпц то което ги дава.
Нз заради бъгави герои или е така става така Куестите.
